### ISSUE TITLE
Make initTable unnecessary

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/RFCs#101]
Recent changes make `string` and `seq` empty by default (not nil). It seems that it makes sense to also make Tables usable without initializing - we just need to check if `t.data.len == 0` before using the table in `[]=`, `[]` etc.

I did a small benchmark (inserting 1G elements). For 64-element tables, the change seems to make the whole benchmark about 4% slower.

**Comment by Araq** [comment]
This has been implemented and is shipping with Nim devel.
