### ISSUE TITLE
[tooling] cache compilation to avoid recompiling when possible

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#107]
The proposal is to introduce a flag (say,`-cache`) to cache compilation results including all needed artifacts:
* binary
* c/c++ files (etc)
* object files
* json file with dependencies

This feature is available in D via `rdmd`: when running the same thing twice, assuming nothing that could impact compilation result changed, the compilation step is omitted the 2nd time, resulting in instantaneous re-runs (useful for scripts among other things)

## implementation
* A1: when `nim c -cache foo.nim foo bar` gets run, nim creates a hash string `hashid` of all compiler flags (including cmd line ones and implicit ones from nim.cfg, config.nims, but excluding program arguments given after foo.nim, these are not cached so we can rerun with different such arguments)

* A2: it then checks whether `dir = nimcache/$hashid` exists:

* A21: if `$dir` exists, it looks at `json=$dir/deps.json` (currently this file is called `nimcache/foo.json` when compiling foo.nim, but under this proposal there would be 1 json for each `$dir`, so let's just call it deps.json)

* A211: if all dependencies `mydep` mentioned in `$json` are up to date (ie `mydep` still exists and `mydep.modificationTime < $json.modificationTime`), then nim skips compiling and runs the binary (which is stored as `exe = $dir/exe`) with arguments ` foo bar`
* else (if they're not up to date), nim compiles `foo.nim` as usual, outputting everything under `$dir`

* A212: else ( if `$dir` doesn't exist), it creates it and proceeds as in A211

## garbage collection
in `A212` step, to avoid using too much disk space, it also keeps track in `nimcache/cache.json` of an LRU cache, and removes old `$dir` folders according when either the number of such `$dir` folders is greater than a threshold, or when the time of last use (updated in A21 step) is older than an offset from current time

## related
I had actually opened an issue mentioning this, but it was closed as completed (other aspects were completed, but not this part), so I'm creating a more targeted issue just to track this
> generate the binary in nimcache, caching the resulting binary

* [TODO] could nimcache be generated out-of-source (in /tmp) like rdmd does in D? #7402

* https://github.com/nim-lang/Nim/issues/8910 is also related but deals with `nim c -r foo.nim` generating results under a nimcache folder, with no mention of caching binary output to avoid recompilation

## links
* see also https://github.com/marler8997/rund which was litterally just released as a faster rdmd /cc @marler8997

**Comment by Araq** [comment]
Do you really think that I don't know that? We're working on ``--incremental:on`` for a reason.

**Comment by Araq** [comment]
Duplicate.

**Comment by timotheecour** [comment]
related: https://github.com/nim-lang/Nim/commit/6ab4e1606ba86e416cac4ed39be07d14a1883ac7
