### ISSUE TITLE
[appveyor] queuing time is too slow (> 8 hours!) => should we buy more machines?

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#110]
https://ci.appveyor.com/project/Araq/nim/build/5592 shows appveyor is still waiting in queue after 8 hours; this is too slow:

Pull request #8614 - Nim now allows modules with same name in a package
mv tests/stdlib/tospaths.nim tests/stdlib/ospaths.nim to make sure it works on tests
5592
5 hours ago by Timothee Cour
exp_module_nonuniq  :  b67bc2f9 >  devel  :  701154dc
Queued

Should we buy more machines?
If there is no budget, I'm sure ppl will be happy to contribute for that (myself included); how much money is needed to double compute capacity for appveyor tests?

## Note
* this limited capacity also currently prevents doing useful regression testing such as suggested here: https://github.com/nim-lang/Nim/issues/8638
* for some reason, travis is less subject to this (although I'd also want travis CI runs to be faster); even though it runs both OSX and linux tests

**EDIT** it finally started after 8 hours of queuing:
![image](https://user-images.githubusercontent.com/2194784/44131175-05495ddc-a006-11e8-822c-c6fe83ad114d.png)

**Comment by Araq** [comment]
Appveyor queuing time is ok now.
