### ISSUE TITLE
`joinPath("foo", "/bar")` should return "/bar" 

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#112]
`joinPath("foo", "/bar")` should return "/bar" 
It's almost always the right thing to do. Eg:

* https://github.com/citycide/glob/blob/b6de2fd1a9eff022bc0006e565840f431cb99015/src/glob.nim#L197 has to introduce this workaround:
```
proc maybeJoin (p1, p2: string): string =
  if p2.isAbsolute: p2 else: p1 / p2
```

Most languages I use do that, eg:
D, python, C#

* D: https://dlang.org/phobos/std_path.html#buildPath
```
rdmd --eval 'std.path.buildPath("a", "/b").writeln'
/b
```

* python:
```
os.path.join('a', '/b')
Out[3]: '/b'
```
* C#: https://msdn.microsoft.com/en-us/library/fyy7a5kt%28v=vs.110%29.aspx

For C++: as mentioned here (https://github.com/rust-lang/rust/issues/16507#issuecomment-58791200) The C++ committee has recently been dealing with this problem.
http://isocpp.org/files/papers/n4211.html issue 64

* NOTE: the current buggy behavior is not documented (no example like `joinPath("foo", "/bar")` is provided) so that makes fixing it less problematic.

* The PR that fixes it should make sure overload `joinPath(parts: varargs[string])` is also fixed (with behavior: any absolute path found kills all the previous arguments) ; likewise with `/` operator

option B: if for some reason the breaking change is not acceptable, I suggest this: intoduce an optional third arg enum:
```nim
JoinBehavior = enum
  throwIfAbs # throw if 2nd arg is abs
  joinAsPath # behavior I suggest
  joinAsString # lagacy behavior
  
joinPath(string, string, joinBehavior = throwIfAbs) = string

joinPath("foo", "bar") # foo/bar
joinPath("foo", "/bar") # will throw
joinPath("foo", "/bar", joinAsPath) # /bar
joinPath("foo", "/bar", joinAsString) # foo/bar
```
option C: another option is to go ahead with the proposed semantic change but when a flag `--transition=8268` is given, throw when 2nd arg is abs

But I prefer to keep it simple and correct and follow the semantics of D, python, C#

**Comment by ZoomRmc** [comment]
Precedents are convincing enough, but I'd argue that the current beheviour seems logical: "Interpret `/bar` in context of `foo` being a parent directory". Might be useful in a hypothetical chroot scenario.

Current implementation of `relativePath` is broken, btw.

**Comment by Zectbumo** [comment]
Please take into consideration the security risk when changing the library:
```nim
"htdocs" / "/etc/passwd"
```
current version:
  file not found

after a surprise update that includes this proposal:
  returns passwd contents

Btw,
> NOTE: the current buggy behavior is not documented (no example like joinPath("foo", "/bar") is provided) so that makes fixing it less problematic.

This has since been documented.
https://nim-lang.org/docs/os.html#joinPath%2Cstring%2Cstring
`assert joinPath("usr/", "/lib") == "usr/lib"`

**Comment by Araq** [comment]
Rejected, it's a terrible idea and an invitation for security breaches.
