### ISSUE TITLE
[low priority] padding in alignString and strformat.fmt should be color and UTF8 aware, at least as option

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#113]
* when foo contains terminal escape color codes, `foo.alignString(n)` produces undesirable results as it counts 1 for each character instead of for each non-terminal escape code character. 100% support is not the goal, but at least supporting common color code escape sequences
* likewise with `fmt"{foo:<3}"`
* also would be nice to make alignment consider the width of unicode characters using same algorithm as one used in terminals for rendering UTF8 characters (eg chinese characters can take up more space)

**Comment by Araq** [comment]
Rejected.
