### ISSUE TITLE
`runnableExamples` should be run by `nim doc` even if symbol is not public

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#115]
runnableExamples would also be useful for private symbols

## proposal
`nim doc foo.nim` also runs runnableExamples on private symbols (instead of current behavior which is to silently ignore these).
it wouldn't appear in the docs (or, as a separate enhancement, could appear in a private symbols section of docs), but would help someone reading a module to understand private symbols.

## EDIT
see also: :point_up: [January 21, 2019 4:51 AM](https://gitter.im/nim-lang/Nim?at=5c45c068dab15872cecbe13d)
> Can nimdoc also generate documentation for non exported types and procs?

**Comment by nc-x** [comment]
Can be closed due to https://github.com/nim-lang/Nim/pull/10413
