### ISSUE TITLE
[docgen] generated docs should contain anchors for each section

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#117]
* https://nim-lang.github.io/Nim/contributing.html (and probably other generated html pages) don't have any anchors; eg I can't easily point to a specific section of that html page in code reviews
that's a bit odd because other pages (eg https://nim-lang.github.io/Nim/lib.html) do show anchors for each section
**EDIT** https://nim-lang.github.io/Nim/contributing.html#stdlib works but hovering on `stdlib` section doesn't show a url (from which you can right-click/copy link), unlike what happens when hovering on `Core` in https://nim-lang.github.io/Nim/lib.html

* **EDIT** no TOC is created for https://nim-lang.github.io/Nim/contributing.html

* symbols (procs etc) in docs (eg: https://nim-lang.github.io/Nim/algorithm.html) don't show anchors (eg for sorted, no anchor shown near proc definition) even though we can navigate to such section via https://nim-lang.github.io/Nim/algorithm.html#sorted%2CopenArray%5BT%5D%2Cproc%28T%2CT%29 ; it's just a matter of showing the anchor in generated docs

**Comment by mratsim** [comment]
This seems like an issue that doesn't require much discussion and with extremely low impact/risk so removing stale label.

**Comment by pietroppeter** [comment]
honestly I am not sure there even still is an issue and what would that be, I think it can be safely closed.

If I look at https://nim-lang.github.io/Nim/algorithm.html and scroll down to the first appearance of `sorted` the keyword `sorted` is indeed clickable (so I would say the anchor is accessible) and it gets me here: https://nim-lang.github.io/Nim/algorithm.html#sorted%2CopenArray%5BT%5D%2Cproc%28T%2CT%29

Again in https://nim-lang.github.io/Nim/contributing.html#stdlib if I hover over stdlib I do see the url.

I also see a TOC in https://nim-lang.github.io/Nim/contributing.html

**Comment by pietroppeter** [comment]
and in case there are still issues, it looks more than an issue for Nim than a RFC (maybe it was not at the time...)
