### ISSUE TITLE
execCmdEx and gorgeEx should have an option/overload to return (exitCode, stdout, stderr) instead of just (exitCode, stdout)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#118]
/cc @dom96 
as mentioned here: https://github.com/nim-lang/Nim/pull/8162#issuecomment-401859080
> tests would be easier to write once execCmdEx gets upgraded to capture (output, error, exitCode) (maybe via a different function name)

one question is naming: should that be called w same names as execCmdEx, gorgeEx

## side note
btw I dislike the name `gorgeEx`; IMO any CT variant that needs a different name to RT proc `foo` should be called predictably `staticFoo` /cc @Araq

**Comment by ZoomRmc** [comment]
Yes please.
