### ISSUE TITLE
testament should produce all its outputs in a gitignored directory

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#119]
.gitignore is polluted with entries from testament; furthermore it's not even complete (ie, git status is not clean after testament runs)
instead, testament should produce all its outputs in a (single) gitignored directory, for example $nim/build

We need to provide an easy way for tests to call: `buildDir / "myFile"`

**EDIT** => see PR https://github.com/nim-lang/Nim/pull/10274 that allows for that
EDIT: that PR was merged so we can now use `specialpaths.buildDir` in testament tests; for example:

```nim
import stdtest/specialpaths
let exe = buildDir / "D20190112T145450".addFileExt(ExeExt) # guid-like string enforces no clash and grep friendly
defer: removeFile exe # in case of a crash (eg user interruption with ^C), won't affect `git status`
# do something with `exe`
```

**EDIT**
PR https://github.com/nim-lang/Nim/pull/10293 fixes remaining cases

**EDIT**
that PR #10293 was closed :(

**Comment by Araq** [comment]
Rejected.
