### ISSUE TITLE
NimVersion should be of type`distinct string` and overload `<`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#127]
* code like `when NimVersion >= "0.17.3":` (eg in $nimc_D/tests/array/tarray.nim) is error prone/wrong:
echo "0.9.3" >= "0.10.3" # true !

* NimVersion should be of type `distinct string`, not string, and overload `<` to give it `semver` meaning of lexicographic cmp on (NimMajor, NimMinor, NimPatch)

* that'll also simplify code that uses following pattern to support backward compatibility:

## example 1:
(eg https://github.com/kaushalmodi/hello_musl/commit/1dc49900a32f95f4349fe083add3ec5a31bed1fe there are others) /cc @kaushalmodi
```nim
when NimMajor < 1 and NimMinor <= 19 and NimPatch < 9:
=> 
when NimVersion < "0.19.9""
```

## example 2:
just wrote this PR (which prompted me to write this issue) https://github.com/nitely/nim-regex/pull/34/files
```nim
when (NimMajor, NimMinor, NimPatch) < (0, 19, 9): # => easier/less error prone with when NimVersion < "0.19.9"
    type MyError = ref OverflowError
  else:
    type MyError = ref ValueError
  try:	  try:
    discard parseInt(first, firstNum)	    discard parseInt(first, firstNum)
    discard parseInt(last, lastNum)	    discard parseInt(last, lastNum)
  except OverflowError:	  except MyError:
```

## note
additional symver-specific procs can be defined on NimVersion as needed

**Comment by Araq** [comment]
1. Version checking should be rare, test for features instead.
2. ``when (NimMajor, NimMinor, NimPatch) < (0, 19, 9)`` works with every Nim version.
3. Version checking is the wrong place for innovations.

Closing.
