### ISSUE TITLE
Add websockets module to stdlib

### ISSUE THREAD

**Issue by lcrees** [nim-lang/RFCs#134]
Possilble starting point:

https://github.com/niv/websocket.nim/tree/master/websocket

Seems as useful an addition to the stdlib as FTP support.

**Comment by dom96** [comment]
I disagree and for what it's worth I don't think FTP would be in stdlib if it wasn't added back when Nimble didn't exist.

**Comment by Wh1teDuke** [comment]
Agree. In particular I used https://github.com/treeform/ws and thought it should be part of the std.

**Comment by hlaaftana** [comment]
No opposing comments for 3 years. Close as rejected?

**Comment by Araq** [comment]
Should be part of "fusion" IMO.

**Comment by hlaaftana** [comment]
I agree. We have to talk about a starting point though. I guess I'll talk about it here for now but the conversation can be moved to a fusion issue (or wherever you discuss fusion libraries) when it's ready.

Currently there are [4 packages focused on websockets on Nimble](https://nimble.directory/search?query=websocket) (I've seen it in other packages but only as a side module). [websocket.nim](https://github.com/niv/websocket.nim) is the original, [ws](https://github.com/treeform/ws) says it's inspired by websocket.nim and seems to be cleaner, and [news](https://github.com/tormund/news) says it's inspired by ws and supports chronos alongside asyncdispatch (will chronos be in fusion?). [The other one](https://github.com/stisa/jswebsockets) is for JS.

Websockets in "fusion" should cover both JS and an original implementation, so for JS we use jswebsockets and update the bindings after we start getting wrappers for Blob/ArrayBuffer/etc, and for the original implementation someone who knows all 3 libraries can give an opinion. I maintain websocket.nim but I know nothing about the other libraries.

**Comment by dom96** [comment]
> Should be part of "fusion" IMO.

Bah, why? Why is it up to Nim core devs to maintain a websockets library of all things? We've got a package manager, we've got a package ecosystem, let the community create a good package and let's adopt the best one.

**Comment by hlaaftana** [comment]
I thought fusion was made so core Nim and fringe common modules can be kept separate. Websockets are too general to be a project owned by 1 person but too niche to be included in standard Nim. There shouldn't be anything stopping core Nim devs from not working on it, am I wrong?

**Comment by Araq** [comment]
> Bah, why? Why is it up to Nim core devs to maintain a websockets library of all things? We've got a package manager, we've got a package ecosystem, let the community create a good package and let's adopt the best one.

Ok, fair enough.
