### ISSUE TITLE
Support modulo by Euclidean divisor

### ISSUE THREAD

**Issue by Paalon** [nim-lang/RFCs#135]
Nim's `mod` is modulo by truncated divisor but Euclidean divisor has many good mathematical properties than truncated divisor and more convenient in many applications.
https://en.wikipedia.org/wiki/Modulo_operation
I think Nim should have modulo based on Euclidean divisor, but there are some problems.
- There are quite few languages which have both modulo and adopt truncated divisor modulo as `mod` (according to wikipedia's page, only Fortran).
- Especially, most of the scientific computing programming languages have Euclidean divisors as `mod` (MATLAB, Maxima, R, Julia) or `Mod` (Mathematica) or  `modulo` (Fortran).
- There are many languages they adopt Euclidean divisors as `mod`, truncated divisors as `rem` (Ada, Closure, Common Lisp, Haskell, Prolog)

I like `mod` as Euclidean divisor, but I think discussions are required.

**Comment by juancarlospaco** [comment]
https://nimble.directory/pkg/euclidean
