### ISSUE TITLE
[feature request] add pragmas to specify/override nim flags directly in source code

### ISSUE THREAD

**Issue by slomp** [nim-lang/RFCs#136]
Since nim uses an unified build strategy (through imports and such),
a feature that could be very handy to make the main source module
more self-contained would be the ability to specify nim compiler flags
directly in code, through some sort of pragma, e.g.:
```nim
{.nim: "cpp --noMain nimcache=...".}
```
It would be very handy to also be able to introspect these compiler
flags in code, as compiler consts accessible by `when` directives.

**Comment by Araq** [comment]
That's way harder than it looks. ;-) We need to know about these switches when compiling ``system.nim``, for example. Why not put a NimScript config file next to your project file instead. That works with today's Nim.

**Comment by slomp** [comment]
Ah, indeed, I did not think about `system.nim`...

Cool, I did not know I could just add `--noMain` to `nim.cfg`!
Btw, presumably, I can simply list any nim compiler flag directly in `nim.cfg`, correct?

**Comment by slomp** [comment]
@Araq Should I close this issue, or is this something worth keeping around for future discussion?

**Comment by Araq** [comment]
Well switches with ``--`` can, the others are "commands" (c/cc/js/doc) and can't.

**Comment by Araq** [comment]
> Should I close this issue, or is this something worth keeping around for future discussion?

We need to focus. Sorry.
