### ISSUE TITLE
[feature request] have a way to prevent a `passC` setting in one nim file to latch over all nim files

### ISSUE THREAD

**Issue by slomp** [nim-lang/RFCs#137]
Currently, `passC` pragmas specified in one nim file will latch to all nim files that import it.
It would be useful to have some annotation to constrain the influence of `passC` to only the nim file that uses it.

In fact, for even more fine grained control, perhaps the `push` pragma could capture/fence `passC` changes until the corresponding `pop` pragma is found:
```
{.push, passC: "...".}
{.compile: "hello.cpp".}
{.pop.}

{.push, passC: "...".}
{.compile: "world.cpp".}
{.pop.}
```

**Comment by demotomohiro** [comment]
Nim has `localPassc` pragma now.
But it doesn't affect `compile` pragma used in the same nim file.
https://nim-lang.org/docs/manual.html#implementation-specific-pragmas-localpassc-pragma

**Comment by Araq** [comment]
The ``.compile`` pragma now supports specific C compiler options too, closing.
