### ISSUE TITLE
Support special functions

### ISSUE THREAD

**Issue by Paalon** [nim-lang/RFCs#138]
For implementing high-level scientific feature, such as probability distributions, special functions are required.

**Comment by liquid600pgm** [comment]
I don't feel like adding those functions would make life easier – if anything, they'll make the stdlib more bloated. Those functions probably aren't that common in typical programming (only in very high-level, functional use cases), so I'd say they should be a separate library, as adding them to the STL isn't going to provide the language with anything too useful for the majority of users.

**Comment by Araq** [comment]
Please use https://github.com/nim-lang/needed-libraries instead.
