### ISSUE TITLE
Allow overloading on type name

### ISSUE THREAD

**Issue by flaviut** [nim-lang/RFCs#14]
It's impossible to overload on a type name, ex.

``` nimrod
type
  Foo = object
    a: int

proc Foo(): Foo =  # fails to compile
  return Foo(a : 213)
proc Foo(val: int): Foo =  # also fails to compile
  return Foo(a : val)
```

Ideally, this would be possible and possibly even unified with the type construction syntax.

**Comment by hlaaftana** [comment]
The comments here don't really indicate a consensus, but I'm guessing it's likely this will not be done? Do we need to revitalize discussion or is this safe to be rejected?

**Comment by Araq** [comment]
There are ideas about adding constructors via a type bound ``=init`` operation (and it might be a good feature) but I don't know if that is related to "overloading on type name".

**Comment by hlaaftana** [comment]
I think the other RFCs about initialization cover enough about initialization, this RFC seems to specifically be about being able to giving routines type names. Another similar proposal might be like being able to define a call operator on typenames, not specifically related to custom initializers but related to the semantics of how custom initializers could be done.

**Comment by timotheecour** [comment]
I don't like this RFC (overloading on type), it creates inconsistencies:
```nim
type Foo = object
  x: int
proc Foo(x = 1): Foo = Foo(x: x)
echo Foo().x # 0 or 1?
echo Foo is proc # true or false?
Foo.bar # can MCS happen ? (ie: Foo().bar)
```

the following already works today, is explicit and has 0 ambiguities:
```nim
type Foo = object
  x: int
type Bar1 = object
  y: int
type Bar2[T] = object
  y: T
type Baz = object
  x: int
proc init(T: typedesc[Foo], x = 123): T = T(x: x)
proc init(T: typedesc[Bar1 | Bar2], y = 123): T = T(y: y)
proc init[U](T: typedesc[seq[U]], n = 0, cap = 0): T =
  if cap == 0:
    result = newSeq[U](n)
  else:
    result = newSeqOfCap[U](cap)
    if n > 0: result.setLen(n)

echo Foo.init()
echo Foo.init(x=2)
echo Foo.init(2)
echo Bar1.init(2)
echo Bar2[int].init(2)
echo seq[int].init(2)
echo seq[int].init()
echo seq[float].init(cap = 3)

doAssert not compiles(Baz.init(2))
```

the case of default constructors (ie, `var a: Foo` and `Foo.default`) is the topic of https://github.com/nim-lang/RFCs/issues/290 (`=default` type bound constructor)

IMO we should close this RFC
