### ISSUE TITLE
Allow procs to be put under headings in docgen

### ISSUE THREAD

**Issue by dom96** [nim-lang/RFCs#140]
As discussed in #10752, I believe it would be really advantageous to enable us to put procedures under headings.

Something like:

```nim
## Main procedures
## -----------------
## 
## These are the main procedures in the module, the rest are irrelevant. Here is how you use them...

proc toMD5() ...

## Less useful procedures
## -----------------------
##
## Don't use these unless you have no other choice
```

**Comment by narimiran** [comment]
> We can have a mix too, like only specify the high-level docs in the separate file but keep the proc-specific docs inside the .nim file

Something like it has already been done and discussed in https://github.com/nim-lang/Nim/pull/10429 ?
