### ISSUE TITLE
Package Nim on npm

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/RFCs#147]
Distributing Nim and Nimble via npm would significantly lower the entry barrier for Javascript developers. A dependency outside the standard ecosystem is often a showstopper for adaption, especially in a workplace environment where ad-hoc installation of a native dependency is not an option. With `nim` and `nimble` published as binaries on npm, it would be possible to build an entire Nim-based front-end with a standard `npm install`/`npm run build`. This is also a typical requirement for inclusion in JS benchmarks [like this](https://github.com/krausest/js-framework-benchmark#how-to-contribute).

I have no experience with npm packaging at all, but I'll try to collect a few resources to show how other packages on npm have solved the problem. Maybe we can find someone with more experience to chime in.

Examples of binary packages:
- The Elm compiler is build in Haskell, and thus required binary distribution. [Apparently it uses](https://www.npmjs.com/package/elm/v/0.19.0-bugfix6?activeTab=dependencies) an npm packages called [binwarp](https://www.npmjs.com/package/binwrap)
- node-sass relies on libsass, a C library. It's not fully clear to me how the installation of the binaries is handled, but it looks like it is [fetching](https://github.com/sass/node-sass/blob/0c1a49eefa37544d16041c5fe5b2e3d9168004b7/lib/extensions.js#L212-L238) the pre-packaged binaries for [GitHub releases](https://github.com/sass/node-sass/releases).

Other resources:
- SO question: [bundling precompiled binary into electron app](https://stackoverflow.com/q/33152533/1804173)
- SO question: [How can I bundle a precompiled binary with electron](https://stackoverflow.com/q/38361996/1804173)
- SO question: [Distribute pre-built native binaries in npm](https://stackoverflow.com/questions/26596814/distribute-pre-built-native-binaries-in-npm) (answers seem off-topic)
- Potentially related [github ticket](https://github.com/nodejs/node-v0.x-archive/issues/4398).
- Electron documentation on [native modules](https://electronjs.org/docs/tutorial/using-native-node-modules)

@dom96 Do you think we can leverage choosenim by pointing this binwrap package to the [choosenim releases](https://github.com/dom96/choosenim/releases)?

**Comment by dom96** [comment]
> @dom96 Do you think we can leverage choosenim by pointing this binwrap package to the choosenim releases?

Please don't do that. Choosenim is designed to be a standalone tool. If you want to package Nim/Nimble in npm then do so using a tarball containing Nim/nimble binaries.

To be honest I think it's fair if you want to package it, but I don't think supporting it officially is worthwhile. There is already hundreds of ways to install Nim and every additional way makes it more likely that the user will get a broken installation.

**Comment by bluenote10** [comment]
> There is already hundreds of ways to install Nim

What I have observed now several times: As far as I know Nim isn't available on any standard package manager, which makes it quite hard to use Nim in a restrictive work environment. If you want to introduce Nim gently for a tiny task like a small JS frontend, you cannot ask a large team of developers to handle that non-trivial dependency manually. It is much more feasible, if the dependency can be handled as part of the standard tooling of the team. Also let's not forget that the dependency of a native C compiler may look completely natural for Nim users targeting C, but for web developers targeting JS it can be a showstopper. That's why I think from all the standard package managers, npm makes the most sense.

Even for personal use don't underestimate the power of a low entry barrier. For instance I only got into Elm development because I could clone a "starter" repo, type `npm install`, and I was coding within seconds because distribution followed a standardized procedure. 

In my opinion an official npm package is a low hanging fruit to help Nim adaption.

**Comment by krux02** [comment]
If there are problems to package nim+nimble via npm, I will accept them as valid issues on nim (I have no say in nimble). I think nim should be as easy to package as possible. But speaking for myself, I cannot maintain npm packages, but I think it should be as easy as possible for the community to maintain such a package (and other packages for more obscure package managers).

**Comment by Araq** [comment]
Package it or not for NPM, but we don't.
