### ISSUE TITLE
Pragma syntax

### ISSUE THREAD

**Issue by ozra** [nim-lang/RFCs#15]
Sorry for pestering with issues, I just haven't felt this fired up about a programming language for 16 years. So, the only things that annoy one, among all this greatness, itch a little in the fingers..

The pragma syntax is plain hideous. It's mainly because of the dots. In my programmer-eyes at least, the dots 'tie' to their nearest identifier-looking tokens, rather than appear as out-of-the-way pragma-block-delimiters. The otherwise so lovely and clutter free looking code, gets sucker punched by it.

If I may so humbly suggest with my new adopter eyes, if such a small addition as the following notation could not be a lot clearer? They both could co-exist without parsing ambiguity, right? Could it please be considered? It would be such a C++'ish wart that I so dearly want to escape.

I could make a stab at it, but I definitely have to get up to speed with Nim first.

``` nim
proc isCounter(s: PSym): bool {{inline}} =
  s.kind in {skResult, skVar, skLet, skTemp} and 
  {sfGlobal, sfAddrTaken} * s.flags == {}

proc isCall(n: PNode): bool {{inline}} =
  n.kind in nkCallKinds and n[0].kind == nkSym

```

**Comment by jjzmajic** [comment]
How about
```nim
+[async]
proc foo(x: int): string =
    ...
```
Visually familiar to rustaceans, removes the signature clutter, and feels like adding a "property" to a `proc`. Kinda reminiscent of org-mode options too. Would this cause any syntactic clashes?

**Comment by Araq** [comment]
Definitely, currently it's valid Nim syntax, unary plus followed by an array construction...

**Comment by FedericoCeratto** [comment]
Nesting the pragmas under the proc definition seems more natural to me. A single character (e.g. `@`) should be enough. This could support multiple pragmas per line and also multiple lines for better readability:

```nim
proc tryInsertID*(db: TDbConn, query: TSqlQuery): int64 =
  @pure, raises: [], effects: []
  @tags: [FWriteDb]
  @deprecated
  ## executes the query (typically "INSERT") and returns the 
  ## generated ID for the row or -1 in case of an error. 
```

**Comment by mfiano** [comment]
As a newbie to Nim, I also find the `{..}` syntax a bit jarring, as well as the placement in procs when dealing with long signatures that have to be multilined. It would be nice to have a dedicated section for optional pragma declarations before the body, similar to Common Lisp's `declare`, or more Pythonic before the definition. I think the `{..}` syntax is edging too close to symbol noise for me.

**Comment by liquid600pgm** [comment]
@FedericoCeratto keep in mind that statement pragmas like .push and .pop are a thing, so your syntax would most definitely clash with that.

**Comment by jprochazk** [comment]
I'm also a newcomer to Nim, coming from C-like language background. The placement feels like it gets "lost" once you have more than a single line. I would support keeping the syntax, but changing the position to after the `proc`, `var`, `type`, etc statement:

```nim
proc tryInsertID*(db: TDbConn, query: TSqlQuery, 
                  args: varargs[string, `$`]): int64
                  {.tags: [FWriteDb], raises: [].} = ...

var
  a {.noInit.}: array[0..1023, char]

type
  MyFlag* {.size: sizeof(cint).} = enum
    A, B, C, D
  MyFlags = set[MyFlag]
```
becomes:
```nim
proc {.tags: [FWriteDb], raises: [].} 
  tryInsertID*(db: TDbConn, query: TSqlQuery, 
               args: varargs[string, `$`]): int64 = ...

var
  {.noInit.} 
  a: array[0..1023, char]

type
  {.size: sizeof(cint).} 
  MyFlag* = enum
    A, B, C, D
  MyFlags = set[MyFlag]
```
Would this introduce any other ambiguity?

**Comment by Araq** [comment]
> Would this introduce any other ambiguity?

I am quite sure this wouldn't introduce an ambiguity. It's ugly for my taste, but technically it would work.

**Comment by Varriount** [comment]
@jprochazk I've argued before about using syntax similar to Python, at least for procedures and types. Although in that case, the position for pragmas attached to procedures would be before ```proc```.

**Comment by Araq** [comment]
Reasons not to do anything:

- Invasive change now that 1.0 uses ``{. .}``.
- You can change your editor to render ``{. .}`` in a more aesthetically pleasing way.
- The "there must be only one way to program" purgers would send PRs correcting the code to use the new, better syntax all the while 1.0 doesn't support it at all. So the people who value stability are stuck with the old syntax anyway.
- The old syntax is not bad enough to warrant these disruptions.
