### ISSUE TITLE
The names “Rune” and especially “Rune16” are misleading

### ISSUE THREAD

**Issue by Serentty** [nim-lang/RFCs#151]
The term “character” is often avoided these days both to avoid confusion with bytes (an association that exists in countries with strong traditions of single-byte character sets), and to sidestep the issue of what exactly constitutes a character when grapheme clusters, which are what users generally perceive as characters, can be made up of more than one code point. The Unicode “character” type in most new programming languages these days can hold a single code point, and the issue then arises of giving it a friendly name. For example, Rust assigns this type the name `char` to this type to establish it as the successor to the old byte-based `char`, but also while allowing for notions such as “combining characters” and “control characters” which have made their way into the consciousness of programmers over the years.

Nim (perhaps inspired by Go, which also uses this terminology) uses the name `Rune` for this type, which has the advantage of having no real attached legacy baggage as a name. However, I would argue that in popular, non-computing consciousness, the meaning of the word “rune” is generally something along the lines of “glyph”, which is definitely not what such a name should convey when many code points represent whitespace, invisible control characters, combining diacritics, and even variation selectors which carry extra information about how the code point before them should be displayed. The assumption that code points correspond to grapheme clusters has broken a lot of software in the past, and misleading naming of types and functions related to text has been the cause of a lot of those programmer errors. In my opinion, the name `Rune` carries an even stronger implication of code points corresponding to grapheme clusters than “character” does, which is already not an ideal name.

Of course, if `Rune` isn't acceptable, then there needs to be an alternative. The type `char` is already used in Nim, so any name with something resembling “character” in it is likely to lead to confusion with that type. There are no easy answers to what the ideal name is, and the best answer that I can give would be `CodePoint`, as it corresponds directly to documentation that programmers will read about Unicode, and doesn't require learning what corresponds to what in Nim. If that name is too long, then perhaps some shorter name which conveys the same meaning could be devised.

If you've read up to this point and are still convinced that this is pointless bikeshedding and that the name `Rune` is perfectly fine, then I'd like to at least make the case that the name `Rune16` needs to go. If with the name `Rune` we have established that “runes” are code points, then the name `Rune16` is misleading because it does not actually represent a code point at all, but rather a “code unit” of UTF-16. All UTF encodings use code units. In the case of UTF-8, a code unit is a single byte, and in UTF-16, it's two bytes. Unlike code points, code units do not correspond to anything meaningful, and are simply low-level details of the binary encoding, just as “the low nybble of an ASCII byte” isn't particularly meaningful in terms of what the character will actually be. The name `Rune16` makes it that much easier for a programmer new to Unicode (or a programmer who still has pre-1996 ideas about Unicode) to mistakenly think that it's meaningful to speak of “a 16-bit Unicode character”. Because of this, even if the name `Rune` stays, I would like to see `Rune16` renamed to `CodeUnit16` or something similar.

**Comment by Araq** [comment]
We'll happily deprecate ``Rune16``, it's not used in Nim's stdlib anywhere afaict.

**Comment by Serentty** [comment]
That's a good solution I think. That's the part I was most concerned about.
