### ISSUE TITLE
Either encourage using `cpp` compiler command as much as possible in the docs or change the meaning of `c`/`compile`

### ISSUE THREAD

**Issue by awr1** [nim-lang/RFCs#152]
In general, we're heading in a direction where we want to prefer generating C++ code as Nim's "native" solution in lieu of C code as the Nim compiler has "traditionally" done it. From the IRC:
```
<vegai_> the 0.20 video mentions that the CPP backend is superior to the C backend in a few ways
<vegai_> does that imply that I should default to the CPP backend whenever I can?
<vegai_> any downsides? Except feeling dirty :⁠P
<leorize> there are more cpp codegen bugs than the c backend :⁠p
<leorize> most of them have been swept, but since the backend is rarely used in actual project, we can't expect anything
<Araq> vegai_, yes, IMO you should default to the C++ backend
```

However, this is not adequately reflected in the docs, e.g. at the beginning of the [Nim tutorial](https://nim-lang.org/docs/tut1.html) or the [compiler guide](https://nim-lang.org/docs/nimc.html).

We could just rewrite the docs to use `nim cpp` here but in my opinion, `compile` should default to `cpp` in the future. This puts in a slightly weird situation as people tend to use `nim c` a lot and the `c` could be inferred as meaning C, the language, and not shorthand for "compile." Of course, `nim cc` is already available as producing C output.

This doesn't have to be done "immediately" per se, but rather an eventuality for the future. Alternatively it could be pushed sooner to devel to accelerate the C++ backend's maturity.

**Comment by andreaferretti** [comment]
Are there considerable differences in time if we compile to C++ instead of C? For various reasons (templates mostly), C++ compilers are notorious for being slow, but maybe if the generated code does not use these features, the compile times stay the same.

In any case, I see more possible downsides in compiling to C++:

* C++ is a much more moving target than C, with new revisions adding to the language significantly
* C is a much simpler language than C++, and this can make the generated C sources more readable. I am pretty sure many more people have some familiarity with C than C++
* For the same reason, defaulting to compile to C++ may make more difficult to contribute to the compiler

**Comment by awr1** [comment]
>Are there considerable differences in time if we compile to C++ instead of C? 

I have not tested this personally, but like you said, usage of C++'s features is what really boosts compile time - since it is unlikely Nim will use C++ templates in any significant way (beyond bindings) I doubt there would be much difference. Plus, we have faster compile times in the future to gain from incremental compilation.

> C++ is a much more moving target than C, with new revisions adding to the language significantly

This is true, but the revisions that the committee makes are often somewhat restricted - the committee does not want to start over and make a language like Nim from scratch, they want to "fix" their language into a modern one without breaking old code, and many of the members of the committee have a vested interest in keeping their old code working on modern compilers without much fuss. It took a very long time for the C++ committee to finally get rid of [trigraphs](https://en.wikipedia.org/wiki/Digraphs_and_trigraphs#C++), for instance.

> C is a much simpler language than C++, and this can make the generated C sources more readable. I am pretty sure many more people have some familiarity with C than C++

From what I recall the only C++ mechanism the Nim codegen (by itself) really uses is C++'s exception handling system, otherwise, it is more or less the same. I don't expect future Nim to be importing Boost and outputting Rule-of-5 code at the drop of a hat unless you're trying to use some weird bindings.

Also, Nim is not CoffeeScript. The compiler output is not meant to be read - at least, ideally. Of course, someone eventually needs to be able to debug compiler output...
