### ISSUE TITLE
Deprecate `[]` for dereferencing and replace by `deref` proc

### ISSUE THREAD

**Issue by mratsim** [nim-lang/RFCs#154]
Sparked by https://github.com/nim-lang/Nim/issues/11705 and https://github.com/mratsim/Arraymancer/issues/185.

The dereferencing operator in nim is `[]` which has the following characteristics:
- pro: short
- con: unsearchable for new Nim users
- con: causes problems with overloading like
  ```Nim
  proc `[]`[T](a: MyMultidimensionalArray[T], indices: varargs[untyped]): T =
    discard
  ```
  now suddenly an empty varargs will conflict with the dereferencing operation.
- con: when scanning for unsafe construct, `[]` will highlight spurious overloads.
  In Nim, we understand that unsafe code is unavoidable but those unsafe operations
  do not have a shorthand to make them less convenient and to make them easier to find.
  For example we have: `cast`, `addr`, `unsafeAddr`, `UncheckedArray`, `ByteAddress` that deals with addresses.
  The dereferencing operator should be on that list and should not take only 2 chars.

**Comment by Araq** [comment]
That's crazy talk. If overloading of the deref doesn't work, we can deprecate this idea. Most of the time, deref is not even written out! ``myRef.field`` is **everywhere** and for good reasons.

**Comment by mratsim** [comment]
I think there is a misunderstanding, I'm not talking about changing how implicit dereferencing works for ref objects or ptr objects or even [automatic dereferencing](https://nim-lang.org/docs/manual_experimental.html#automatic-dereferencing).

I just propose that for explicit dereferencing, a name like `deref` is better than an operator, especially one such as `[]` which is often overloaded with varargs.

**Comment by krux02** [comment]
I like to disagree. For the multidimensional array. use either ``openArray`` or a vector type (e.g. ``glm.Vec4i``), then it won't cause conflicts in overload resolution, because there will always be one Argument. For the other issues, I think the cost outweighs the benefit.

**Comment by andreaferretti** [comment]
@mratsim is talking about the case where the number of axes is not fixed a priori (i.e. designing a tensor library). `Vec4i` is (I think) about the 1 axis case, that is a vector, of dimension 4. Arraymancer needs to be able to - say - take a slice of a 6-axes tensor along the first two axes or something like that

**Comment by mratsim** [comment]
To give more context, in Arraymancer I need to be able to handle:

- 1-dimensional vectors
  for example, a vector of 1000 elements
- 2-dimensional matrices
  for example, a matrix representing a 200x200 grayscale image
- 3-dimensional tensors
  for example, a tensor representing a 200x200x3 RGB image
- 4-dimensional tensors
  for example, a tensor representing a batch of 128x200x200x3 RGB image
- 5-dimensional tensors
  - for example, a tensor representing a batch of 10 3d-image of shape 10x512x512x512x3.
    Note that this is not a theoretical scenario, lots of medical data coming from CT scans are stored as 3D-image in Dicom format and there have been several high-profile challenges in the past years involving them.
  - Another example are batches of videos for video classification or self-driving cars
- 6-dimensional tensors
  No example, no one uses deep learning for 3D-video

**Comment by krux02** [comment]
Maybe an alias for `[]` called `deref` would not hurt Nim. Nim uses a word for ``addr``, it simply makes sense to have a word for the inverse as well. But really I don't like to take out ``[]`` as it is right now from the language. It has been like this for too long.

**Comment by Araq** [comment]
You can try to use:

```nim

proc `[]`[T](a: MyMultidimensionalArray[T], firstIndex: untyped; indices: varargs[untyped]): T =
  discard

```

Plenty of other solutions exist like not making `MyMultidimensionalArray` a `ptr` or `ref`.
