### ISSUE TITLE
Multi-line string literals (blocks of lines)

### ISSUE THREAD

**Issue by Tronic** [nim-lang/RFCs#161]
I would suggest -- instead of, or in addition to Python-style """ literals -- using indented block syntax for multi-line string literals. E.g.

````nim
proc foo =
  let str = ":
    Hello
      World!
  stdout.write str
````
Where str is defined equivalent to
````nim
let str = "Hello\l  World!\l"
````

This syntax avoids the indentation problem with string literals that .unindent attempts to address. Also, for clarity, all string content appears within the block, not on the opening or closing lines as is with """.

The literal terminates as soon as the block ends (i.e. a non-empty line indented less is found), avoiding the need for """ at the end. This also avoids the need to escape double quotes that belong to the string.

Whitespace at the end of any line and empty lines at the end would be omitted (and could be added via escape sequences in the rare cases where needed). Whitespace-only lines in the middle would become simply \l (no matter if there are spaces or not). This removes any ambiguity with source code formatting and makes the intention explicit.

This suggestion proposes string block to be indented by exactly two spaces (compared to the line with ": in it). Any further initial spaces would become string content.

This could still be used within parenthesis or other expression, provided that the continuation of that expression appears less indented than the string content.

**Comment by juancarlospaco** [comment]
YAML already has a very well known and documented contruct for this, why not just use that.

I think is awesome that you can use literal JSON on Nim code directly, 
then maybe copy that feature of YAML too. 
YAML is an open format, and already supported by tons of software.

YAML syntax can be very friendly as start of a block because it uses `:>` or `:|`

https://en.wikipedia.org/wiki/YAML#Indented_delimiting
:thinking:

**Comment by SolitudeSF** [comment]
`:|` and `:>` could clash with user defined operators, while `":` cant.
but i dont see why this should be a language change, if all it does is breaks every syntax highlighter.

**Comment by juancarlospaco** [comment]
```
sugar.`:>` 
``` 
then :grey_question: 

I agree that I dont feel a huge need for this. 🤷‍♀️

**Comment by Tronic** [comment]
FWIW, a comment at the end avoids problems with current highlighters without changing anything else (a simple hack - not part of RFC):

````nim
    await client.send ":
      HTTP/1.1 200 OK\r
      content-type: text/plain\r
      content-length: 13\r
      \r
      Hello World!
    #"
````

**Comment by juancarlospaco** [comment]
> a comment at the end avoids problems
> a hack

:thinking:

**Comment by SolitudeSF** [comment]
@Tronic which highlighters? github doesnt highlight correctly anyway.
in my editor its this
![image](https://user-images.githubusercontent.com/10168645/63280987-7d15e700-c2b4-11e9-836f-8033fd5a42f6.png)

which is correct representation of current syntax, since `"` strings cant be multiline.
and no, `#"` is not a solution even if it worked.

**Comment by Tronic** [comment]
@SolitudeSF I use this in VSCode. Obviously tools need to be fixed, and that really shouldn't be a big issue. After all, they already manage to handle the mix of different quotation formats & comment parsing, incl. Nim-specific syntax and escape sequences.

**Comment by juancarlospaco** [comment]
For stuff like this I just use `staticRead` 🤷‍♀️

**Comment by SolitudeSF** [comment]
i dont see how this can be trivially fixed, since most editors use regex based highlighting which cant have indentation awareness.

**Comment by juancarlospaco** [comment]
Too bad you can not do the `strformat` formatted multi-line literal `fmt"""  """` in there. :crying_cat_face:

**Comment by krux02** [comment]
@Tronic If editor support can't be provided, I can only reject this feature. What value does it have when it virtually no editor will support it, or if it will take years until the editors will have a solution for it? Also I am the one who maintains the emacs integration at this point, it is not like that emacs will magically grow support for this feature.

**Comment by awr1** [comment]
I'll admit I was wrong about `unindent()` not needing any change, but I would _much_ prefer `unindent()` to be fixed. It honestly feels way too late in the game for a grammar change like this, especially one that may not be reliably workable with certain editor syntax highlighting engines.

**Comment by Tronic** [comment]
@SolitudeSF Regex cannot match indent? `\n([ \t]*)[^\n]*":\n(\1  [^\n]*\n|[ \t]*\n)*` matches this string block. Use backward lookup or editor's custom handling of captures, if necessary. Every serious editor implements some sort of recursive matching in addition to basic regex to be able to do parenthesis matching, to handle HTML closing tags etc.

If nimpretty is a concern, I am sure I can quickly patch that as well.

**Comment by GULPF** [comment]
If this can be properly highlighted with a `tmLanguage` syntax definition (what vscode and many other editors uses) I would be interested to se how. I think it's impossible but I don't know for sure. I tested the YAML `tmLanguage` syntax definition and it seems pretty broken for strings.

**Comment by Tronic** [comment]
This sort of approach seems to work (tried in VSCode):
````
"begin": "( *)(\":)$",
"while": "^\\1  ",
````
I'll have a proper look later.

**Comment by Clyybber** [comment]
@Tronic AFAICT your regex cannot deal with arbitrary indentation. In Nim indenting with all numbers of spaces is allowed. If there exists a regex that can work with arbitrary indentation then I will support this feature.

**Comment by Tronic** [comment]
VSCode highlighter updated to support `r":` and `":` literals. It seems to be working but needs more testing.

@Clyybber Surrounding code may be indented by arbitrary number of spaces. String block contents must be indented by exactly two spaces, compared to leading line, as discussed in this thread. This is to allow indentation to appear within string content, so any indentation on top of those two spaces are included in the string.

**Comment by Clyybber** [comment]
@Tronic I don't think we should enforce those to be indented by exactly two spaces.
Instead make the first line dictate the indentation, or make the most left line of the string block dictate the indentation.

**Comment by timotheecour** [comment]
@Tronic 
relevant discussion: https://forum.nim-lang.org/t/471#23415 (Does Nimrod have a heredoc syntax?)
this RFC would have to compare its merits against heredoc.

## pros of heredoc (as used in D, see https://forum.nim-lang.org/t/471#23415):
* visually clear (and easy to grep) where string ends
* copy pasting a string doesn't require re-indenting it; but indenting at same level as code (followed by `.unindent`) is an option if user prefers to keep their string at block indent
* works in all cases (a suitable identifier always exists that prevents a clash with given string); see note in https://forum.nim-lang.org/t/471#23415 regarding a non-ambiguous way to terminate the heredoc string that can represent any string even if it doesn't end with `\n`

**Comment by Araq** [comment]
If the argument is "you can always come up with a delimiter that isn't used" than Nim's triple quotes work just as well:

```nim

const
  s = """
foobar
UNUSED_DELIM
baz
""".replace(UNUSED_DELIM, "\"\"\"")

```

Requires no language change and is easier to implement for highlighters as it doesn't involve a regex with backtracking (which is NP complete iirc?)

**Comment by krux02** [comment]
This is how string literals work in ``c++11``, where ``R"V0G0N(`` and ``)V0G0N"`` act as delimiters.
```c++
const char * vogon_poem = R"V0G0N(
             O freddled gruntbuggly thy micturations are to me
                 As plured gabbleblochits on a lurgid bee.
              Groop, I implore thee my foonting turlingdromes.   
           And hooptiously drangle me with crinkly bindlewurdles,
Or I will rend thee in the gobberwarts with my blurlecruncheon, see if I don't.
                (by Prostetnic Vogon Jeltz; see p. 56/57)
)V0G0N";
```

Not only does it allow to specify arbitrary delimiters that won't clash with the content, it would also allow  to write editor extensions that detect such string blocks for syntax highlighting. Then you can can have SQL strings, python strings, etc all with correct syntax highlighting. Currently Nim has call string literals, for example ``SQL"""select elephant from africa"""``. This already works partially, but it won't work for embedded python strings that well, as ``"""`` is a very common python token.

**Comment by Tronic** [comment]
@krux02 Theoretically it can overcome the delimiter appearing in content problem. In practice everyone just uses it as another form of """ and complains that `R"(...)"` looks uglier than the same thing in some other language. As @Araq pointed out, one should not be required to invent unique identifiers. Also, this sort of literal completely fails to address the indentation problem.

Indented-block literals make a **clear separation** between source code **formatting** (indent of the block) and string **content** (any characters within the block). This way clean source code formatting can be preserved without introducing extra whitespace into the string.

For me it is actually really hard to understand how in 2010's people still design formats with issues that were widely understood and fixed in 1990's if not decades earlier. I presume that the argument has always been that "we cannot fix this because of compatibility" and that "it would take years". As I have demonstrated in this thread, fixing it both in the Nim compiler and in popular text editors took only few hours of work, and frankly I've already spent far more than that here, arguing for it.

**Comment by Araq** [comment]
> As I have demonstrated in this thread, fixing it both in the Nim compiler and in popular text editors took only few hours of work

Well we need to check that. I'm not convinced that popular text editors can be "fixed".

**Comment by krux02** [comment]
@Tronic I might have changed my opinion about this kind of string literals. They are very valuable for emit and asm statements. They are also very useful for my very own project [here](https://github.com/krux02/opengl-sandbox/blob/master/examples/deferred_shading.nim#L71).

**Comment by Clyybber** [comment]
With the introduction of `strutils.dedent` this can now be closed:
```nim
import strutils
proc foo =
  let str = dedent """
    Hello
      World!
  """
  stdout.write str

foo()
```
will print
```
Hello
  World!
```

**Comment by AmjadHD** [comment]
So, I have to import `strutils` for this. IMO triple string literals should be dedented by default in 2.0 (like [julia](https://docs.julialang.org/en/v1/manual/strings/#Triple-Quoted-String-Literals)).

**Comment by Varriount** [comment]
@AmjadHD I would suggest writing another proposal for that. I'm even optimistic that it would be accepted, since it's unlikely to cause too much breakage.
