### ISSUE TITLE
Enable bracket syntax for `from [xyz, abc] import nil`

### ISSUE THREAD

**Issue by awr1** [nim-lang/RFCs#162]
In Nim, you can import multiple modules in concisely as:
```nim
import std / [sequtils, parsexml]
```

However, you cannot do the same using the `from` syntax, (particularly if you want fully qualified imports on multiple modules) which I feel is not consistent, e.g.
```nim
from std / [sequtils, parsexml] import nil # error!
```

If others agree with adding this, unfortunately this will require a bit of a grammar change, (although nothing too drastic in my opinion) because:

```
importStmt = 'import' optInd expr
              ((comma expr)*
              / 'except' optInd (expr ^+ comma))
fromStmt = 'from' moduleName 'import' optInd expr (comma expr)*
```

**Comment by timotheecour** [comment]
duplicate of https://github.com/nim-lang/RFCs/issues/76 (proposal 1); see also its proposal 2 (which is a compatible addition to proposal 1)
proposal 1 is actually easy to implement IIRC

**Comment by awr1** [comment]
Will close as a duplicate of #76.
