### ISSUE TITLE
Add a `withAlloc` (or similar) to newruntime, making it easier to mix allocators

### ISSUE THREAD

**Issue by alehander92** [nim-lang/RFCs#165]
## withAlloc

This is a very simple change: it is an abstraction that basically just wraps some code with the existing allocators API: i mostly want to discuss custom allocator support:

What i'd love to have was e.g. a way to be able to pass an allocator to each function that needs it, so it can be easily overloadable and changeable for different environments. (similar to zig)

People correctly argue that this leads to noise: so newruntime already has a thread-local API for setting such allocators and resetting them: if we use it , at least in sync code, it seems to get us the same effect, if new instances are designed to always use getLocalAllocator()

However I admit this might be more messy for async?

### Usage
```nim
withAlloc(dummyAllocator):
  var b = newSeq[int](10)
  b.add(2)
  echo b

# here we dont change the implementation, only the callsite
echo "# with withAlloc "
var b2 = withAlloc(dummyAllocator, newSeq[int](10))
echo "end"
echo "b2 ", b2
echo "# default"
var b3 = newSeq[int](10)
echo "end"
echo "b3 ", b3

```

## Example implementation

```nim
import core/allocators, strformat, macros

# withAlloc(myAllocator, b(2))
# withAlloc(myAllocator):
#   new(b)
macro withAlloc(allocator: Allocator, b: untyped): untyped =
  var resSym = genSym(nskVar, "res")
  result = quote:
    let oldAllocator = getLocalAllocator() # stack ?
    setLocalAllocator(`allocator`)
    when compiles(echo `b`): #`b` is Assignable:
      var `resSym` = `b`
    else:
      `b`
    setLocalAllocator(oldAllocator)
    when compiles(echo `b`): #`b` is not Assignable:
      `resSym`
  echo result.repr
```

## Pro-s

* You can write "generic-about-its-allocator" code without parameter noise and let the callsite handle it
* Mostly existing: all of the real work is done in newruntime

## Con-s

* Is it a good fit for async?
* How does it interact with type allocators? i think we should be able to have several levels: local allocators, manually annotated type allocators, non-overridable local allocators

(this is just a list of some of simple ideas/impressions after a discussion with @mratsim , Shield, @raynman22202 and others: i myself am mostly a beginner in this kind of thing : i wanted to record the argument for such style of mixing))

**Comment by Araq** [comment]
In Nim + ORC there is already enough flexibility wrt allocation and allocators.
