### ISSUE TITLE
[RFC] Rework the module system.

### ISSUE THREAD

**Issue by Krognol** [nim-lang/RFCs#166]
# Abstract

The goal is to make the module system more flexible, and less of a pain to deal with.

# Description

As of writing this working with Nim's module system is the most annoying thing about the language, and has actually put me off of working on things with it several times.

The goal for this proposal is to find a more suitable module system that won't stop Nim from feeling like Nim.

Of course, it's possible that I've fundamentally misunderstood Nim's module system and have just been using it incorrectly, however I've seen several ([1](https://www.reddit.com/r/nim/comments/c51has/circular_module_importing/), [2](https://www.reddit.com/r/nim/comments/bebb01/how_to_structure_nim_modules/) [3](https://www.reddit.com/r/nim/comments/9bratp/how_do_you_modularize_in_nim/)) discussions about how to properly use modules in Nim which makes me believe that it's flawed and confusing not just for me.

I'm gonna preface this with saying that I'm probably going to be biased towards a certain kind of implementation because of other languages I use, however I'd be satisfied with pretty much any change at this point. This proposal also relates to, and solves, #6.

Currently the module system is very limited in that one file is one module, which means you end up writing gigantic files with potentially thousands of lines of code that, while more than likely relates to each other in some way, is often irrelevant of each other.

Here's a simple example where two different types rely on each other

```nim
# types.foo

type
  Foo = object
    b*: Bar
  Bar = object
    f*: Foo
```

Now, if I wanted to separate the logic for each type I would either

  a) have to keep the types and their logic in the same file
  
  or

  b) keep the types in the same file and put their logic in separate files that import the types.

While this may work for some people, ultimately organizing your code becomes hell. Keeping everything in one file makes it cluttered and confusing to navigate. Keeping things spread across multiple files you would have to keep switching between `types.foo` and the types logic file for example if you make a change in the type declaration and the logic changes. 

Other downsides include possibly having to expose private fields as other modules wouldn't be able to see the otherwise private fields, or make getters and setters.

## So how do other languages do it?

I'm only going to use Go as an example here. Feel free to add more examples.

In Go a package (module) is just a directory, and the directory name is the name of the module. Each file in the module can "see" each other and are aware of the types/functions, etc. declared in each other.

This makes it easy to separate each type and logic from each other while still being able to make co-dependent types.

The downside here is that you may end up with a lot of files lying around, cluttering the workspace instead.

# Examples

Lets assume Nim would change the module system to be like Go's, not a lot of would really have to change.

## Before

```nim
# types.nim

type
  Foo = object
    b*: Bar
  Bar = object
    f*: Foo
```

```nim
# foo_logic.nim

import types
proc doFoo(foo: Foo) = foo.b ...
```

```nim
# bar_logic.nim

import types
proc doBar(bar: Bar) = bar.f ...
```

## After

Note that we've removed the `types.nim` module here, and assume we've started a new project with Nimble with the files being in the project root.

```nim
# project/foo.nim
type Foo = object
  b: Bar

proc doFoo(foo: Foo) = foo.b ...
```

```nim
# project/bar.nim
type Bar = object
   f: Foo

proc doBar(bar: Bar) = bar.f ...
```

```nim
# someOtherProject.nim

import project
proc doFooAndBar(f: Foo, b: Bar) = ...
```

# Implementation

There would have to be some changes to the compiler. E.g. directories as modules instead of files, and also a separate phase for declaration scanning. The type/function bodies don't need to be generated/checked straight away, instead do an initial phase for type/function declarations (error out if some type/function is not declared), and then move on to the declaration bodies.

This would also eliminate the need for forward declarations which, in turn, would solve #6, and also removes confusion about which code goes where.

# Backward incompatibility

Of course, this could potentially break a lot of code bases, a solution could be to use a compiler flag for opting in for the new module system and eventually force it as the standard, or just leave it as an optional thing.

**Comment by narimiran** [comment]
Already possible with the following:

The same as in the proposal:

```nim
# project/foo.nim
type Foo* = object
  b: Bar

proc doFoo*(foo: Foo) = foo.b ...
```

```nim
# project/bar.nim
type Bar* = object
   f: Foo

proc doBar*(bar: Bar) = bar.f ...
```

New file:
```nim
# project.nim
import project / [foo, bar]
```

Result, the same as in proposal:
```nim
# someOtherProject.nim

import project
proc doFooAndBar(f: Foo, b: Bar) = ...
```

**Comment by mratsim** [comment]
That doesn't eliminate the need for forward declarations.

Also one of the most popular complaints about Nim modules are the global namespace that dumps everything and "we don't know from where what proc/types come". This proposal makes it even worse.

**Comment by Krognol** [comment]
You could always force the qualifier e.g 
```nim
import foo

let result = foo.qux()
```

which, to be honest, should already be a thing.

**Comment by narimiran** [comment]
> You could always force the qualifier which, to be honest, should already be a thing.

...by using the existing `from foo import nil`.

**Comment by awr1** [comment]
It sounds like your issue would be solved with cyclic import, IMO. Although that is a double-edged sword in itself...

**Comment by Araq** [comment]
> While this may work for some people, ultimately organizing your code becomes hell. 

I think the problems with it are blown out of proportion and Ocaml and the whole ML family of languages including the beloved F# manage to work just fine with these restrictions. But yeah, in the end it's just another proposal for "give us cyclic imports already".

**Comment by yglukhov** [comment]
99% of complexity implementing this RFC goes to cyclic imports. Other 1% to implicit imports, and `import module_name` aliasing to `import module_name/*`. This proposal "solves" #6 because it includes it :)

**Comment by Araq** [comment]
Cyclic imports are coming. Eventually. But this RFC has considerable overlap with #6, so closing..
