### ISSUE TITLE
db_postgres' tryInsertID can raise exceptions

### ISSUE THREAD

**Issue by dom96** [nim-lang/RFCs#17]
This seems like a perfect use for the `raises` pragma. The `tryInsertID` in db_postgres calls setupQuery which can raise an `EDb` exception but its docs say that it returns `-1` on error.

We are going to need to decide what to do with this, [here](http://www.postgresql.org/docs/9.4/static/errcodes-appendix.html) is a list of postgres error codes. Some error codes such as the connection errors may need to actually be raised in the `tryInsertId` procedure whereas others should not be. Should we introduce a `SqlQueryError` and a `SqlConnectionError`?

Btw I think we need to rename `EDb` to `DbError` or something.

CC @boydgreenfield, @Araq

**Comment by Araq** [comment]
5 years passed, no action.
