### ISSUE TITLE
Atomics API stabilization

### ISSUE THREAD

**Issue by mratsim** [nim-lang/RFCs#170]
In Nim we currently have 2 atomics files:

- One in system, based on pointers, https://github.com/nim-lang/Nim/blob/v1.0.0/lib/system/atomics.nim
- One in concurrency, with Atomics at the type level, https://github.com/nim-lang/Nim/blob/v1.0.0/lib/pure/concurrency/atomics.nim

The last one is much more complete but API is tagged unstable.
I don't really have any proposition but I'd like this thread to collect feedback on what you use, what worked, what is missing.

If you are experienced with C++11 memory model and would like Nim to improve the API, suggestions are also welcome.

References
- Herb Sutter, 3 hours foundamental presentation, [Atomic<> weapons](https://channel9.msdn.com/Shows/Going+Deep/Cpp-and-Beyond-2012-Herb-Sutter-atomic-Weapons-1-of-2)
- https://en.cppreference.com/w/cpp/atomic/memory_order
- [Memory Models for C/C++ Programmers paper](https://arxiv.org/abs/1803.04432)
- [GCC Article](https://gcc.gnu.org/wiki/Atomic/GCCMM)

**Comment by Araq** [comment]
Well for a start, the API doesn't really follow our style guidelines and it ugly. The documentation is also lacking, C++'s documentation is not good enough, it needs to focus on examples otherwise everybody will get it wrong.

**Comment by awr1** [comment]
I like the `concurrency.nim` one, but not sure if I'm a huge fan of using the STL directly.

**Comment by planetis-m** [comment]
All I can say, from using std/atomics, is the atomicType template https://github.com/nim-lang/Nim/blob/devel/lib/pure/concurrency/atomics.nim#L308 always causes not found error in my client code and have to import the module.

**Comment by planetis-m** [comment]
So my question is, should =sink and =copy be disallowed for atomics? Whats the expected behavior of coping when a non trivial atomic is locked by a spinlock? https://github.com/nim-lang/Nim/blob/devel/lib/pure/concurrency/atomics.nim#L367

**Comment by Araq** [comment]
What's wrong with assignment for atomics? Isn't the point that these can be assigned, but atomically?

**Comment by planetis-m** [comment]
So in C++ you can do the following
```nim
import std/atomics
var
  a: Atomic[int]
  b: Atomic[int]

a = 1
# which implies:
a.store(moSeqCst)
```

Currently in Nim you can do, this:
```nim
a = b
```
which is wrong for the aforementioned reason.

**Comment by Araq** [comment]
Yes so we need an overloaded `=copy`.

**Comment by planetis-m** [comment]
> Yes so we need an overloaded `=copy`.

...but that means `=copy[T](dest: var Atomic[T]; src: T)` and it doesn't work.
```
Error: signature for '=copy' must be proc[T: object](x: var T; y: T)
```

**Comment by mratsim** [comment]
Relevant https://github.com/nim-lang/Nim/issues/12631

Atomics are always referred to by address so they should at least be non-copyable.
I don't see a use-case to make the `Atomic[T]` movable as well (but T alone can be move-only).

**Comment by Araq** [comment]
That means we should do `type Atomic[T] = distinct T`. 

> Also everything wrong with overloading operators for atomics is explained in this talk.

Does not convince me but then I don't mind `atomicInc` either.

**Comment by planetis-m** [comment]
> That means we should do type Atomic[T] = distinct T.

That is nice, as it would be easier to support non atomic operations, you can do it by just casting to its distinct base type. Does that mean we drop support for non Trivial types? I am fine with it, one can implement his own spin/ticket/or whatever lock.

**Comment by planetis-m** [comment]
sorry, I can't see how that would work. Afaik you can't `.borrow` the assignment operator in order to make it sequentially consistent.

```nim
from std/typetraits import distinctBase

type
  Atomic*[T: AtomType] = distinct T

proc load*[T](location: var Atomic[T]; order = AtomicSeqCst): T {.inline.} =
  atomicLoadN(addr location.distinctBase, order)

proc store*[T](location: var Atomic[T]; desired: T; order = AtomicSeqCst) {.inline.} =
  atomicStoreN(addr location.distinctBase, desired, order)

var
  a: Atomic[int]

proc main =
  a.store(1, AtomicRelease)
  int(a) = 2 # not AtomicSeqCst
  echo a.int

main()
```

**Comment by Araq** [comment]
What's wrong with this best solution of yours?

**Comment by planetis-m** [comment]
So I finished it https://github.com/planetis-m/sync/blob/master/sync/atomics2.nim and will try to dog feed it on my own projects. Is there an interest in submitting this to Nim's stdlib?

**Comment by Araq** [comment]
> Is there an interest in submitting this to Nim's stdlib?

I hope to get the "bundling" going, so yes and no...
