### ISSUE TITLE
C++ interop: cppMethod/cppVirtual/cppOverride

### ISSUE THREAD

**Issue by krux02** [nim-lang/RFCs#174]
sometimes it is necessary to interact with C++ inheritance. This RFC
should make it possible to override virtual C++ methods.

#### method

The `cppMethod` tag should set the proc into a state that tells the
compiler that the function should be called with method call syntax,
and it should affect the code generator to generate the forward
declaration into the type of the first argument.

In the following example the function prototype for `foobar` would be
generated in the type definition `MyType` when it is needed.

```nim
proc foobar(self: MyType) {.cppMethod.} = 
  echo "abc"
```

In Nim all function prototypes are generated lazily. This means unlike
a hand written C program where usually headers with the entire API are
included, Nim only generates those forward declarations that will
actually be relevant for that translation unit. This behavior can be
adopted to non virtual methods as well, as more or fewer methods won't
affect the equivalence of the types. This should make it possible to
extend types with additional methods even if method definitions are
scattered across module boundaries. It's advantage over free functions
would be that the c++ compiler won't complain about accesses to
private fields of the first argument.

#### virtual

The `cppVirtual` tag for virtual methods will imply the method tag. 
The generated procedure will be generated with `virtual` keyword from
C++. Unlike normal methods, when a type has a virtual method the
definition of the type always need to include all forward declarations
of virtual methods, not just the used methods. Otherwise the C++
compiler will generate in the different modules different incompatible
vtables. If you are lucky this would cause an instant crash. It
certainly is undefined behavior and the C++ linker wouldn't complain
about it. This means it only makes sense to restrict definitions of
virtual methods to the same module as the type itself.

#### override

Emitting C++ `override` keyword is truly optional, it is never
required. Though in C++ it does guarantee some safety against spelling
errors.  I would suggest to introduce the `cppOverride` tag for
this. It will imply the method tag and It will cause that the
generated C++ method will also have the C++ `override`
annotation. Since this RFC is about improving Nim/C++
interoperability, `cppOverride` should not enable any checks on the
nim Side of things. I suspect that often a c++ function will not even
be visible to the Nim compiler, so the Nim compiler should not try to
check for the existence of a function to be overridden, this work will
be left for the C++ compiler.

## concerns

In C++ a method declaration can implicitly become a virtual override
if the superclass has the virtual definition of it. This could cause
problems when in Nim this method is not tagged as `virtual` and it's
definition won't be generated into each module that uses that type.

**Comment by zah** [comment]
Nice, I've dreamt about this feature even since I discovered Nim!

I wouldn't try to cut corners. I think the raised concern is serious enough to require us to use the same class definition in every module. One way to solve this is to execute the sem pass for all modules before the codegen pass begins. There are many other codegen problems that can be simplified if we can assume that the codegen has "full-program" knowledge.

**Comment by kunitoki** [comment]
Yeah this is pretty much a game changer for a lot of applications.

**Comment by jmgomez** [comment]
Is there any work done in this direction by anyone?

**Comment by jmgomez** [comment]
Can someone close this? It has been a while since `virtual` was implemented and it may lead into confusion https://nim-lang.github.io/Nim/manual_experimental.html#virtual-pragma
