### ISSUE TITLE
Conversion to unsigned integers shall not produce range checks

### ISSUE THREAD

**Issue by Araq** [nim-lang/RFCs#175]
This is a followup of:

https://github.com/nim-lang/Nim/issues/12554

There are two conflicting designs at play here: 

1. Nim's distinction between ``T(x)`` and ``cast[T](x)`` implies that runtime checks for ``T(x)`` are always anticipated and desired. This is what the spec for version 1 says and no special casing for ``unsigned`` is mentioned.

2.  Unsigned numbers are heavily used in low level contexts and diverging too much from C's behaviour is confusing and dangerous. Arithmetic operations on unsigned wrap around because of this requirement.

In the past Nim followed (2) but starting with version 1 Nim followed its own spec. This RFC proposes to change the spec to reflect what was true in previous Nim versions.

Note that either (1) or (2) is fine from a design standpoint IMO but the legacy code relies on (2) (including Nim's own library) and now the compiler inserts time ticking bombs in the form of secret runtime checks that can result in exceptions being raised without any warnings. This is bad enough to revert it to the old behavior and change the spec so that it matches Nim's historical behavior.

**Comment by krux02** [comment]
@zah that specific operation that you call `truncate` already exists. It is called `cast`.

**Comment by zah** [comment]
`cast` in considered an unsafe operation. We should always try to avoid it when a safer construct is available.

**Comment by mratsim** [comment]
The fact that `cast` allows casting between types of different sizes for integers is also questionable.
This was also not allowed for a very long time in the VM and semfold I expect.

It's still not allowed for objects for example:
```Nim
type Foo64 = object
  data: uint64

type Foo8 = object
  data: uint8

let x = Foo64(data: 300'u64)
echo cast[Foo8](x) # Error: expression cannot be cast to Foo8=object
```

It probably requires another RFC but I'd rather have cast be only about reinterpreting the bit pattern of the type.

**Comment by mratsim** [comment]
A note on the title

`conversion from unsigned to unsigned integers and raw bytes shall not produce range checks`.

Signed -> unsigned conversion should still be checked for negative values.

**Comment by Araq** [comment]
> Signed -> unsigned conversion should still be checked for negative values.

Uh but in the past ``byte(-1)`` did compile. Now you are adding more special rules, I don't like it.

**Comment by mratsim** [comment]
> > Signed -> unsigned conversion should still be checked for negative values.
> 
> Uh but in the past `byte(-1)` did compile. Now you are adding more special rules, I don't like it.

It did not, it throws `Error: -1 can't be converted to byte` for semfold and a runtime error for runtime values.

**Comment by cheatfate** [comment]
@mratsim i dont think signed to unsigned conversion must be checked. it can be converted without any problems even with sign bit. So:
```nim
uint8(-1) = 0xFF
uint16(-1) = 0xFFFF
uint32(-1) = 0xFFFF_FFFF
uint64(-1) = 0xFFFF_FFFF_FFFF_FFFF
```

**Comment by zah** [comment]
@cheatfate, I can see the habits of the C programmers here and the desire to cling to the familiar. Why should we write `uint8(-1)` when we have `uint8.high`?

**Comment by cheatfate** [comment]
@zah this is just an example of possible values which must be accepted and work properly.

**Comment by krux02** [comment]
Here this is the situation we were in (tested on 0.17):
```nim

echo high(uint64)   # invalid argument for high
echo uint64(-1)     # OK

echo high(uint32)   # OK
echo uint32(-1)     # conversion from int literal(-1) to uint32 is invalid
```

Range checks sometimes. No consistent way to get the high value of all integer types. All that has been changed is, now we are not half ass anymore. You can rely on it. Also, `high` now consistently works on all types.

This is the same code in version 1.0.0
```nim
echo high(uint64)   # OK
echo uint64(-1)     # -1 can't be converted to uint64

echo high(uint32)   # OK
echo uint32(-1)     # -1 can't be converted to uint64
```

And about people who are afraid of the `cast`. It is not unsafe anymore. It is a well specified operation. Casting between differently sized integer types is a conversion without range check. It does sign extension if needed, so that a `-1'i8 (0xFF)` can become a `-1'i16 (0xFFFF)`. Casting between int and float does reinterpret the bit pattern and requires the types to be the exact same size. This behavior is specified and tested on both C backand as well as the VM.

**Comment by dryajov** [comment]
> @mratsim i dont think signed to unsigned conversion must be checked. it can be converted without any problems even with sign bit. So:
> 
> ```nim
> uint8(-1) = 0xFF
> uint16(-1) = 0xFFFF
> uint32(-1) = 0xFFFF_FFFF
> uint64(-1) = 0xFFFF_FFFF_FFFF_FFFF
> ```

Doesn't signed to unsigned and specifically the code above assume 2s complement hardware (no matter how prevalent it is this days)? Does Nim asume 2s complement hardware everywhere or is it up to the backend to do the "right thing"? Wouldn't this require this assumption to be explicit at the language spec level, i.e. don't repeat other's errors.

**Comment by dryajov** [comment]
IMO, the safer thing to do is to disallow implicit signed to unsigned conversion.

**Comment by Araq** [comment]
Nobody talks about *implicit* conversions here.

**Comment by Araq** [comment]
> Does Nim asume 2s complement hardware everywhere or is it up to the backend to do the "right thing"? Wouldn't this require this assumption to be explicit at the language spec level, i.e. don't repeat other's errors.

2s complement hardware is pretty safe to bet on and a compiler can always emulate it on alien hardward.

**Comment by dryajov** [comment]
> Nobody talks about _implicit_ conversions here.

Ok I stand corrected. But sign conversion more vulnerable than unsigned overflow, for example:

```nim
var a: string = "boom!"
var b: string = "     "

copyMem(addr b[0], addr a[0], uint(-1)) # boom!!
```

The above contrived example builds fine on 0.19.6. It basically implies that `uint` can be used in place of `int` anywhere, including `Naturals`?
