### ISSUE TITLE
Feature request: macros able to iterate over symbols

### ISSUE THREAD

**Issue by jboy** [nim-lang/RFCs#18]
**Summary:** I am requesting compile-time types & procs (to be called by macros) that enable bidirectional iteration over the symbols (from modules, macros, templates, procs, constants) that are currently defined.

This is something I've wished for, during my work on Pymod:  To be able to check, if a user wants to export a proc called `foo`, that there are no other `foo` symbols (in particular, that the current module is not called `foo.nim`) that will cause problems later.  For example, I have a crude, hacky check for module-name symbol conflicts here: https://github.com/jboy/nim-pymod/blob/83d9cc7e5aabccc3c939fa09ac75e537405d93b4/pymodpkg/private/impls.nim#L282

A much more general approach would be if you could iterate over (or perhaps filter) the available overloads for symbol `foo` at compile time, then programmatically select the one you're looking for.  Perhaps you might filter upon whether the overload is a proc, a module, or something else.  Perhaps you want to filter to match certain proc parameter types.  If there are ultimately multiple equally-good alternatives (or no good alternatives), meaning that you can't select just one, then yes, you could default to an error.

I think that being able to iterate over symbols during the compile-time interpretation of macros would significantly enhance the robustness of libraries that make use of macros.  (Could it also be used to implement some additional future-proofness in a situation such as this one: https://github.com/nim-lang/Nim/issues/3542 ?)

**Disclaimer:** I'm sure that this request must interact in subtle ways with Nim's existing `bindSym` functionality:
- http://nim-lang.org/docs/manual.html#macros-bindsym
- http://nim-lang.org/docs/macros.html#bindSym,string,BindSymRule
- http://nim-lang.org/docs/macros.html#BindSymRule

But I must apologetically admit that I barely understand `bindSym` at all...

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/9560 implements the essential of this RFC
