### ISSUE TITLE
Add SharedChannel to channels standard library

### ISSUE THREAD

**Issue by pmetras** [nim-lang/RFCs#183]
The [channels](https://nim-lang.org/docs/channels.html) documentation has the note:

> **Note**: Channels cannot be passed between threads. Use globals or pass them by `ptr`.

As channels are primary communication link between threads, this seems anachronistic not being able to share them. Using globals as recommended is generally not good programming practice. The only remaining solution is to share them between threads by `ptr`, but this could frighten new users or programmers that want to only write *safe* code...

It is easy to wrap all pointer operations into overloaded procs of a `SharedChannel`. Such addition would complete this module, and the **channels documentation note could be removed**.

```nim
## `SharedChannel`, a wrapper to `Channel` that can be shared between threads.
## Documentation removed from source. See `Channel` documentation for the corresponding procs.
type
  SharedChannel*[TMsg] = ptr Channel[TMsg]

func `$`*[TMsg](c: SharedChannel[TMsg]): string =
  result = $c[]

func repr*[TMsg](c: SharedChannel[TMsg]): string =
  result = repr(c[])

proc newSharedChannel*[TMsg]: SharedChannel[TMsg] =
  result = cast[SharedChannel[TMsg]](allocShared0(sizeof(Channel[TMsg])))

proc open*[TMsg](c: var SharedChannel[TMsg]; maxItems: int = 0) =
  open(c[], maxItems)

proc trySend*[TMsg](c: var SharedChannel[TMsg]; msg: TMsg): bool =
  result = trySend(c[], msg)

proc send*[TMsg](c: var SharedChannel[TMsg]; msg: TMsg) =
  send(c[], msg)

proc tryRecv*[TMsg](c: var SharedChannel[TMsg]): tuple[dataAvailable: bool, msg: TMsg] =
  result = tryRecv(c[])

proc peek*[TMsg](c: var SharedChannel[TMsg]): int =
  result = peek(c[])

proc recv*[TMsg](c: var SharedChannel[TMsg]): TMsg =
  result = recv(c[])

proc close*[TMsg](c: var SharedChannel[TMsg]) =
  close(c[])
  deallocShared(c)
  c = nil

proc ready*[TMsg](c: var SharedChannel[TMsg]): bool =
  result = ready(c[])
```

**Comment by Araq** [comment]
Your code is not "safe" enough, after ``close`` there can be dangling pointers. This requires a form of reference counting and only recently Nim got the right means to do that.

**Comment by pmetras** [comment]
The problem with globals in libraries is that it creates code that is not re-intrant. Overwriting bugs happen when there are multiple instances using the same globals...

Can we make it safer by adding the constraint that only the thread that opened the `SharedChannel` can close it? That way, we ensure that the other threads don't play with the channel pointer.

Mutual access from both threads to `SharedChannel` is through a reference, but only one thread can access the pointer field. For instance (*this code does not protect accessing to the thread id field*):
```nim
import os
import strutils

const
  NoThread = -1

type
  SharedChannel[T] = ref object
    thread: int
    ch: ptr Channel[T]

  TArgs = object
    max: int
    cout: SharedChannel[int]
  

proc newSharedChannel[C]: SharedChannel[C] =
  result = new SharedChannel[C]
  result.thread = NoThread
  result.ch = cast[ptr Channel[C]](allocShared0(sizeof(Channel[C])))


proc open[C](channel: var SharedChannel[C]; maxItems: int = 0) =
  assert channel.thread == NoThread, "Attempt to open an already opened SharedChannel."
  open(channel.ch[], maxItems)
  channel.thread = getThreadId()


proc send[C](channel: var SharedChannel[C]; msg: C) =
  assert channel.thread != NoThread, "SharedChannel must be opened first."
  send(channel.ch[], msg)


proc recv[C](channel: var SharedChannel[C]): C =
  assert channel.thread != NoThread, "SharedChannel must be opened first."
  result = recv(channel.ch[])


proc close[C](channel: var SharedChannel[C]) =
  assert channel.thread == getThreadId(), "The SharedChannel must be closed by the thread that opened it."
  close(channel.ch[])
  deallocShared(channel.ch)
  channel.ch = nil
  channel.thread = NoThread


proc algoZ(args: TArgs) {. thread .} =
  var
    cout = args.cout
    max = args.max
    i = 0

  while i < max:
    cout.send(i)
    echo "Sent ", i
    inc(i)
  
  # Iterator complete
  cout.send(-1)
  cout.close()
  echo "Thread completed!"


proc stream(m: int): iterator: int =
  iterator iter: int {.closure.} =
    var t: Thread[TArgs]

    # Calculate one result at a time
    var cout = newSharedChannel[int]()
    cout.open(1)
    var args: TArgs = TArgs(max: m, cout: cout)

    createThread[TArgs](t, algoZ, args)
    while true:
      let val = recv(cout)
      echo "Received ", val
      # Wait long enough to be sure that the thread algoZ
      # has enough time to send multiple values, if not blocking
      sleep(1_000)
      if val == -1:
        break
      yield val

    joinThread(t)
    cout.close()

  result = iter


let iter = stream(parseInt(paramStr(1)))
for i in iter():
  echo "i=", i
  if i == 10:
    echo "Aborting iteration in main after 10 items..."
    sleep(1_000)
    break
echo "Out of iterator in main"
```

If you run it with `./a 15`, it runs normally, but if you use `./a 5`, the child thread will try to close the channel and will raise an assertion.

**Comment by Araq** [comment]
> The problem with globals in libraries is that it creates code that is not re-intrant. Overwriting bugs happen when there are multiple instances using the same globals...

How can you create "overwrite" bugs with a channel? And how do you use threads in libraries anyway, almost every library written in C/C++ is oblivious to threads; for good reasons.

**Comment by pmetras** [comment]
> How can you create "overwrite" bugs with a channel?

No, overwriting the globals referencing the channels, for instance double opening of the same channel.

**Comment by Araq** [comment]
Yeah, never seen that happen in my lifetime.

**Comment by Araq** [comment]
There is `std / channels` now.
