### ISSUE TITLE
deprecate array with low != 0

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#184]
array with low != 0 (eg: `array[2..4, int]`) seems like a bad idea in hindsight, it causes complications and edge cases and doesn't seem provide any benefit.

## example of such complications
see https://github.com/nim-lang/Nim/pull/12993#issuecomment-576434537 /cc @Araq 
> doubt the code really was correct for e.g. array[-3..10, T].
> The rest of the stdlib uses openArray and doesn't bother with weird arrays either. We cannot accept the resulting factor of 2 in API surface and the maintainability effort it implies.

## proposal
* array with enum index is useful, not bug-inducing and is not deprecated:
```nim
type Days = enum
  monday, tuesday
var a: array[Days, string] = [monday: "lundi", tuesday: "mardi"]
echo a
echo a[monday]
```

it's not bug-inducing because it's type safe: a misuse would cause a CT error.

* array with range index starting at non-zero is not really useful, source of bugs (eg: you used `0` instead of `low`) and should be deprecated.
unlike the enum index case, the type system can't help you if you mis-used 0 for `low`

one possible way to deprecate would be to:
* not deprecate array[N: int, T]
* deprecate array[R, T] where R is an range of ordinal except enum

**Comment by andreaferretti** [comment]
Notice that 

> The rest of the stdlib uses openArray

and `openarray` is always indexed starting from 0. This allows to support arrays with custom indices **and** write procs that operate on them **and** seqs without worrying about `low`. So it seems that after all supporting arbitrary arrays is not that high effort.

**Comment by Araq** [comment]
I would do it like this: 

There is only a conversion from ``array[X, T]`` to ``openArray`` when ``X`` is some integer range starting with 0.

**Comment by Araq** [comment]
> So it seems that after all supporting arbitrary arrays is not that high effort.

Think about ``proc find[T](x: openarray[T]; elem: T): int``. What ``find`` returns is a 0 based index no matter the shape of the input array.

**Comment by Clyybber** [comment]
Maybe introducing a magic `openarrayoffset` or something like that would suffice? Then theres no need to duplicate the APIs for index returning procs, you just return `index - someOpenArrayParam.openarrayoffset`. Of course the name could be a bit shorter/better.

**Comment by Clyybber** [comment]
We could introduce an openarray variant with two generic params, where one is the index type (for seq it would just be int).
Then procs which return an index can just use that variant.

**Comment by andreaferretti** [comment]
> Think about proc find

Agreed, `find` is nasty

**Comment by pmetras** [comment]
> What find returns is a 0 based index no matter the shape of the input array.

Perhaps change the doc and say that `find` does not return and array index but returns the offset from the base index of the passed `openArray`? To get the index, you have to use `find() + low()` if `find` result is not -1. We could even have a template to convert offsets to indexes. With Nim array bound checks, this type of bug is quickly caught.

There are times when 1-based array are more natural than 0-based, and sometimes other ranges. If `low` and `high` were not available at compile time, requiring 0-based arrays could be seen as an optimization. But with `low` and `high` one can write code working with all types of arrays and benefit from the same optimizations as C 0-based arrays. Mathematics and games are domains where non-zero-based arrays are frequently used.

**Comment by metagn** [comment]
> There is only a conversion from array[X, T] to openArray when X is some integer range starting with 0.

This should be good enough, no? We have `toOpenArray` now which lets us do this explicitly

**Comment by Araq** [comment]
Rejected, see https://github.com/nim-lang/Nim/pull/21952
