### ISSUE TITLE
Deprecate asyncftpclient

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/RFCs#186]
No public project on GitHub uses asyncftpclient except forks of Nim, my project and https://github.com/nim-lang/nimbuild which hasn't been updated since 2015. More bugs pop up by the second, for example there was [this bad one](https://github.com/nim-lang/Nim/pull/13242) and another one I just found, the `store()` proc takes a string filename as an argument and doesn't close the file. If I have to PR to Nim itself to fix this and update Nim instead of a single package it doesn't really seem convenient. Right now I just have a copy of the module in my own source.

Original author of this module was @dom96, if that helps things go quicker

**Comment by dom96** [comment]
You can't move it or remove it, it's part of 1.0. Best you can do is deprecate it.

**Comment by Araq** [comment]
There is more cruft in the stdlib we need to get rid of. However, if nobody uses it, nobody has problems with its bugs either. :P
