### ISSUE TITLE
allow `when` in enum types

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#190]
when is allowed inside `type Foo = object` but not inside `type Foo = enum`; this proposal is to allow:

```nim
type Foo = enum
  foo1
  when bar:
    foo2
  else:
    foo3
  foo4
```

* eg use case: in https://github.com/nim-lang/Nim/pull/13342/commits/1720baefce57ca3afc54f1253765c3c270214768 (part of https://github.com/nim-lang/Nim/pull/13342) I had to add `nnkCustomDefSection` at the end to avoid breaking bootstrap (which isn't still super satisfactory because we're out of sync with an extra element), whereas I could've instead done, with this feature:
```
type
  NimNodeKind* = enum
    ...
    when defined(nimHasCustomDefSection):
      nnkCustomDefSection,
    ...
```

* there are obviously other use cases, eg:
```nim
type Foo = enum
  kBaz
  when defined windows:
    kFoo
  kBar
```

**Comment by Varriount** [comment]
I like this, the only possible issue is that this can affect the ordinal value of an enum

**Comment by timotheecour** [comment]
> I like this, the only possible issue is that this can affect the ordinal value of an enum

but hopefully ordinal value wouldn't be part of public interface

**Comment by Araq** [comment]
It's a "natural" feature, yet, I prefer to handle this via a macro. The syntactic and implementation effort would be quite severe.

**Comment by timotheecour** [comment]
in my use case it was for NimNodeKind which can't be handled with a macro; although this is an edge case though and wouldn't justify a language feature just because of that... still not sure to do in that case...

but generally ya a macro would give maximum flexibility and no language change; feel free to close

**Comment by Araq** [comment]
> feel free to close

Such a rare offering that I can't resist.
