### ISSUE TITLE
Rename `since` to `sinceNim` and export it in system

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/RFCs#215]
## Abstract

`since` is a [template](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/system/inclrtl.nim#L52-L68) used in the standard library and system module to control declarations and behaviour when the version supplied for its first argument is older than or equal to the Nim version (NimMajor, NimMinor, NimPatch).

This template is currently private in a file called `inclrtl.nim` inside the `system` folder, and standard library modules include this file to use the `since` template. It should be imported from a module instead of included, and since the `system` module itself uses it, it should be in system and made public for everyone to use. Because the name "since" is too generic, it should be renamed to sinceNim (I'll accept a better name), and standard library modules can do `from system import sinceNim as since` to replicate the old behaviour.

## Motivation

`system/inclrtl` normally has a different purpose, it isn't a "prelude" for standard library modules. Even if it was, `since` has uses outside the standard library, although the name `since` is generic and doesn't make clear that it checks for the Nim version. Including a module every time also most likely negatievly affects compile time.

List of modules that include inclrtl just for since:

* [dom](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/js/dom.nim#L12)
* [asyncdispatch](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/asyncdispatch.nim#L169) (seems to use it for no reason? leftovers like this are also bad)
* [asyncnet](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/asyncnet.nim#L98)
* [browsers](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/browsers.nim#L16)
* [critbits](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/collections/critbits.nim#L15)
* [deques](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/collections/deques.nim#L54)
* [hashes](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/hashes.nim#L47)
* [httpclient](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/httpclient.nim#L203)
* [math](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/math.nim#L55)
* [net](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/net.nim#L67)
* [sequtils](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/collections/sequtils.nim#L76)
* [sharedtables](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/collections/sharedtables.nim#L20) (also seems to be pointless)
* [streams](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/streams.nim#L97)
* [sugar](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/sugar.nim#L13)
* [tables](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/collections/tables.nim#L222)
* [typetraits](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/typetraits.nim#L17)
* [unittest](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/unittest.nim#L99)
* [uri](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/uri.nim#L47)
* [xmltree](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/pure/xmltree.nim#L38)
* [system/dollars](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/system/dollars.nim#L1)
* uses it for benign pragma: macros, random; uses it for rtl pragma: cstrutils, cpuinfo, os, osproc, parseopt, parseutils, pegs, ropes, strtabs, strutils, times, unicode

Another piece of motivation is that packages and libraries outside the standard library will benefit from `sinceNim`. The preferred solution for most cases is using `when declared`, but sometimes there might be pesky bugs that any other `when` check will not help with (including `compiles`). Also the standard library itself doesn't use `when declared` enough.

## Description

The implementation is as follows: move the [linked lines above from inclrtl](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/system/inclrtl.nim#L52-L68) to [below the `include "system/inclrtl"` inside the system module](https://github.com/nim-lang/Nim/blob/d844d10e8e1aea9d9995c954553b8982f3b3f031/lib/system.nim#L504) (needs to be ahead of system/comparisons), and change the name of `since` to `sinceNim`; then accordingly refactor every use of `since` in the standard library to `sinceNim`, doing the aforementioned `from system import sinceNim as since` if preferred (most likely not needed).

### Before

```nim
# httpclient.nim
include "system/inclrtl"

...

proc `$`*(data: MultipartData): string {.since: (1, 1).} =
  ...
```

### After

```nim
# httpclient.nim
# include removed

...

proc `$`*(data: MultipartData): string {.sinceNim: (1, 1).} =
  ...
```

## Backwards incompatibility

The old versions of the standard library might cause problems (in some frankensteining of modules scenario). To fix this you need a `since` annotation on `since` itself, putting it back in inclrtl when the version is under the one with the change. Or just put `{.deprecated.}` on the old since.

**Comment by Araq** [comment]
> system/inclrtl normally has a different purpose, it isn't a "prelude" for standard library modules.

Actually it is, but the rest of article remains true.

> The old versions of the standard library might cause problems (in some frankensteining of modules scenario). 

I cannot imagine this to cause problems, maybe for the backporting process though. @narimiran ?

**Comment by Araq** [comment]
But ``.since`` is for Nim's stdlib development, others shouldn't use it.

**Comment by hlaaftana** [comment]
> The preferred solution for most cases is using `when declared`, but sometimes there might be pesky bugs that any other `when` check will not help with (including `compiles`).

I'd give an example but there are too many to choose from and my point is self evident. When someone tries some code and the error they get is "undeclared identifier: foo" the first thought that comes to their head isn't going to be Nim's version it's going to be that that identifier is undeclared. 

I don't really think people keep track of what Nim version has what proc declared, their first thought isn't going to be to bother to check versions. I know this first hand, because when the `securehash` module was deprecated for `std/sha1` and I had to import sha1 while supporting old versions, I thought if there was a way to check if [modules exist](https://forum.nim-lang.org/t/3752). You also definitely need `sinceNim` for language changes. In my PR the docs for `sinceNim` says "See also: declared", if you want I can add a full disclaimer that says "`when declared` is a better solution most of the time".

**Comment by Araq** [comment]
But ``.since`` is used for *disabling* procs in the stdlib, just try it yourself, say in Nimble package A you write:

```
since (1, 2):
  # can use sugar.collect here
# else:?? # gah, we don't have an else for that...
  # need to use a workaround

```

Seems useless to me for other client code.

**Comment by hlaaftana** [comment]
I don't understand your point. The right thing to do there is `when declared(sugar.collect)`, yes. If this RFC is implemented someone might use `sinceNim (1, 2)` instead, yes. But they most likely won't, and we can make it clear in documentation if they shouldn't. Even if we don't have a public `sinceNim` template, they probably are doing the same thing right now, with `when (NimMajor, NimMinor) >= (1, 2)`.

There are other uses for it in client code, not tied to the stdlib, just tied to the Nim version in general, and I don't know how this was eliding me but having an `else` is definitely important, we can implement it with `do:` which sadly isn't very descriptive, but should still work. I understand the wording `sinceNim` and it being a template doesn't make that much sense for packages. Some kind of `when nimVersionAbove` also doesn't work since you'd have to make a new one for >, >=, <, <=, == each. We could do `const NimVersion = (NimMajor, NimMinor, NimPatch)` but NimVersion is already a string so it'd need some name like `NimVersionTuple`.

I concede, I don't know what I was thinking, the main problem here was including `inclrtl` too many times anyway. We can echo what `std/with`/`sugar` did with `std/private/underscore_calls` and have a `std/private/since` which is imported.

**Comment by Araq** [comment]
> I concede, I don't know what I was thinking, the main problem here was including inclrtl too many times anyway. We can echo what std/with/sugar did with std/private/underscore_calls and have a std/private/since which is imported.

There is no problem with including "inclrtl", it's a tiny file.

**Comment by hlaaftana** [comment]
I implemented moving since from inclrtl to std/private/since, can I open a PR for that?

**Comment by Araq** [comment]
> I'm assuming you won't reject that immediately unlike the other PR

Correct.
