### ISSUE TITLE
Object variant kind field type inference

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/RFCs#219]
This isn't a personal complaint of mine but I think it will help ease a lot more people into the language. I haven't put much thought to this myself so if you can see any obvious flaws please say so. I don't really like writing RFCs without having thought about it a lot but it's not healthy to keep it backed up.

**Problem:** In Nim github wiki common criticisms: [sum types are weird](https://github.com/nim-lang/Nim/wiki/Common-Criticisms#sum-types-are-weird). It's true that they look weird because the programming is seeing redundant information with this syntax.

```nim
type
  NodeKind = enum opValue, opAdd, opSub, opMul, opCall
  Node = ref object
     case kind: NodeKind
     of opValue: value: int
     of opAdd, opSub, opMul, opCall: kids: seq[Node]
  
  Option[T] = object
    case has: bool
    of true: val: T
    else: discard
```

`case kind: NodeKind of opValue`, `case has: bool of true` have redundant type annotations because we already know what type the `kind`/`has` fields  by looking at the `of` branches. It's like if we had to type `let x: int = 3` every time.

**Proposal:** Make the `: Type` annotation in `case field: Type` optional.

```nim
type
  NodeKind = enum opValue, opAdd, opSub, opMul, opCall
  Node = ref object
     case kind
     of opValue: value: int
     of opAdd, opSub, opMul, opCall: kids: seq[Node]
  
  Option[T] = object
    case has
    of true: val: T
    else: discard
  
  Obj[T] = object
    case foo
    of T(0): zeroField: string # foo inferred to be T
    else: discard

  Obj2 = object
    case foo
    of 1'u8, 7, 9: bar: string # foo inferred to be uint8
    of 3, 19, 10: discard
    else: discard
```

It's not that big of a deal for the compiler to infer the field's type since it's literally the next statement that has the type. This also helps reduce pure enum type name redundancy, since current Nim doesn't have a way of auto-qualifying enums based on the type of the LHS (I believe, if not then they can just annotate the variant kind field).

**Flaws & backwards compatibility:** I don't see any backwards compatiblity issues since this is opt-in. It's going to be slightly more work for macros, but not any more than the compiler has to work. Also AST is backwards compatible since the first child of `nkRecCase` is an `nkIdentDefs`, which `let`/`var`/`const` can already use with an empty type field.

A flaw is that `case ident` doesn't really imply a field definition and will look weird to people who are used to Nim (`case ident*` less so). This can also be solved by allowing `case ident: auto`.

**Comment by Clyybber** [comment]
If this is done it should be done for case statements too and not for object variants only.

**Comment by alaviss** [comment]
> because `case field: Type` is not replicable in macros.

You can replicate them in macros, see [`nnkRecCase`](https://nim-lang.org/docs/macros.html#statements-type-section).

**Comment by hlaaftana** [comment]
I meant to say you can't use them as AST in macros, like you can't do

```nim
dumpTree:
  case field: Type
  of 1: foo: Type
```

You can do `case (field: Type)`, but you can't do `field*: Type` or `foo*: Type` and so on.

**Comment by alaviss** [comment]
https://play.nim-lang.org/#ix=2klB

The parser will only accept that style of case when combined with a type declaration :)

**Comment by Araq** [comment]
I'd go further than that and also infer the full enum definition... Maybe like so:

```nim

type
  (Node, NodeKind) = ref object
     case kind
     of opValue: value: int
     of opAdd, opSub, opMul, opCall: kids: seq[Node]

```

**Comment by hlaaftana** [comment]
To go further than your going further, here is some kind of "nominal typedef stack"

```nim
type
  (Node, NodeKind, Foo, Bar, _) = ref object # first typedef, Node
    case kind: enum # second typedef, NodeKind
    of opValue: value: int
    of opAdd, opSub, opMul, opCall: kids: seq[Node]
    foo: enum a, b, c # third typedef, Foo
    tup: tuple[a, b: int] # not counted, not a nominal type
    bar: object of RootObj # fourth typedef, Bar
      name: ref object # fifth typedef, ignored (_), accessible via `typeof`
        str: string
```

Seriously though, being able to parse `nkEnumTy` and `nkObjectTy` as an expression anywhere would be a win for macros in general (if it's even possible). If they're used in the wrong context (generics, proc arguments) it would be a semantic check error, not a parser one.

**Comment by alehander92** [comment]
i think still a variant macro like https://github.com/andreaferretti/patty#constructing-variant-objects but combined with type sections like now its possible is better

**Comment by hlaaftana** [comment]
The last 2 yes. I still want the original proposal though and think it's trivial, macroless Nim is still a language

**Comment by disruptek** [comment]
> I'd go further than that and also infer the full enum definition... Maybe like so:
> 
> ```nim
> type
>   (Node, NodeKind) = ref object
>      case kind
>      of opValue: value: int
>      of opAdd, opSub, opMul, opCall: kids: seq[Node]
> ```

Why would I want this over the optional syntax first proposed?

**Comment by Araq** [comment]
> Why would I want this over the optional syntax first proposed?

Because then you don't have to type out the enum fields twice.

**Comment by disruptek** [comment]
Gah, terrible, please no!  :laughing:

**Comment by a-mr** [comment]
### Alternative proposal

It would be enough to just define `enum` fields automatically, e.g. by introducing `infer` pragma for enums:

```nim
type
  NodeKind = enum {.infer.}
  Node = ref object
     case kind: NodeKind
     of opValue: value: int
     of opAdd, opSub, opMul, opCall: kids: seq[Node]
```

For that to work also introduce a rule
- right after `{.infer.}` there should be a case object definition that does not have `else` branch in its corresponding `case`.

**Pro:**
* w.r.t. original @hlaaftana proposal — more concise/DRY
* w.r.t. @Araq proposal — no need for any new syntax like `type (Node, NodeKind) = ...`

**Comment by Clyybber** [comment]
Alternatively the original proposal could accomplish the same
```nim
type
  Node = ref object
     case kind: NodeKind
     of opValue: value: int
     of opAdd, opSub, opMul, opCall: kids: seq[Node]
  NodeKind = Node.kind
```

**Comment by Araq** [comment]
> Alternatively the original proposal could accomplish the same

That is a bit in conflict with the planned "you're allowed to reuse the discriminator" feature.

**Comment by hlaaftana** [comment]
> I'd go further than that and also infer the full enum definition

If type pragma macros are made able to output multiple types, this is easily solved like:

```nim
type Node {.kindType: NodeKind.} = ref object
   case kind: _
   of opValue: value: int
   of opAdd, opSub, opMul, opCall: kids: seq[Node]
```

Even now you can do:

```nim
inferKind:
  type Node = ref object
   case kind: _
   of opValue: value: int
   of opAdd, opSub, opMul, opCall: kids: seq[Node]
# NodeKind is defined by the macro
```

But it's obviously ugly and forces a typesection separation.

If type macro pragmas are allowed to output multiple types I think this issue can be closed.

**Comment by hlaaftana** [comment]
The following works on devel:

```nim
import macros, strutils

proc realBasename(n: NimNode): string =
  $(if n.kind in {nnkPostfix, nnkPragmaExpr}: n.basename else: n)

proc isExported(n: NimNode): bool =
  (if n.kind == nnkPragmaExpr: n[0] else: n).kind == nnkPostfix

macro genEnums(td): untyped =
  var obj = td[2]
  while obj.kind in {nnkRefTy, nnkPtrTy}: obj = obj[0]
  if obj.kind == nnkObjectTy:
    result = newTree(nnkTypeSection)
    let tn = td[0].realBasename
    let exported = td[0].isExported
    for r in obj[^1]:
      if r.kind == nnkRecCase and r[0][^2].eqIdent"_":
        let enumName = ident(tn & r[0][0].realBasename.capitalizeAscii)
        let enumNameTypedef = if exported: postfix(enumName, "*") else: enumName
        var enumMembers = newTree(nnkEnumTy, newEmptyNode())
        for b in r:
          if b.kind == nnkOfBranch:
            for mem in b[0..^2]:
              enumMembers.add(mem)
        result.add(newTree(nnkTypeDef, enumNameTypedef, newEmptyNode(), enumMembers))
        r[0][^2] = enumName
    result.add(td)
  else:
    result = td

type Node {.genEnums.} = ref object
  case kind: _
  of opValue: value: int
  of opAdd, opSub, opMul, opCall: kids: seq[Node]

proc `$`(n: Node): string =
  case n.kind
  of opValue: $n.value
  of opAdd: n.kids.join(" + ")
  of opSub: n.kids.join(" - ")
  of opMul: n.kids.join(" * ")
  of opCall: $n.kids[0] & "(" & n.kids[1..^1].join(", ") & ")"

echo opValue.type # NodeKind
echo Node(kind: opAdd, kids: @[Node(kind: opValue, value: 1), Node(kind: opValue, value: 2)]) # 1 + 2
```

You can even make it so you can replace `_` with `infer NodeKind` or something if you want. I predict people who will want this kind of stuff will tend to use macros that do a lot more so the effort it takes to write `{.macroName.}` should not be too much of a problem. Closing as the original proposal is pointless and the other comments seem not received well
