### ISSUE TITLE
Feature request: Make openarray a concept

### ISSUE THREAD

**Issue by mratsim** [nim-lang/RFCs#22]
It would be nice to have openarray as a concept that requires:
- an iterable type
- len field or proc.
- Maybe `[]` bracket?

Use case: I use the following static array like a seq to avoid heap allocation

```Nim
type
  MetadataArray* = object
    data*: array[8, int]
    len*: int
```

**Comment by Araq** [comment]
Rejected, an openArray is concrete, a concept isn't so everytime you write ``openArray`` you would get these subtle implicit generics where previously you had none. I cannot see how this can work out, if you need a concept, use a concept but ``openArray`` won't change.
