### ISSUE TITLE
RFC: `--hint:msgOrigin`: no more guessing where compiler msgs came from

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#223]
see all details, examples and motivation in https://github.com/nim-lang/Nim/pull/14317
hopefully not much to discuss here...
~~only question is default on or off; I've opted for the "safe" default off for now, and later can be on if flag turns out not too annoying as default~~

I've opted for the "safe" default off

**Comment by Araq** [comment]
Wait what? Surely this *needs* to be turned off by default, most Nim users do not debug the Nim compiler. What am I missing?

**Comment by timotheecour** [comment]
well it's off, and can stay that way.

**Comment by timotheecour** [comment]
was implemented in https://github.com/nim-lang/Nim/pull/14317
