### ISSUE TITLE
We have just introduced `--backend`, possibly there is better solution: backend autodiscovery

### ISSUE THREAD

**Issue by cooldome** [nim-lang/RFCs#227]
IMO, it is useful feature to have sempass independent of codegen and backend, such that `nim doc`, `nim check`, `nim run` just work without a need to specify backend.

We already have the following feature:
```nim
   type MyType {.importcpp.} = object
```
Even if I compile to C this module, nim switches to cpp automatically because of `importcpp` directive. 

Suggestion is to auto discover backend based on presence of `import` directives for symbols in the module. If module contains `{.importc.}` backend discovered to be C, if contains `{.importcpp.}` discovered to be cpp, upgrade from C to CPP is possible. `{.importjs.} `means it is javascript. Backend is discovered on per module basis.

If we have in one module `{.importc.}` and `{.importjs.}` we can raise a clear compile time error to user that he is doing something wrong. Currently users get weird codegen errors when they import cpp only module and compile to js. Adding `when defined(js): {.error: "not supported backend".}`  is terrible.

Unfortunately, it means javascript needs separate  {.importjs.} directive. 
In unlikely scenario when imported sym is usable from javascript and cpp simultanously, we cause use something like this: `{.import: [cpp, js], $1}`

It also means that system module is not allowed to use `when defined(js)` as backend is not yet known. js and cpp specific code should be in dedicated modules. This a shift in our current paradigm so it possibly too late, because `system` module needs refactoring and people adding `import js` or `import cpp` to their projects.

Potential future features: compile c backend and javascript frontend in one compilation command. As long as backend discovery is on per module basis, it is possible. Mixing cpp and js in one module is compile time error, but cpp and js in separate modules but in one project is ok.

**Comment by mratsim** [comment]
Seems interesting. Currently for CUDA I need to compile the whole project with nvcc and it causes issue on the flags, though `{.localPassC.}` will probably a tremendous help.
