### ISSUE TITLE
User defined default values

### ISSUE THREAD

**Issue by pmetras** [nim-lang/RFCs#233]
[User manual](https://nim-lang.org/docs/manual.html#statements-and-expressions-var-statement) defines how variables are initialized. In fact, memory used by the variables is 0-filled.

## Proposal
The special func `default(t: typedesc[T]): T` can be defined by the user to specify a different default value. When it exists, the compiler will call this proc to initialize variables of type `T`. In such case, 0-filled memory does not occur and it's replaced by `default` calls.

## Justification
* Let the user select the default value. The following program won't display error message `Warning: Cannot prove that 'f' is initialized. This will become a compile time error in the future. [ProveInit]`
```nim
type
  Val = range['A' .. 'Z']

func default(a: typedesc[Val]): Val =
  'A'

proc foo =
  var f: Val
  echo "f = '", f, "', ord = ",  ord(f)

foo()
```
* Better control over default values for ranges, enum, tuples, arrays, etc.
* No change to existing behaviour and limited change to documentation.
* Some `[ProveInit]` warnings can be corrected by users.

**Comment by dom96** [comment]
I like this idea, since AFAIK the compiler already has a concept of `default`.

**Comment by trustable-code** [comment]
Maybe related to:
- #126 Support default values for object properties
- #48 Another proposal for a standardized object construction/initialization

**Comment by snej** [comment]
Great feature, but the syntax seems overly complex to me for something whose effect is so simple. How about `proc \`=init\`(var T)`, since it’s functionally the opposite of the =destroy function?
