### ISSUE TITLE
Fast substring match / contains

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/RFCs#239]
strutils should provide a `containsAt` or `matchAt` proc to check if a string contains a substring at a given location. It's commonly used for implementing network protocols or file formats.
It should use memcmp to benefit from SSE instructions and avoid loops or nested conditionals.

It could use toOpenArray or #178

Perhaps a similar proc should also exist for MemFiles

**Comment by trustable-code** [comment]
There is [strutils.continuesWith()](https://nim-lang.org/docs/strutils.html#continuesWith%2Cstring%2Cstring%2CNatural).

**Comment by Araq** [comment]
FWIW I have SSE optimized stdlib parsers in beta state.

**Comment by juancarlospaco** [comment]
`constains` is just convenience for `find` and `find` has `start` and `end` (?). :thinking:

**Comment by FedericoCeratto** [comment]
Having searched for "match", "contains", "substring" I could not find "continuesWith". Perhaps it could have a more intuitive alias.

**Comment by FedericoCeratto** [comment]
Previous discussion of SSE: https://github.com/nim-lang/Nim/issues/3155
