### ISSUE TITLE
Support generic wildcard for ref and ptr types

### ISSUE THREAD

**Issue by tulayang** [nim-lang/RFCs#246]
## Motivation

When creating a container or collection, the specific type of a ``ref`` or a ``ptr`` element does not need to be specified.

## Description

In java, the question mark (``?``) is a wildcard to represent an unknown type. You can use a wildcard to relax the restrictions on a variable.

```java
class Foo<T> {
  T value;
}

class Bar {
  List<Foo<?>> foos = new LinkedList<Foo<?>>();
}
```

This can be very useful especially when creating a container or collection. 

## Examples

For example, define a queue for dispatching tasks:

```nim
type
  Task[T] = object
    data: T
    run: proc (task: ref Task[?])

  Queue = object
    data: seq[ref Task[?]]

proc add(queue: Queue, task: ref Task[?]) =
  queue.data.add(task)

proc exec(queue: Queue) =
  for d in queue.data:
    d.run(d)
```

```nim
type
  FooData = object
    value: int
  
  FooTask = Task[FooData]

proc runFooTask(task: ref Task[?]) = 
  echo (ref FooTask)(task).data.value

proc newFooTask(value: int): ref FooTask =
  new(result)
  result.value = value
  result.run = runFooTask

type
  BarData = object
    name: string
    value: int
  
  BarTask = Task[BarData]

proc runBarTask(task: ref Task[?]) = 
  echo (ref BarTask)(task).data.name, ":", (ref BarTask)(task).data.value

proc newBarTask(name: string, value: int): ref BarTask =
  new(result)
  result.name = name
  result.value = value
  result.run = runBarTask
```

```nim
var queue = new(Queue)

queue.add(newFooTask(1))
queue.add(newFooTask(2))
queue.add(newFooTask(3))

queue.add(newBarTask("bar1", 1))
queue.add(newBarTask("bar2", 2))
queue.add(newBarTask("bar3", 3))

queue.exec()
```

**Comment by Yardanico** [comment]
The code you showed can be easily achieved by generics, so I guess all you want is some syntax sugar to make it a little less verbose?

**Comment by Yardanico** [comment]
And for generic `ptr` we already have `pointer`

**Comment by Araq** [comment]
The "Motivation" is lacking and unfortunately I don't understand the purpose of this RFC.

For example:

```nim

type
  TaskBase = object of RootObj
  Task[T] = object
    data: T
    run: proc (task: ref TaskBase)

  Queue = object
    data: seq[ref TaskBase]

proc add(queue: Queue, task: ref TaskBase) =
  queue.data.add(task)

proc exec(queue: Queue) =
  for d in queue.data:
    d.run(d)

```

**Comment by mratsim** [comment]
```Nim
type
  Task[T] = object
    data: T
    run: proc (task: ref Task[?])

  Queue = object
    data: seq[ref Task[?]]

proc add(queue: Queue, task: ref Task[?]) =
  queue.data.add(task)

proc exec(queue: Queue) =
  for d in queue.data:
    d.run(d)
```

can be written

```
type
  Task[T, U] = object
    data: T
    run: proc (task: ref Task[U])

  Queue[U] = object
    data: seq[ref Task[U]]

proc add(queue: Queue, task: ref Task) =
  queue.data.add(task)

proc exec(queue: Queue) =
  for d in queue.data:
    d.run(d)
```

**Comment by tulayang** [comment]
@Araq 

Yeah. I know this solution. And in my code, this compromise is now adopted. I hope to achieve this goal without ``object of``. I think ``object of`` has two limitations:

- doesn't allow multiple inheritance
- adds redundant abstraction

The solution provided by @mratsim looks good, but it cannot be compiled:

```nim
type
  Task[T] = object
    data: T
    run: proc (task: ref Task[T])

  Queue[T] = object
    data: seq[ref Task[T]]

proc newQueue(): Queue =
  # Error: cannot instantiate: 'Queue[T]'; Maybe generic arguments are missing?
  new(result)

var queue = newQueue()
```

**Comment by mratsim** [comment]
The error is pretty clear though, you're missing a generic argument.

```Nim
type
  Task[T] = object
    data: T
    run: proc (task: ref Task[T])

  Queue[T] = object
    data: seq[ref Task[T]]

proc initQueue(T: typedesc): Queue[T] =
  discard

var queue = initQueue(int)
echo queue.data.len
```

**Comment by mratsim** [comment]
> Task.data is a user data, the Queue has nothing to do with it and doesn't care its specific value.

The type system cares. Nim is not Java where every single type is Boxed and derives from a Root object.
Ideally this would be possible with the introduction of VTable for concept and creating a concept called `Any`. Or use what Araq's suggested.

If it's too cumbersome you can write a template to automate that in a one-liner.

**Comment by Araq** [comment]
Sorry but this has a chance of 0% of being adopted.
