### ISSUE TITLE
[RFC] Terminal's input events

### ISSUE THREAD

**Issue by data-man** [nim-lang/RFCs#26]
```nim
type
  KeyCodes* = enum
    key1,
    key2,
     ...
    keyA,
     ...
    keyF1,
    keyF2,
     ...

  KeyModifiers* = enum
    Ctrl,
    Alt,
    Shift,
    Menu,
    Win,
    LeftCtrl,
    LeftAlt,
    LeftShift,
    LeftMenu,
    LeftWin,
    RightCtrl,
    RightAlt,
    RightShift,
    RightMenu,
    RightWin

  Key* = tuple
    code*: KeyCodes
    modifiers*: set[KeyModifiers]
    pressed*: bool
    pressCount*: int
    ch*: char

proc getKey*: Key
```

**Comment by FedericoCeratto** [comment]
"Win" should use an OS-independent name.

**Comment by kaushalmodi** [comment]
> "Win" should use an OS-independent name.

Emacs calls that key "Super"

**Comment by kaushalmodi** [comment]
By @genotrance: https://github.com/genotrance/snip/blob/master/src/snip/keymap.nim

**Comment by genotrance** [comment]
I'm planning a libtermkey wrapper since it is used by neovim. It will be merged into libtickit at some point. It can serve this requirement as an alternative to ncurses.

**Comment by Wh1teDuke** [comment]
I agree.

**Comment by Araq** [comment]
There are Nimble packages which do the terminal handling differently and that's good enough.
