### ISSUE TITLE
add `os.touchFile`, `os.touchDir`, mapping to `touch file` and `touch dir` linux commands

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#263]
## semantics
raises if touchDir is applied on a file or touchFile is applied on a dir, or if these calls fail
on windows, emulation can be used, eg: https://stackoverflow.com/questions/30011267/windows-equivalent-of-touch-i-e-the-node-js-way-to-create-an-index-html

## design choice
* the alternative would be `touchPath` that'd work with both files and dirs, but touchFile+touchDir probably makes more sense to ensure desired semantics; touchPath could be added in future if needed, which would work with either.

**Comment by dom96** [comment]
This makes sense in the context of a CLI, but for a language? Why not just use ``writeFile(path, "")``.

**Comment by Araq** [comment]
"touching" a file is (almost?) always a workaround for a broken tool that uses timestamps rather than checksums. I can't imagine use cases that are not gross hacks.

**Comment by timotheecour** [comment]
> Why not just use writeFile(path, "").

that has different semantics; touch creates the file if it doesn't exist, else updates the timestamp

> This makes sense in the context of a shell, but for a language?

nim is general purpose and users shouldn't have to resort to shelling out to run their scripts.

it's also built in python >= 3.4 standard library, see https://stackoverflow.com/questions/1158076/implement-touch-using-python

```py
from pathlib import Path
Path('path/to/file.txt').touch()
```

> Path.touch(mode=0o777, exist_ok=True)
> Create a file at this given path. If mode is given, it is combined with the process’ umask value to determine the file mode and access flags. If the file already exists, the function succeeds if exist_ok is true (and its modification time is updated to the current time), otherwise FileExistsError is raised.

> "touching" a file is (almost?) always a workaround for a broken tool that uses timestamps rather than checksums. I can't imagine use cases that are not gross hacks.

a doc comment pointing to MD5 hash can be added, but this has its use cases, just like linux's `touch` + python's `pathlib.touch` does, if anything, to port scripts, write tests etc.

**Comment by timotheecour** [comment]
note: as an alternative, I can add it to new `fusion/os` module (which is expected to grow)

**Comment by Araq** [comment]
Look, "touch" is really a metaphor for an incredibly poor mechanism which could also be named as ``updateTimestampOrCreateFile``. Known cases where I don't know which of these two unrelated functions I really need: None.

Can we close this now?

**Comment by timotheecour** [comment]
willing to drop this one for the sake of moving on
