### ISSUE TITLE
Implementing a seqtosqlarray proc for db_postgres

### ISSUE THREAD

**Issue by C-NERD** [nim-lang/RFCs#280]
### Summary
Hello guys I have been using the db_postgres module for a while and I noticed that I have to manually convert seqs to sqlarrays. This is not a problem but I think there should be a proc which does that. Now I would like to do this myself but I am not familiar with GitHub and how foss works so would someone guide me

**Comment by Araq** [comment]
Please outline the proc declaration that you have in mind. Also please outline if the other ``db_*`` modules (db_sqlite, db_mysql) would benefit from it.

**Comment by C-NERD** [comment]
> Please outline the proc declaration that you have in mind. Also please outline if the other ``db_*`` modules (db_sqlite, db_mysql) would benefit from it.

I have 2 procedure declarations in mind :
##1  seqtosqlarray:
This procedure aims at converting nim seq to sqlarrays
##2 sqlarraytoseq:
This procedure aims to covert sqlarrays back to nim seq

And no the other ``db_*`` module will not benefit, it's only for db_postgres because of postgres support for arrays

**Comment by Araq** [comment]
> And no the other db_* module will not benefit, it's only for db_postgres because of postgres support for arrays

The db_* modules are DB-agnostic though. This means you should add these helpers to a module like ``db_postgres_extensions`` and preferably this should start as a Nimble package.

**Comment by C-NERD** [comment]
Thanks for the reply i am already working on a nimble package, i think `db_extensions` will be a good name just in case anyone wants to add extended features to the other db_* modules through the package in the future.
