### ISSUE TITLE
Explicit-only converters

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/RFCs#289]
You can do the following with converters:

```nim
import json
converter toString(jnode: JsonNode): string =
  jnode.getStr

echo string(%"hello world")
```

However, you might not want it to be possible to do something like this:

```nim
proc useNodeAndString(node: JsonNode, str: string): JsonNode =
  node[str]

doAssert useNodeAndString(%"key", %*{"key": 1}).getInt == 1
```

This will error at runtime instead of at compile time. So, I propose there should be converters that only get called when you perform `TypeToConvertTo(valueToConvert)` or other similar explicit operations. The definition could be with some pragma like this:

```nim
converter toString(jnode: JsonNode): string {.explicit.} =
  jnode.getStr
```

Or we could make this the default and deprecate the default behavior being implicit converters, to make it implicit you would have to do:

```nim
converter toString(jnode: JsonNode): string {.implicit.} =
  jnode.getStr
```

I would be fine with any other proposed ways to do this.

**Comment by Clyybber** [comment]
I think we should allow overriding explicit type conversions like this:
```nim
proc string(jnode: JsonNode): string =
  jnode.getStr
```

**Comment by hlaaftana** [comment]
> I think we should allow overriding explicit type conversions like this:
> 
> ```nim
> proc string(jnode: JsonNode): string =
>   jnode.getStr
> ```

Then the *only* way to call this proc would be like `string(x)`, and you would have to tie this proc to a type, giving it special behavior, to make it work with aliased types. It would also look weird for partial generics:

```nim
type Foo[T, U] = object
  x: T
  y: U

proc Foo[T](x: T): Foo[T, int] = Foo[T, int](x: x, y: 1)
```

Converters also do support some level of generic inference believe it or not, so it wouldn't be too much worse compared to procs. This compiles:

```nim
type Foo[T] = object
  field: T

converter toFoo[T](x: T): Foo[T] = Foo[T](field: x)

echo Foo[auto](3)
```

If instead of `Foo[auto](3)` you call `Foo(3)` though it compiles but gives an error in the C code, so perhaps that was intended to work as well.

**Comment by Araq** [comment]
> So, I propose there should be converters that only get called when you perform TypeToConvertTo(valueToConvert) or other similar explicit operations. 

What kind of "conversion" is this? This is overloading a typename with an operation, this is not idiomatic Nim at all.

**Comment by hlaaftana** [comment]
I don't remember why I needed this, and now it doesn't sound great, closing unless someone can come up with a good reason

**Comment by disruptek** [comment]
Actually, you can already do this "conversion" hack.  Whether it's a good idea or should be outlawed is another question. 😆

```nim
proc int(s: string): int = 4
assert 4 == "5".int
```

**Comment by hlaaftana** [comment]
> Actually, you can already do this "conversion" hack. 

This would error if you named it a type you defined in the same module as that proc

**Comment by cooldome** [comment]
This will not be converters at all. If you don't like converters don't use them.

**Comment by timotheecour** [comment]
a better / more flexible approach that also doesn't require changing the compiler is to standardize on a generic way to write such conversions, like D's std.conv.to template; see https://github.com/nim-lang/RFCs/issues/84 (in particular latest version of this proposal, in https://github.com/nim-lang/RFCs/issues/84#issuecomment-625081674)

eg: `doAssert "13".to(int) == 13` etc
