### ISSUE TITLE
remove --nilseqs:on + associated logic to support it

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#293]
## rationale
* this would simplify a lot of code, eg:
```nim
rg -i nilseqs | wc -l
      49
```
* `nim --useVersion` only supports nim >= 1.0
* nim bootstrap currently uses 0.20 and builds fine without `--nilseqs:on`
* the only thing that stands in the way are tests for nim in action (see `testNimInAction`), but IMO this isn't a viable reason to prevent cleaning up nim and reduce complexity; those tests should be updated to use what's in current nim (since even before 1.0), not what was used at the time the book was written

(tests/cpp/tasync_cpp.nim uses --nilseqs:on but doesn't need to, it works without it as jester has been patched a while ago IIRC)

**Comment by juancarlospaco** [comment]
I do not understand why a compiler needs a book in the sources. :shrug:
