### ISSUE TITLE
Command expression notation not respected when fed a paranthesized arg (for a macro).

### ISSUE THREAD

**Issue by ozra** [nim-lang/RFCs#3]
``` nim
macro foo(a: expr): expr {.immediate.} = discard   # actual macro left out for brevity

var a = foo x + 47                 # Works as expected
var b = foo (let x = 47; x + a)    # "Call stmt space" is ignored so it doesn't compile
var c = foo((let x = 47; x + a))   # regular style notation: works as expected
```

The 'b' one should translate to the 'c' one. It seems if expression parantheses are used for the arg, the call-parser ignores spaces and greedily grabs it as an arg-list instead. 

**Fixing this can potentially break existing code that use unorthodox spacing at call sites.**

I propose this is implemented according to above expectation, but post-poned until the next major pre release, where other breaking changes may or may not be included, when it's expected to have to run nimfix. It should be possible to make a transform in nimfix to handle it, right?

**Comment by andreaferretti** [comment]
Compiles for me now

**Comment by ozra** [comment]
I'll assume it's been fixed during the ages since I issued it. Closing.
