### ISSUE TITLE
Removal of nre and improvement of re

### ISSUE THREAD

**Issue by dom96** [nim-lang/RFCs#31]
There isn't time for this in the upcoming release but we need to decide what to do about ``nre``. The consensus between me and Araq is that it should be deprecated and ``re``'s API improved to [fix issues with it](https://github.com/flaviut/nre#why)

**Comment by flaviut** [comment]
I've pulled the latest version of nre into [flaviut/nre](https://github.com/flaviut/nre). I'm not exactly sure how to use it (it's in nimble, installed, etc, but `import nre` grabs the stdlib version), but it's there.

**Comment by Araq** [comment]
V1 ships with both and both libraries are mature. Let's change nothing.

**Comment by al6x** [comment]
In my personal opinion it would be better to deprecate the `re` and use `nre` by default.

The `re` package is too low-level and is hard to use and feels too alien for people from Ruby (and probably from Python too), JS etc. languages.
