### ISSUE TITLE
Check converters at compile time if possible

### ISSUE THREAD

**Issue by al6x** [nim-lang/RFCs#326]
In many cases converters could be checked at compile time.  

It should help to **decrease runtime errors**, improve **runtime performance** (as conversion done just once at compile time), require no change in the language, and **shouldn't slow down compiler** (compiler can skip the check if the conversion is too complicated). 

It should work for all converters, but I would like to highlight the usage with the example for string enums. 

```Nim
import strutils  # for parseEnum

type
  Priority = enum
    pLow = "low", pNormal = "normal", pHigh = "high"
  
  Todo = object
    text:     string
    priority: Priority

converter toPriority(s: string): Priority = parseEnum[Priority](s)

echo Todo(text: "Buy milk", priority: "high")      # Simple, should be checked at compile time
echo Todo(text: "Buy milk", priority: "h" & "igh") # Too complicated to check, could be ignored
```

As a bonus, we would get **literal types for string** that are **fast** for free.

Fast because `string -> enum` conversions will be done at compile time, and during the runtime the enum (in example I use `string -> string` enum, but it also could be `string -> int` enum) will be used instead of the string, so all the "literal string" enum comparison operations will be in reality fast `int` comparisons.

P.S.

And it's aligned with plans for 2021 for Nim - stability and less bugs :).

**Comment by hlaaftana** [comment]
I believe you want something like this:

```nim
converter toPriority(s: string): Priority {.compileTime.} = parseEnum[Priority](s)
# should be similar to how compileTime procs work

var x: Priority
x = "high" # works
let str = "high"
x = str # does not compile

converter toPriorityRuntime(s: string): Priority = parseEnum[Priority](s)
x = str # works
```

An alternative could be this:

```nim
converter toPriority(s: static string): static Priority = static parseEnum[Priority](s)
```

but this would complicate things.

**Comment by al6x** [comment]
@hlaaftana thanks, `{.compile_time.}` is close to what I want, but it doesn't work, [try it](https://play.nim-lang.org/#ix=2NwT).

**Comment by hlaaftana** [comment]
Yes, sorry, I was merely proposing its use here.

**Comment by Araq** [comment]
So ... sometimes your **string literals** are checked at compile-time and sometimes they are not? Seems like a really bad idea, sorry. You should use the enum values directly when you can.

**Comment by al6x** [comment]
> sometimes your string literals are checked at compile-time and sometimes they are not?

If it's a simple string literal - it always checked at compile time. If it's an expression - it's up to compiler to decide to try to check it, or just ignore. From the practical point that would cover like 95% of use cases for strings as enums. 

> Seems like a really bad idea, sorry. 

Hmm, I look at it a bit differently, from the user perspective. I write a program and I want the program to be correct and bugs detected as soon as possible. 

The way it currently works - enum conversion problems would be caught late, when program is running. With this proposal some of those bugs would be detected immediately. So, from my point of view as a user - it is an improvement.

As for how exactly those checks would be implemented - with compiler, or with linter or some other code analysis tools - it's not that important.

**Comment by Araq** [comment]
Ah it's just a tooling convenience ... I suppose we can never have enough of these. Still doesn't look particularly important to do, does it?

**Comment by al6x** [comment]
> Still doesn't look particularly important

I guess it depends on the use case, probably not that important if you don't use enums heavily. In my case I use it a lot.

I'm working on a program that would check portfolio against set of rules. There are tens of different enums and tens of rules. The actual rules expressed in the language, not in english, but just as an example I write some in english.

With **string enums**:

If company is in the `resource` sector it should have `low` risk score and be in "low" risk country and be of `large` or `medium` size, should have "stable" financials, and be insured with `put` option with strike price of at least 70% and `medium` long expiration.

With **raw enums**, doesn't look that good, and you have to remember all those prefixes.

If stock is in the `sResource` sector it should have `srLow` risk score and be in "crLow" risk country and be of `ssLarge` or `ssMedium` size, should have "fsStable" financials, and be insured with `otPut` option with strike price of at least 70% and `oeMedium` long expiration.

**Comment by Araq** [comment]
> With raw enums, it doesn't look that good, and you have to remember all those prefixes.

Sure, but you don't have to use the prefixes for raw enums. Nor do you have to use raw enums, you can also use ``.pure`` enums.

**Comment by al6x** [comment]
Pure enums still have name conflict.

**Comment by Araq** [comment]
What's so annoying about:

```nim

let c = Color.red

```

?

**Comment by greenfork** [comment]
It's annoying in examples like this one:
```nim
proc processInput(w: GLFWWindow) =
  if w.getKey(Escape) == GLFWPress:
    w.setWindowShouldClose(true)
  elif w.getKey(W) == GLFWPress:
    camera.processKeyboard(cmForward, deltaTime)
  elif w.getKey(S) == GLFWPress:
    camera.processKeyboard(cmBackward, deltaTime)
  elif w.getKey(GLFWKey.A) == GLFWPress:
    camera.processKeyboard(cmLeft, deltaTime)
  elif w.getKey(D) == GLFWPress:
    camera.processKeyboard(cmRight, deltaTime)
```

note `GLFWKey.A` which has to be prefixed because A is also a gamepad button

**Comment by bluenote10** [comment]
> This feature would allow to write DSL-like nicely

To me the string based version isn't nicer. What if you want to refactor the names? Refactoring symbols is more obvious and can be assisted by IDEs. With strings you just have lots of hard-coded magic values that may or may not be convertible to enum values.

**Comment by al6x** [comment]
> To me the string based version isn't nicer. What if you want to refactor the names?

@bluenote10 I see, yes symbols would be fine too, if naming conflict would be resolved.

> What's so annoying about: `let c = Color.red` ?

@Araq clean, nice, expressive code `paint(red)` or `company.risk = low` looks much better than the `paint(Color.red)` or `company.risk = CompanyRisk.low`.

**Comment by Araq** [comment]
Feel free but I'm about to write an RFC about this as well...

**Comment by Araq** [comment]
Sorry, I didn't get to write the RFC yet. However, this one here is "rejected".
