### ISSUE TITLE
discardable for templates

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/RFCs#327]
```nim
template foo: int {.discardable.} = 3

foo()
```

Don't know if it should be supported for `untyped`. Instead of checking the return type at the declaration site it would have to instantiate the template every time its called, get its type, then check if it is discardable at that callsite. If this is possible, then it could probably be extended to macros as well.

Could be useful for something like this:

```nim
template `:=`(a, b): untyped {.discardable.} =
  let a = b
  a

foo := 1
if bar := false:
  doAssert bar
```

Just to get it out, this proposal is void if it's decided that discardable in general is not worth supporting, but if it is worth supporting then this would help the feature have more of a universal availability.

**Comment by Araq** [comment]
The idiom is ``(a = b; a)`` and works well. Better than Python's new ugly C-isms that never made much sense.

**Comment by hlaaftana** [comment]
It does work well, but I have seen people request that operator for easier migration from Python (don't know if it's because they actually used it in the code they were migrating). Implicitly discardable calls only applying to procedures would just be odd to the people that were using discardable already. That applies to templates which are just procs but as AST replacements, and also to emulators of what would be language-level syntax in another language but are trivial to implement as user code in Nim like `:=`. Another rough example could be emulating both JS class statement and [named class expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class#named_class_expressions):

```nim
class NamedFoo:
  discard

# becomes something like:
const NamedFoo = ...
NamedFoo # discarded

const Foo = class NamedFoo:
  discard

# becomes

const Foo = (const NamedFoo = ...; NamedFoo)
```
This change to discardable would only help people using discardable, it wouldn't be a very productive addition otherwise. While it would be kind of weird to think of discardable as a feature you "grow out of" before you learn how to really use Nim, I do think it is understandable to think of it as a feature that will eventually be deprecated, as Nim's identity will only grow stronger and people adopting it will be more and more accepting of something like `discard`. If it's not going to be deprecated anytime soon however this is the next obvious step IMO. I just found out that the manual actually [specifically points this case out](https://nim-lang.org/docs/manual.html#statements-and-expressions-discard-statement), implying someone using discardable is likely to encounter this.

Perhaps discardable needs a significant overhaul to make this work, in which case it might not be worth bothering, if so then a  minor improvement would be `{.discardable.}` on template giving a proper error like "discardable is not supported on templates" as it currently gives "cannot attach a custom pragma".

**Comment by Araq** [comment]
Maybe we can make discardable more useful by attaching it to an expression and not just to a proc:

```nim

({.discardable.} 3) 

``` 

This seems easy to implement and naturally allows for usage in a template:

```nim

template foo: int = ({.discardable.} 3)

foo()

```

**Comment by hlaaftana** [comment]
I don't know how I missed it, this is actually possible in current Nim:

```nim
proc discardable[T](x: T): T {.discardable, inline.} = x

template `:=`(a, b): untyped =
  let a = b
  discardable a

foo := 1
if bar := false:
  doAssert bar
```

This is good enough to close the issue, it would be perfect if it's possible to completely elide `discardable` but it's not worth the effort for such a small reward. One thing is the signature needs to be `proc discardable[T](x: lent T): lent T` for best performance I believe? but you can't `lent` ints etc

**Comment by Araq** [comment]
You should use ``proc discardable[T](x: sink T): T``. :-)
