### ISSUE TITLE
add `os.isAdmin` to tell whether we are admin (windows) or root (posix)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#329]
refs https://github.com/nim-lang/Nim/pull/16859#issuecomment-769984578

## on windows:
refs https://stackoverflow.com/a/16285248/1426932
running `execShellCmd("net session")` can tell you: if not admin you get:
```
System error 5 has occurred.

Access is denied.
```

else you might get an answer such as: `There are no entries in the list.`

## on posix:
refs: https://stackoverflow.com/a/21622456/1426932
running `getEnv("EUID") == "0"` or similar will tell you if you're root
(it's readonly, can't be set)

## use cases
* giving more informative error messages, avoiding re-inventing the wheel with solutions that aren't robust, allow user to branch on this (eg symlinks on windows can be created by admin or, in developper mode, if some flag is set)
* writing tests (refs https://github.com/nim-lang/Nim/pull/16709#issuecomment-769258310 @rominf )

## links
* https://security.stackexchange.com/questions/10194/why-do-you-have-to-be-an-admin-to-create-a-symlink-in-windows
* related but different: [Add isWindowsDeveloperModeActive · Issue #343 · nim-lang/RFCs](https://github.com/nim-lang/RFCs/issues/343)

**Comment by alaviss** [comment]
> refs: https://stackoverflow.com/a/21622456/1426932
> running `getEnv("EUID") == "0"` or similar will tell you if you're root
> (it's readonly, can't be set)

This is a shell feature, there is nothing preventing the caller from modifying this environment variable. The POSIX way is to use the `geteuid()` syscall.

> refs https://stackoverflow.com/a/16285248/1426932
> running `execShellCmd("net session")` can tell you: if not admin you get:
> 
> ```
> System error 5 has occurred.
> 
> Access is denied.
> ```
> 
> else you might get an answer such as: `There are no entries in the list.`

This is a terrible way to do it, if a malicious actor modify the PATH or Microsoft changes the output of `net`, it will fail. Here's how to do it in Win32: https://docs.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-checktokenmembership?redirectedfrom=MSDN

**Comment by juancarlospaco** [comment]
If the computer is already compromised nothing is totally secure but yeah... :shrug:

**Comment by rominf** [comment]
See https://github.com/nim-lang/Nim/pull/17012 for the implementation.
