### ISSUE TITLE
Rename xmltree.escape to escapeXml

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/RFCs#333]
It usually conflicts with strutils.escape. Comparably json has escapeJson.

**Comment by Araq** [comment]
So what. ``import strutils except escape`` works well. There are lots of other solutions like typing ``xmltree.escape``.

**Comment by planetis-m** [comment]
After some testing, I think that escapeJson is not a good name to begin with. I mean for my [use-case](https://github.com/nim-lang-cn/html2karax/blob/094dac53c17003bc3957a8ece23d5fc0640d5313/public/html2karax.nim#L100) it turned out to be a better match than even `strutils.escape`

**Comment by Araq** [comment]
So ... close?
