### ISSUE TITLE
[RFC] `get` for container types returning an Option[T]

### ISSUE THREAD

**Issue by dom96** [nim-lang/RFCs#35]
If I'm using the ``options`` module in my program it sucks that not all modules use it. It would be nice to implement it for the containers in the stdlib, for example ``proc get*[K, V](t: Table[K, V], key: K): Option[V]``.

We should standardise on the name too, it should be consistent across the stdlib.

**Comment by arnetheduck** [comment]
Here's an example of what this syntax can look like with nim today:

https://github.com/status-im/nim-eth/blob/4492bae6a2eb71a62c794f09ba8b4cf7a2be9090/eth/keys/secp.nim#L173

```
proc fromHex*(T: type SkSecretKey, data: string): SkResult[T] =
  T.fromRaw(? seq[byte].fromHex(data))
```

this does early return in case of error in `fromHex` and passes it up the stack - making the potential for failure visible at the call site but in a minimally intrusive way.
