### ISSUE TITLE
Allow to return block

### ISSUE THREAD

**Issue by al6x** [nim-lang/RFCs#356]
Allow to return block of code, because sometimes it increase readability. 

It's expected to be used mostly in **early returns** `if ... return`.

```Nim
func somefn: string =
  return
    "hi"
```

or possibly with `:`

```Nim
func somefn: string =
  return:
    "hi"
```

It's possible to do with parentheses, but with block it feels better and more Nim-like.

```Nim
func somefn: string =
  return (
    "hi"
  )
```

Also it's possible to do with `=` so it feels that it should be also possible with `return`

```Nim
func somefn: string =
  let some = 
    "hi"
  return some
```

Example:

```Nim
proc process(server: Server, req: Request): Response =
  ...
  if route.is_none: 
    return
      case format_type
      of web_e:   respond(404, server.render_not_found_page("Route not found"))
      of data_e:  respond((is_error: true, message: "Route not found").format_as(req.format))
      of other_e: respond(404, "Route not found")

  ...
  respond("ok")
```

**Comment by Yardanico** [comment]
Already easily possible:
```nim
func somefn: string =
  return block:
    "hi"
```

**Comment by Yardanico** [comment]
Or, if you prefer having `return` or need it for control-flow:
```nim
func somefn: string =
  return (block:
    "hi"
  )
```

**Comment by al6x** [comment]
Yes, that's what I'm currently use. But the `return:` looks much better.

**Comment by Yardanico** [comment]
And of course no one stops you from making a simple template:
```nim
template retBlock(body: untyped): untyped = 
  return(block:
    body
  )

func somefn: string =
  retBlock:
    "hi"

echo somefn()
```

**Comment by hlaaftana** [comment]
This syntax should be valid as of https://github.com/nim-lang/Nim/commit/2859069dbe1c943494cb6be299b200afa748cf52:

```nim
func somefn: string =
  return block:
    "hi"
```

**Comment by Araq** [comment]
Rejected.
