### ISSUE TITLE
introduce `'i` literal suffix, require a suffix for int's outside of in32 range and for 0b,0o,0x integers

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#364]
## proposal P1
introduce `'i` literal suffix to indicate an int, eg: `123'i` (analog to `123'u`)

## proposal P2
require a literal suffix for int's outside of int32 range(>int32.high or <int32.low), eg:
```nim
when true:
  let a1 = -2147483648 # ok
  let a2 = -2147483649 # error: use -2147483649'i or -2147483649'i64
  let a3 = 2147483647 # ok
  let a4 = 2147483648 # error: use 2147483648'i or 2147483648'i64 or 2147483648'u or 2147483648'u64 or 2147483648'u32
```
note that currently, these are all legal, with types: int, int64, int, int64.

This will force users to choose whether to treat a large int64 integer as int (not portable to 32bit machines) or int64 (portable to 32 bit machines)

## proposal P3
require a literal suffix for integers with 0b,0o,0x prefix
eg:
```nim
let a = 0xFF # error: use 0xFF'i or  0xFF'u or  0xFF'u8 or ... etc ...
```

## rationale
the current rules are error prone and confusing eg:
```nim
when true:
  template fn(a) =
    echo astToStr(a), ": ", type(a), " = ", a
  fn 0x000000000FF00000
  fn 0x1FFFFFFFFFF00000
  fn 0xFFFFFFFFFFF00000
```
prints:

0x0FF00000: int = 267386880
0x1FFFFFFFFFF00000'i64: int64 = 2305843009212645376
0xFFF00000: int = -1048576

* as you increase the hex representation using same number of hex digits, you go from int to int64 to int. While this can be explained, it's non intuitive and needlessly confusing.
* furthermore, most people would expect `0xFF` to be unsigned, but changing this would be a bad breaking change (changing semantics), so instead we can just deprecate it and use instead a literal suffix, which clarifies this, `0xFF'i` or `0xFF'u` or `0xFF'u8` etc

## note
the fact that astToStr (or repr) is broken is a separate issue eg
```nim
when true:
  template fn(a) =
    echo astToStr(a), ": ", type(a), " = ", a
  fn 0xfffffffff'u
  fn 0xfffffffffff'u
```
prints
0xFFFFFFFF'u: uint = 68719476735
0xFFFFFFFF'u: uint = 17592186044415

## migration path
* introduce the `'i` suffix literal and backport it to 1.0 so that code can remain forward and backward compatible
* deprecate violations of P2 and P3, with a warning message indicating how to replace the code

**Comment by Araq** [comment]
I fail to see the advantage, it's only "confusing" if you don't know the rules and more rules or just changing the rules is not worth it. At some point we have to admit that users who read the manual have some advantage over users who go by guesswork. The real problem here is that hexadecimal numbers are inherently ambiguous as they lack a sign.

**Comment by timotheecour** [comment]
an alternative to `proposal P3` is your very own proposal from here: https://github.com/nim-lang/Nim/pull/14530#issuecomment-636819169

> Somewhat related: I wonder if "length-specific hex literals" are intuitive:

I think this is indeed most intuitive way to interpret 0x,0o,0b numbers when there is no suffix, as the bit pattern is aligned to the chars in the hex/oct/binary representation:
```nim
0xf # ERROR
0xff # ok, uint8 (instead of int)
0xffi8 # ok, int8
...
0x00_00_ff_00 # uint32 (instead of int)
0x00_00_ff_00_00_00_ff_00 # uint64 (instead of int64 <= NOTICE the pre-existing inconsistency here)

# explicit suffix is ok:
0xffi32 # ok, int32 instead of uint8)
0xffu32 # ok, uint32 (instead of uint8)
0xfu32 # still ERROR
```

This is what C# does too: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types but different languages do different things (eg in C++, 0xFFFFFFFFFFFFFFFF is unsigned long whereas 0xFFFFFFFFFFFFFFF is long)

## backward compatibility
This is the same story as `\x HHH became illegal` which we've already deprecated.

We can add a pushable pragma to specify how suffix-less hex/oct/binary literals are interpreted:

```nim
# foo.nim:
{.unsignedLiterals: on.}
assert not compiles(0xf)
assert 0xff is uint8
assert 0xffff is uint16
assert 0xffffffff is uint32
assert 0xffffffffffffffff is uint64
assert 0xffffffffffffffff'i64 is int64 # always possible
```

for literals that appear in a context without `{.unsignedLiterals: on|off.}` defined, we start issuing a warning (but keep pre-existing behavior for backward compatibility):
```nim
# bar.nim:
let a = 0xf # warning: deprecated, must use 2,4,8,16,32 chars
# the following literals also would generate a warning: use `{.unsignedLiterals: on|off.}` to disambiguate
assert 0xff is int 
assert 0xffff is uint16

echo type 0x000000000FF00000 # int
echo type 0x1FFFFFFFFFF00000 # int64
echo type 0xFFFFFFFFFFF00000 # int
```

then after a few releases, `{.unsignedLiterals: on.}` becomes the default.

**Comment by Araq** [comment]
No.
