### ISSUE TITLE
transfer Varriount/NimLime to nim-lang/NimLime

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#365]
## proposal
transfer https://github.com/Varriount/NimLime to https://github.com/nim-lang/NimLime
see https://github.com/Varriount/NimLime/issues/154 for rationale and prior discussion:
> I'm in favor of this since I have no time to continue maintaining it. We should be looking for new maintainers if varriount is also unable to maintain

I've already created a fork https://github.com/nim-lang/NimLime tentatively, if there's no objection then we can move issues and PRs (only 1 pending, https://github.com/Varriount/NimLime/pull/153, which supports the new literals) to the new location (see how in https://hub.packtpub.com/github-now-allows-issue-transfer-between-repositories-a-public-beta-version/), but IIRC it needs to be done by someone with admin access to both repos.

**Comment by Varriount** [comment]
Just want to chime in: I'm 100% ok with this.

**Comment by timotheecour** [comment]
> Someone will have to work to change where GitHub's Nim highlighting definitions are sourced from (as far as I know, they're still sourced from the NimLime syntax definition files).

see https://github.com/github/linguist/pull/5306 which was needed to support the new number literals, and changed from https://github.com/Varriount/NimLime to https://github.com/timotheecour/NimLime as a temporary measure, but once Varriount/NimLime is transfered to nim-lang/NimLime, we'll need to update again the submodule as followup to https://github.com/github/linguist/pull/5306

The next action item right now is for an owner of https://github.com/Varriount/NimLime to transfer issues and PRs from  Varriount/NimLime to nim-lang/NimLime, using https://hub.packtpub.com/github-now-allows-issue-transfer-between-repositories-a-public-beta-version/ or equivalent so that issue metadata are preserved

**Comment by Araq** [comment]
So ... do I need to do anything to make this happen?

**Comment by timotheecour** [comment]
@Varriount can you please make @Araq an owner of your repo
and then @araq can transfer the repo using:

https://github.com/Varriount/NimLime/settings > Danger Zone > Transfer ownership
> Transfer this repository to another user or to an organization where you have the ability to create repositories.

![image](https://user-images.githubusercontent.com/2194784/114806487-b472ba80-9d59-11eb-9214-930c85ec70be.png)

**Comment by Varriount** [comment]
> @Varriount can you please make @Araq an owner of your repo
> and then @Araq can transfer the repo using:
> 
> https://github.com/Varriount/NimLime/settings > Danger Zone > Transfer ownership
> 
> > Transfer this repository to another user or to an organization where you have the ability to create repositories.
> 
> ![image](https://user-images.githubusercontent.com/2194784/114806487-b472ba80-9d59-11eb-9214-930c85ec70be.png)
> 
> (i'm not sure whether the fork i made in https://github.com/nim-lang/NimLime needs to be deleted first)

Ah, sorry. It hadn't occurred to me that I would need to do anything. Should be done in a moment.

I'll  need to work with Package Control to move the link in that repo as well.

**Comment by timotheecour** [comment]
@Varriount 
> Edit: Someone will need to delete or rename the current fork Nim-Lang has.

done (i had created the fork recently and checked that nothing was added to it before removing the fork); what else should be done?

**Comment by timotheecour** [comment]
ping @Varriount

**Comment by AmjadHD** [comment]
@timotheecour 
https://packagecontrol.io/docs
in short this url should be updated (through a PR)
https://github.com/wbond/package_control_channel/blob/836c004d544830ab89c50c09d61e3dc7d3f2a7b7/repository/n.json#L629

**Comment by timotheecour** [comment]
looks like the repo, issues, PRs were successfully migrated, thanks!
next steps:
step 1: merge https://github.com/nim-lang/NimLime/pull/153
step 2: do a followup PR after https://github.com/github/linguist/pull/5306 to point to new fork (yet again)
step 3: send PR against https://github.com/wbond/package_control_channel/blob/836c004d544830ab89c50c09d61e3dc7d3f2a7b7/repository/n.json#L629 ; @AmjadHD do you want to do 2 and 3 after 1 is done?
