### ISSUE TITLE
Move choosenim under Nim org

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/RFCs#374]
This idea is simple, move `choosenim` thats a very relevant tool to install the language and manage Nim versions 
under the Nim organization on Github, to keep it under the Nim umbrella, and improve its visibility as a core tool.

**Comment by dom96** [comment]
Personally I would prefer to keep it where it is for now.

**Comment by shirleyquirk** [comment]
Nim is really heavily dependent upon it, for example if one wants `nim doc` to work. https://github.com/nim-lang/Nim/issues/14424 https://forum.nim-lang.org/t/7702

While I'd prefer that Nim were better supported by os-specific packages, and maybe that's a better way to support Nim in the wild, choosenim is just so darn useful, i can't imagine Nim without its `rustup`.

A broad ecosystem is as beneficial as a tightknit toolchain, and nothing prevents anyone from contributing on /dom96/choosenim vs /nim-lang/choosenim, so this isn't an attempt to change @dom96's mind, more of a love letter to the tool.

**Comment by dom96** [comment]
The way I see it is that this would be largely symbolic. I would prefer to see real action and that starts with Nimble: it's already in the nim-lang org but doesn't see much maintenance from the core Nim team. Let's change that first before doing anything with choosenim.

**Comment by juancarlospaco** [comment]
No correlation.
