### ISSUE TITLE
Memoization stdlib

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/RFCs#389]
Memoization for functions should be in stdlib.

Basic Memoization is relevant in a function oriented lang like Nim.

Does not have to be the fastest in the world,
an average memoization is still better than no memoization,
can start with a Table-based implementation or similar, can be a `macro` too.

Should take few lines (~500 lines at most), including a `runnableExample`.

Memoization should work for JavaScript targets too.

Can provide good performance improvements for very few lines.

# Why not implement your own ?

Yes, users can implement a custom one, but then each lib author will do their own,
then in a project with multiple libs the implementations will not be compatible,
that kinda defeats the whole purpose of memoization, 9 caches instead of 1.

# How is it done in other langs ?

- https://devdocs.io/python~3.9/library/functools#functools.lru_cache

**Comment by Araq** [comment]
There is https://github.com/andreaferretti/memo

> Yes, users can implement a custom one, but then each lib author will do their own

You can also use a Nimble package...

> that kinda defeats the whole purpose of memoization, 9 caches instead of 1

The cache is usually per function so this makes no sense you would get 9 different caches for 9 different functions, totally acceptable.
