### ISSUE TITLE
Nim is unsafe

### ISSUE THREAD

**Issue by dom96** [nim-lang/RFCs#4]
...or at least that's what I am told by Reddit/HN.

It seems that this is Nim's reputation now, every single time a discussion about Nim gets off the ground somebody comes along and says something like "Nim would be awesome _but_ it has the same unsafe and undefined behaviour as C". Recent example [here](https://www.reddit.com/r/programming/comments/3sa6lf/d_has_no_vision_go_is_out_of_its_depth_rust/cwvgh4k). Somebody even asked a question on Quora about this: https://www.quora.com/Is-Nim-really-that-unsafe.

The root of this criticism is [here](https://news.ycombinator.com/item?id=9050999).

I think it's about time we do something about this. Either simply decide that Nim doesn't try to be safe, does try to be safe but provides features which allow it to be unsafe, does try to be safe but a bug causes it to be unsafe, or a combination of those statements. So which is it?

Is it for example fine that

``` nim
echo("Counting to ten: ")
for i in countup(1, 10):
  var k: ref int = nil
  var l = k[]
  echo($l)
```

Will not crash in release mode?

Possibly related: #2809

**Comment by Araq** [comment]
We now have ``-d:release`` vs ``-d:danger``, so closing. We still want ``-fsanitize-trap=null`` but I couldn't get it to work but this can be its own RFC/issue.
