### ISSUE TITLE
Simplify Nim's effect system

### ISSUE THREAD

**Issue by Araq** [nim-lang/RFCs#404]
IMHO Nim's effect system didn't age well and has a remarkably bad costs vs benefits tradeoff: If you use it, the annotation burden becomes quite high but at the same time it doesn't catch too many bugs. Worse, the Nim compiler has some effect inference bugs and fixing these bugs will make the compiler "pickier" so it will break code out there, eventually, as eventually the newly introduced warnings need to become compile-time errors. That would be good if this additional pickiness detected problems in real world code bases, but in my experience it doesn't: While it occasionally does detect problems, in the vast majority of the cases all it detects are annotation inconsistencies and it's a big productivity loss.

See also:

  https://github.com/nim-lang/Nim/issues/18376
  
  https://github.com/nim-lang/Nim/issues/13905
  
  https://github.com/nim-lang/Nim/issues/17369
 
My proposal consists of a couple of simple steps that certainly need to be refined. I hope for a fruitful, productive discussion.

1. Make the compiler ignore these effects: `tags`, "lock level", `gcsafe`. Tags and lock levels can be handled by an external linter tool instead, if we decide that these are worth keeping.
2. To compensate for the lack of a `gcsafe` effect require that every access to a global variable is done in a `{.global.}:` pragma section. These sections would usually be hidden inside a `withLock` template.
3. Distinguish between `raises` and `noraises` and forget about the exception hierarchy. Rationale: The control flow implications of exceptions are what "exception safe code" actually cares about, the differences between OSError, IOError and ValueError do not have to be tracked via the type system and can bite code evolution and abstraction. `raises` would continue to be the default and `noraises` is not inferred and must be explicit.

# Side Effects

How to deal with side effects remains unclear. One idea is that funcs can only call other funcs but procs can call anything. There would be no fragile `.noSideEffect` inference. However, this doesn't cover converters, iterators or methods. We can also of course keep the existing system. 

# Effect polymorphism
 
As we have fewer effects to begin with, effect polymorphism would not be required: 
- The comparator callback for `sort` would simply be enforced to be `noraise`.
- The callbacks for `execProcesses` would simply allow for `raise` and `execProcesses` would be `raise`.
- Likewise `map` cannot really deal with exceptions and enforces `noraise`. There could be a `toEither` operation that can be used inside map's lambda.

Now, before you downvote this RFC into oblivion, please consider that by simplifying Nim in its effect system dimension, we would decrease our overall complexity budget and we could spend the complexity elsewhere, for example, by refining the existing notions of "graph partitions" via separation logic or by incorporating DrNim's "requires" and "ensures" contracts.

**Comment by arkanoid87** [comment]
From my point of view the noSideEffect and generally the effect tracking system is the most attractive feature of the language, so my opinion is biased toward this.

While not being perfect, effect tracking in Nim is something I can't do with Rust and Go and at the same time is what pushes me towards functional programming. Imho Nim is the best imperative language that successfully enforces no side effect at compile time enabling a design based on isolating pure code from IO, just like I do in functional programming.
While I think is ok to move part of the task to an external linter, I think that the potential benefit of this feature is huge and really deserves love.

I use tags to "colorize" my procs, so I can map which effects I have on the edge of the design (pure core, effects on edge).
I tend to {.noSideEffect.} and {.raises: [].} all the core logic and use Options/Either in core logic instead (not yet perfect at this, often I still have exceptions bubbling up to the edge).

About your proposal:
- will noSideEffect still imply gcsafe?
- will noraises still effectively error out if any func down the stack raises anything?

you may realize I'm more concerned about the black/white extremes of the matter, as I use Nim to reduce problem surface and enabling better handling of the complexity by enforcing purity, just how it's done in functional programming.

**Comment by Araq** [comment]
> will noSideEffect still imply gcsafe?

I don't know. :-)

> will noraises still effectively error out if any func down the stack raises anything?

Yes.

**Comment by timotheecour** [comment]
> To compensate for the lack of a gcsafe effect require that every access to a global variable is done in a {.global.}: pragma section. These sections would usually be hidden inside a withLock template.

but then what's the point of `{.global.}:` since you'd easily circumvent it via an auxiliary proc:

```nim
when true:
  var s = @[10]
  proc aux*() =
    {.global.}:
      s.add 1
  proc main2*() =
    aux() # I'm hiding the fact that I'm accessing gc global via an intermediate proc
```

**Comment by Araq** [comment]
> but then what's the point of {.global.}: since you'd easily circumvent it via an auxiliary proc

It offers a mild level of protection. In practice today you can also easily use `.cast(noSideEffect)` already. And for the same good reasons.

**Comment by timotheecour** [comment]
> or handle the exceptions via try except.

that's not usually what you want; I want to propagate the exception up the call stack, not resolve it in cmp which is arbitrary:
```nim
proc cmp2(a, b: string): int =
  try:
    result = cmp(a.parseInt, b.parseInt) # can raise ValueError
  except ValueError:
    result = 1 # should that be -1? 0? 1? it's arbitrary!
```

**Comment by arkanoid87** [comment]
In my opinion escape hatches are necessity, but I wish there were at least a warning when used. This again to raise awareness on the lack of purity or to track down and isolate effects.

**Comment by timotheecour** [comment]
See https://github.com/nim-lang/RFCs/issues/403#issuecomment-890162087 which IMO is a completely sound approach instead; the effects are explicit and type inference resolves it:

```nim
proc sorted*(a: seq[T], cmp: proc(a, b: T): int): seq[T] = ...
  # infered as: {.raises: [cmp].} since cmp is called

proc main2(): auto = # infered as {.raises: [ValueError].} because of raises: [cmp]
  proc cmp2(a, b: string): int = cmp(a.parseInt, b.parseInt) # can raise ValueError
  sorted(@["12", "3", "01"], cmp2)
```

**Comment by Araq** [comment]
> {.cast(raises: []).}: is arguably worst here, it just mascarades that an exception might throw.

I consider this a minor issue as the problem can easily be remedied: 

```nim
  proc cmp2(a, b: string): int = 
    {.cast(raises: []).}: 
      result = cmp(a.parseInt, b.parseInt)

{.cast(raises: [ValueError].}:
  sort a, cmp2
```

"human compiler at work" here, yes, but I doubt it comes up all that often. Other solutions are also possible.

**Comment by bluenote10** [comment]
What is the implication of this on write tracking? I vaguely remember the way to solve the "immutable ref object" issue was to use the effect system?

**Comment by Araq** [comment]
> What is the implication of this on write tracking? I vaguely remember the way to solve the "immutable ref object" issue was to use the effect system?

Nothing has to change, the write tracking would still be attached to `.noSideEffect` / `func`.

**Comment by planetis-m** [comment]
I think the correct thing to do for this use case is to have a default parameter. At least that is what json, tables already does.

**Comment by juancarlospaco** [comment]
Simplify it.

**Comment by n0bra1n3r** [comment]
Just wanted to say that I've been using the effect system successfully for my game engine's ECS. I use it in conjunction with my automatic event tracking system to issue compile-time errors if a component mutation is detected in certain callbacks. Here is an example of my usage:

```nim
# a component type defined by the user
type Object = object
  data: int

type MutateEffect = object
type QueryEffect = object
  
proc doMutate(obj: var Object) =
  obj.data = 2
  
proc noMutate(obj: Object) =
  discard

# an internal proxy type for intercepting component usage
type Proxy = object
  value: Object

converter toObject*(self: Proxy): lent Object {.tags:[QueryEffect].} =
  self.value

converter toVarObject*(self: var Proxy): var Object {.tags:[MutateEffect].} =
  self.value
  # ...
  # propagate mutation event to listeners

# a known callback proc declared in a system by the user
proc queryOnly() {.tags:[QueryEffect].} =
  var proxy = Proxy(value: Object(data: 1)) # wrapped entity component fetched from an ECS API
  #doMutate(proxy) # Error: can have an unlisted effect: MutateEffect
  noMutate(proxy) # OK
```
I find it elegant to use, but I can figure out another way to do this if the effect system is too hard to maintain.

**Comment by Araq** [comment]
> I can figure out another way to do this if the effect system is too hard to maintain, but IMO would really love to keep it.

Thank you for your valuable feedback.

**Comment by Araq** [comment]
Primary reason for rejection: Effect polymorphism a la `.raises: [], effectsOf: callback` is desired by pretty much everybody and introduces almost all of the involved complexity.

**Comment by kobi2187** [comment]
I see great potential in the safety of Nim: raises should be enough in my opinion, enhancing with require/ensure/invariant contracts or z3 (constraints programming) fuzzing, suggesting unit tests based on code could be amazing. Microsoft has a similar tool in visual studio professional, and IIRC Eiffel language has that in their studio too.
Why is this important? 1. as a system language, low level details and testing with raw data is not so easy. 2. most time in coding goes for debugging an issue. minimize that time, and it's a big win for productivity. 3. quality of code, less bugs, produce bug less code. it's a dream for programmers, and to have a solution with such a nice language... can be a virtue.
