### ISSUE TITLE
Allow to indent `of/else/elif/except/finally` for block commands

### ISSUE THREAD

**Issue by haxscramper** [nim-lang/RFCs#420]
Proposal is pretty simple - allow additional level of indentation for command calls:

```nim
  match arg:
    of test1: discard
    of test2: discard
    elif 12: discard
    except: discard
    else: discard
```

This topic came up several times in discussion of `caseStmtMacros`. Main reason for this change - there should be only one `case` in the language, and implicitly overloading it with multiple different semantics is not the best idea

- can't google it ("nim case `<macro-related error>`" would probably confuse every possible syntax at once),
- have to keep in mind all the imports,
- not clear what is going on in the code based on syntax alone (which overload would implicitly trigger in this case?),
- the name is not descriptive, behavior is implicit, it relies on experimental feature that has to be explicitly turned for per-file or global (more language dialects) basis,
- it clashes with generics since it depends on the expression type (I believe this is the reason for https://github.com/nim-lang/fusion/pull/33#issuecomment-716140197).

Instead, being able to write a custom macro that looks like case is much easier, but right now `case` allows for indented `of`, but command block doesn't. This is probably the only limitation, it is pretty minor, but still annoying because of random inconsistencies. 

Related

- https://github.com/nim-lang/RFCs/issues/332
- https://github.com/nim-lang/Nim/pull/17047#issuecomment-884711693
- https://github.com/nim-lang/Nim/pull/18798 CI is green and fix itself is ~7 lines, so it is a yes/no decision in the RFC, implementation is trivial.

**Comment by Araq** [comment]
The way to write the case statement is:

```nim
case variable
of value1, value2: ...
```

No additional indentation and no colon after `variable`. The alternative was allowed because some users demanded it but it never made sense as no "code block" follows after the (optional) colon.

Likewise we only need to support

```nim
  match arg
  of test1: discard
  of test2: discard
  elif 12: discard
  except: discard
  else: discard
```

IMO.

But I still like the overloaded `case` better.

**Comment by haxscramper** [comment]
```nim
match arg:
  myof ...

match arg:
of ...

case arg:
of ..

case arg:
  of ...
```

Are allowed, but 

```nim
match arg:
  of ...
```

Is not allowed. If we disregard stylistic preferences about number of spaces before 'of', optionally of the colon, we still have this inconsistency where parsing of the 'of' branches differs between case statement and user commands. Both allow to use branches, but one supports indent, and other does not.

**Comment by haxscramper** [comment]
> But I still like the overloaded case better.

What about the reasoning for the `customMacro` that I provided? This RFC is directly tied to it, so I think it can be addressed as well.

**Comment by disruptek** [comment]
How about, instead, deprecating `case expr:` syntax; it promotes a mental model that doesn't match reality and I cannot see how this is advantageous to someone learning the language.

**Comment by haxscramper** [comment]
Okay, got it, stylistic preferences etc. Don't think there is any reason to keep this RFC open then, probably won't be accepted anyway.

**Comment by haxscramper** [comment]
Why reopen?

**Comment by Araq** [comment]
Well it's not a bad idea in itself. I merely happen to dislike it but not strongly.

**Comment by haxscramper** [comment]
Okay, got it. I reopened PR then, it is filled treen and fix itself is ~7 lines, so it is most yes/no decision in the RFC about whether we want this in the language.

**Comment by juancarlospaco** [comment]
I am neutral, but I want Pattern Matching more close to StdLib,
even if it has to be a more simplified version of it.

**Comment by haxscramper** [comment]
Pattern matching in stdlib also requires (1) `let` expressions, (2) stable view types, and some reimplementation effort for `fusion/matching`. This issue is not directly blocking std/matching ... it really just an absolutely tiny inconsistency that I think could be fixed, that's all.

**Comment by Varriount** [comment]
I'd prefer pattern matching to be available as a non-standard library module first, and then later incorporated into the standard library. That way we have some definite evidence regarding which design or approach works best.

**Comment by haxscramper** [comment]
@Varriount and that's *exactly* why I decided to add patter matching to fusion first, so everyone could test it out and see what is working or not. Over the past 11 month since I made my PR https://github.com/nim-lang/fusion/pull/33 I didn't have have any major complaints with design, things that people *did* complain about were mostly about missing things, or lack of docs for certain parts, which I also tried to fix in timely manner. Overall I think my specification from #245 worked well enough, with only noticeable inconvenience being that there can be *only one* implementation of the patter matching in a given scope, and it would **implicitly change semantics of the built-in language construct** based on the switch expression type. Which is, IMO quite questionable.

**Comment by haxscramper** [comment]
I also did make a PR https://github.com/nim-lang/Nim/pull/17047 into stdlib when fusion was unbundled from nim, but was told (in discord discussion that followed) that "well if you want it in the standard, it should look exactly as we want it", (in context of let expressions https://irclogs.nim-lang.org/15-02-2021.html#18:49:45). I agree that we need to wait for let expressions, and some other things, and after all I decided to close the PR because "current implementation can be improved in certain areas, and regardless whether we would get it into stdlib at some point, it would differ from this PR" https://github.com/nim-lang/Nim/pull/17047#issuecomment-884336453

**Comment by Araq** [comment]
What would a parser fix that allows for `match x\nof` take?

**Comment by haxscramper** [comment]
Just to make sure, you mean this, right?

```nim
match arg
of test
```

Well in my PR I just expand `postExprBlocks` with trivial check for indentation. In case of `match arg` ... it should be able to handle all the edge cases, so command statement parsing should look ahead, check if there is an `of`, and parse it, otherwise finish parsing. 

```nim
  match arg1, arg2
  of 1: discard

  match arg1 = test
  of 1: discard
```

This can probably be done, though I don't understand why we need to get rid of colon delimiter for this, since *every single block statement* uses it - `block/try/catch/except/finally/if/else/elif/when/of`.

**Comment by Araq** [comment]
> Just to make sure, you mean this, right?

Right.

> This can probably be done, though I don't understand why we need to get rid of colon delimiter for this, since every single block statement uses it ...

Because `of` is not a block statement.

> I imagine it should be the same, or somehow considered as well?

Not for me, no, `of` is special and a keyword.

**Comment by haxscramper** [comment]
So you want to make `match` work the same way as `case` wrt. to optional colon etc.?

```nim
match arg
of 12: ...
else: ...

match arg:
of 12: ...
else: ...

match arg:
  of 12: ...
  else: ...

match arg
  of 12: ...
  else: ...
```

**Comment by haxscramper** [comment]
And note that indenting `of` might not "make sense" to you when it comes to `of`, but as a macro author I might have a different opinion about what *makes sense when it comes to DSL that I'm implementing*, including indentation. gara pattern matching used indentation for arms, https://github.com/alehander92/gara#values

```nim
match(a):
  Rectangle: # matches Rectangle(a: 0), Rectangle(a: 2, b: 4)
    echo "rectangle"
  _:
    echo "other"
```

and so did patty https://github.com/andreaferretti/patty#example

```nim
proc sum(xs: List[int]): int = (block:
  match xs:
    Nil: 0
    Cons(y, ys): y + sum(ys[])
)
```

**Comment by Araq** [comment]
I only care about 

```nim

match arg
of 12: ...
else: ...
```

The other forms can be supported for consistency, but I don't care. :-)

**Comment by haxscramper** [comment]
alright, if we can agree on supporting all forms mentioned above, I will expand my PR if possible

**Comment by Araq** [comment]
We can agree on that, yes.

**Comment by haxscramper** [comment]
https://github.com/nim-lang/Nim/pull/18798#issuecomment-917428817

> Closing because it seems like it is impossible to implement cleanly, considering all of these ridiculous edge cases that I didn't even know were valid. Basically allowing _any_ kind of flexibility with block arguments would create 'danging else' kind of situation, turning implementation in a completely broken piece of garbage, and it is not worth it.
> 
> ```nim
>   readStmt = if 1: quote do: 3 # ok now
>     else: quote do: 2
> 
>   readStmt = if 1: quote: 3 # ok now
>     else: quote: 2
> 
>   match: # Supported now
>     myOf: 12
>   of:
>     discard
> 
>   match 1: # supported now, would be ambigous to implement
>     match 2:
>     of 1: discard # For inner one, indented against 'match 2'
>     of 1: discard # Meant to be added to outer, or inner?
>   of 1: discard # Added to outer one
> ```
> 
> The same goes for `match arg\nof` - very ambiguous, current grammar is overly flexible, someone probably already depends on all edge cases that exist, and breaking their code for minor consistency improvements does not make any sense.

**Comment by Araq** [comment]
I think the language should be fixed to require `else` to be in the same **column** as the `if` etc. Misaligned code first would produce a warning, of course.

**Comment by haxscramper** [comment]
We already support too much random AST arrangements, so fixing them is nearly impossible.

```nim
import std/macros

dumpTree:
  match if a: a 
  else: b: 
    if c: 
      c
    else: d
    myof: zzz
  of a: q
```

```
StmtList
  Command
    Ident "match"
    IfExpr
      ElifExpr
        Ident "a"
        StmtList
          Ident "a"
      ElseExpr
        StmtList
          Call
            Ident "b"
            StmtList
              IfStmt
                ElifBranch
                  Ident "c"
                  StmtList
                    Ident "c"
                Else
                  StmtList
                    Ident "d"
              Call
                Ident "myof"
                StmtList
                  Ident "zzz"
            OfBranch
              Ident "a"
              StmtList
                Ident "q"
```

That does not make sense to me (I don't really know what should "correct" AST look like for this code. (Colon after b is supposed to close post expr block for match, so second if should be in the main body, but it got parser into call for 'b' for some reason.)), I assume it does not make sense to you either, but I'm pretty sure there is a line somewhere (maybe even in important packages) that relies on this behavior.

**Comment by Araq** [comment]
> I assume it does not make sense to you either, but I'm pretty sure there is a line somewhere (maybe even in important packages) that relies on this behavior.

As long as the code breakage isn't silent I don't mind it too much. We need to have a 2.0 release anyway for `--gc:orc`. Cannot hurt to make Nim's grammer saner while we're at it.

**Comment by haxscramper** [comment]
Assessing damage done by parser changes is relatively easy and can be done for whole ecosystem (at least it was not particularly time-consuming to parse all existing code to figure out stdlib usages), so we can make an informed decision when it comes to considering this change.
