### ISSUE TITLE
Use setter `seq.len = 10` instead of `seq.setLen(10)`

### ISSUE THREAD

**Issue by al6x** [nim-lang/RFCs#424]
It's more consistent with getting the length `echo seq.len` and looks better.

It's probably not worth to deprecate `setLen`, too breaking change, but it may be worth to add `len=` setter and put a note in docs and manual that `setLen` is older version.

**Comment by Araq** [comment]
But then we have two ways to write the same and people would be "confused" about whether there is a difference between `s.setLen 0` and `s.len = 0`. Not worth it.
