### ISSUE TITLE
For loop in reverse order

### ISSUE THREAD

**Issue by al6x** [nim-lang/RFCs#425]
Sometimes it's useful to iterate in reverse order

```Nim
for i in 10..1:
  echo i
```

**Comment by konsumlamm** [comment]
It would be very helpful if this RFC included more information, like more motivation. alternatives, drawbacks, etc. See the other RFCs for examples of that.

This has been requested quite often and it has been explained equally often that "reverse ranges" (`a..b` where `a > b`) are empty for a reason, namely that things like `0..(a.len - 1)` would silently be buggy. As another data point, [Rust also has this behaviour](https://doc.rust-lang.org/std/ops/struct.RangeInclusive.html). Apart from that, it would be a (silent) breaking change, which is yet another reason against changing this.

Additionally, this can already be achieved by using the [`countdown`](https://nim-lang.github.io/Nim/system.html#countdown.i%2CT%2CT%2CPositive) iterator:
```nim
for i in countdown(10, 1):
  echo i
```

**Comment by Varriount** [comment]
While this makes sense logically, practically there are a few points against it:
  - Changing this would break quite a large amount of existing code.
  - In the majority of cases, the current behavior is more useful.

**Comment by al6x** [comment]
Ok, closing then.

> Additionally, this can already be achieved by using the countdown iterator:

There are so called Machete vs SwissKnife designs. With machete, you have simple knife that could do many things, and the more you master it the more you can do. With SwissKnife, you have a box of predefined narrow use tools and you can pick tool you need, but you can't quite combine it the same way and you need to remember and know all those tools. 

I think this is about this situation, where you can't reuse a "Range" tool in new situation, and need to pick up another specific "countdown" tool.
