### ISSUE TITLE
[WIP] Unified Effects, async/await and Exceptions

### ISSUE THREAD

**Issue by locriacyber** [nim-lang/RFCs#434]
# Unified Effects, async/await and Exceptions

## Abstract

I think it's beneficial to have all possible effects of a program type checked together, instead of having exceptions be a separate concept to manage. Having a solid effect system based on type system also allows async/await to be implemented in user-space.

## Motivation

- one way to manage effects
- fine-grained function coloring, arbitrary amount instead of 2 (async/sync)
- removes the need for allocation on Exception; just jump to exception handler is fine
- continue from exception
- define DSL with less `template`
- replace global and context variables and check if context variables exist at compile time
- all effects except the core ones are user-space
- use C library while knowing what is still guaranteed

## Description

1. Every procedure has a list of effects.
2. Users can consume effects with effect handlers
3. Users can produce effects with defining new effects and use an effect's callbacks
4. The compile keeps track of all the effects and users can annotate any `proc` with possible and impossible effects

Koka, a programming language self-labeled "A Functional Language with Effect Types and Handlers" has the following [built-in effect types](https://koka-lang.github.io/koka/doc/std_core_types.html):
- alloc<h>: procedure may allocate on heap `h`
- div: may not halt
- local: may access local variable
- read<h>: may read from heap `h`
- write<h>: may write to heap `h`
- ndet: nondeterministic, usually used with `read` and `write`

Note that there is no `abort` or exception effect type. The effect system ensures that if an effect isn't handled at program entry point, the program won't compile.

Nim may add the following effects as part of its standard library:
- IO effects
- Exception effect (parameterized by the exception type)
- Defect (the effect system will allow defects to be handled)
- Suspension effect (async/await)

### Downsides

Maybe it's hard to implement and slow to compile.

## Examples
In the following examples, I used "effect:" for denoting effects for clarity. A shorted syntax will be in final implementation.

### Before
```
proc foo(x: Input): Output {.async.} = ...
proc fpure(x: Input): Output {.noSideEffects.} = ...
```
### After
```
proc foo(x: Input): Output = ...# by default, any effect is inferred
proc fpure(x: Input): Output {.effects:div.} = ... # procedure doesn't have any affect but might not terminate
```
### Effect Operations
```
import effects # hypothetical standard library

const indexErrorEffect = effects.RaiseEffect[IndexDefect] + effects.RaiseEffect[KeyError] # effects are just types and `+` means "add two effects together
const indexErrorEffect2 = effects.raises([IndexDefect, KeyError]) # same thing as above; `raises` is a pure function written in Nim

type procIE = proc () {.effects:indexErrorEffect.} # here we define a procedure with some effect
type procIO = proc () {.effects:IOEffect.} # a procedure that may do IO stuff

const indexErrorEffect3 = effects.effectsOf(procIE) # same as indexErrorEffect
const indexErrorEffect4 = indexErrorEffect3 + effects.effectsOf(procIO) # a better solution than `effectsOf` pragma

# when defining a procedure `autoeffects` is the inferred effects of the procedure
proc procNoIO() {.effects:autoeffects - IOEffect.} # this procedure can do anything but not IO; i.e. will only compile when no IO is done inside it
proc procNoException() {.effects:effects.noException(autoeffects).} # `noException` is a pure function that plucks every exception effect from given effect type.
```

## Backward incompatibility

To my knowledge, it is possible to make most old pragmas work.

**Comment by Araq** [comment]
You seem to have read more about Koka than about how Nim's effect system actually works.

**Comment by locriacyber** [comment]
In the current 1.6 release:
1. No generic effect
The following code compiles while it shouldn't.
```
type IO[T] = object ## input/output effect
proc readLine(): string {.tags: [IO[int]].} = discard

proc main() {.tags: [IO[float]].} =
  # the compiler prevents this:
  discard readLine()
```

2. No way to assert that a procedure raises one less exception type than some other procedure
3. No way to ensure that a procedure has no allocation in it. Important for tasks that can't abort on memory allocation failure.
4. `Defect`'s effect change change based on `--panics:on`. It would be better if Nim maps that to an effect like `abort`, and then you can consume the effect in some scope so that division by zero won't kill your whole program.

**Comment by Araq** [comment]
1. Bugs are bad but usually don't justify an RFC process.
2. Well this works:

```nim


proc foo() {.raises: [ValueError].} =
  raise newException(ValueError, "v")

proc bar() {.raises: [IOError].} =
  raise newException(IOError, "io")

proc main {.raises: [IOError].} =
  try:
    foo()
  except ValueError:
    echo "caught"
  bar()

main()
```

3. Easily done when you wrap your allocation procs in an AllocEffect but it's pointless. You might as well try to prevent that the function uses stack space. Stack allocations can fail too.
4. No it wouldn't be "better", we don't even know if it can work at all. No production PL out there uses "checked panics", no Golang does not do it, Python doesn't do it, C# doesn't do it, etc.

**Comment by locriacyber** [comment]
2. What if the procedure you call has too many exceptions? And the list of exceptions might change during library update.
3. Same as 2: I want the compiler to check it for me so I don't have to read all the code I use when I don't want heap allocation.
4. In Go you can use `recover` to stop goroutine from aborting. In Python, unless you use FFI, every program error won't end the program rightaway. C# is the same. In Nim, `Defect` may or may not be caught depend on a compiler flag.

**Comment by Araq** [comment]
2. It would still be checked by the compiler?
3. Sounds like a problem you just made up, sorry.
4. Well but then you argue that `--panics:on` shouldn't exist. Quite different from "we can use the type/effect system to handle Defects".
