### ISSUE TITLE
Doing in batch and quick: declaring, initializing, filling individual identifier

### ISSUE THREAD

**Issue by abdulbadii** [nim-lang/RFCs#449]
There's no yet way to do in batch and quick, declaring, initializing, filling, and type conversion at once into identifiers from array ?   
e.g.

The identifier `a ,b, c, ...k` need to be initialized, filled, and converted their types to `string` at once, with array e.g
`arr :seq[int] = @[7, 41, 3, 9, 33, 6, 99, 17, 8, 2, 1]`   

(remind us an interpreter, Perl, feature)
So ask as new feature if it really cannot do unless there simple workaround to solve it

**Comment by Araq** [comment]
Maybe you are looking for `sequtils.mapIt` but in any case, ask questions on the forum, this is a tracker for RFCs.
