### ISSUE TITLE
the must build_all that'd be able to resuming all build process

### ISSUE THREAD

**Issue by abdulbadii** [nim-lang/RFCs#452]
Must have option for the build_all that is able to resuming from the last compilation step

Summary
Urgently needed on the poor hardware quickly getting overheated and "sudden death" is the build_all being able to resuming of the last compilation step

**Comment by Araq** [comment]
This is not an RFC and if you need things "urgently", feel free to patch the generated scripts yourself so that they do what you think they should do.
