### ISSUE TITLE
capacity for seq and string

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/RFCs#460]
## Abstract

Allow read-only access to `cap` of `seq` and `string`.
The name is suggested to be `capacity` instead of `cap`.
It is a very simple and tiny RFC.

## Motivation

It is a nice information to design macros and metaprogramming, 
like unrollings, `setLen`, `newStringOfCap`, `newSeqOfCap`, etc.

`len` and `setLen` of `seq` and `string` is usable, but `cap` is not.

## Examples

I imagine something kinda like 

```
func capacity*(self: string): int
```

(Pseudocode-ish)

Change would require 3 ~ 5 lines at most (?).

### Before

`cap` is not accessible, it is always unknown.

This can not be implemented with third-party Nimble modules, in a non-hacky way at least.

### After

`myString.capacity` returns an `int` with the allocated capacity.

## Backward incompatibility

No backward-incompatible changes, because it is a new proc.

**Comment by Araq** [comment]
Since this probably yet another system.nim extension and it is rather rare to come up, can we name is `capacity` and `setCapacity`?

**Comment by Araq** [comment]
Neither "space" nor "room" is as spot on as "capacity" is though. But of course, it's subjective.

**Comment by Vindaar** [comment]
I'd stick to something related to "capacity". Whether it's the short form "cap" or the full word, I personally don't care too much though.

**Comment by arnetheduck** [comment]
related: https://github.com/nim-lang/Nim/issues/19727

**Comment by planetis-m** [comment]
One thing to consider that came up with my work, is that when exposing internal state, like capacity to user code, is that when fuzzing code like that it would be impossible to correctly reproduce the conditions for a crash. That's because when copying or serializing the capacity is not saved.
