### ISSUE TITLE
Option to ignore unknown pragmas

### ISSUE THREAD

**Issue by metagn** [nim-lang/RFCs#461]
Currently shims are required for code that uses newly added pragmas to work in older versions.

```
when defined(nimHasEffectsOf):
  {.experimental: "strictEffects".}
else:
  {.pragma: effectsOf.}

proc mysort(s: seq; cmp: proc(a, b: T): int) {.effectsOf: cmp.}
```

If the shim is not there, we get the error `invalid pragma: effectsOf: cmp`. The proposal is to add a command line/config option that ignores unknown pragmas like this one and emits a warning that an unknown pragma was attempted to be used. 

This will be a easy workaround for using newer code without shims in older versions. Adding new pragmas will also not be as big of a problem for backwards compatibility.

Currently there is a simple way to do this by turning the "invalid pragma" error into a warning then adding a `--warningAsError` option for it in the default Nim config. This can then be overriden by `--warningAsError:WarningName:off`. But having invalid pragma originally as a warning in the compiler might be dangerous.

**Comment by mratsim** [comment]
> This will be a easy workaround for using newer code without shims in older versions. Adding new pragmas will also not be as big of a problem for backwards compatibility.

Adding new pragmas being tedious sounds like a win to me.
Also explicit > implicit.

While not strongly against, I think the current situation is OK

**Comment by Araq** [comment]
Sorry but this is worse esp since pragmas can be user-defined too. And in an ideal Nim the builtin pragmas would just be like other pragmas and namespaced so that you can use `.system.importc` etc. Eventually we will have this and "warning on unknown pragma" doesn't fit this goal.
