### ISSUE TITLE
Only allow `pure`/specifically annotated enums to be overloaded

### ISSUE THREAD

**Issue by metagn** [nim-lang/RFCs#468]
### Abstract

Require an annotation/pragma (preferably a repurposed/renamed `{.pure.}`) on enum types to be able to use their fields as overloads.

### Motivation

The following code works without, but breaks with `--experimental:overloadableEnums` (https://github.com/nim-lang/Nim/issues/20077):

```nim
type Foo1 = enum abc
block:
  type Foo2 = enum abc
  doAssert abc is Foo2
```

A more important version of this problem is with imports. There are multiple tests for this, both [without](https://github.com/nim-lang/Nim/blob/62b81d7f109b2ec4b249a0abea121d7e0bc14d86/tests/sets/tsets.nim#L72) and [with](https://github.com/nim-lang/Nim/blob/devel/tests/enum/tregression.nim) imports.

However, this is mostly intended behavior of overloadableEnums. Consider the following:

```nim
# a.nim
type A* = enum
  Left, Right

# b.nim
type B* = enum
  Left, Down

# c.nim
import a, b

type C* = enum
  Left, South

let what = Left
```

An ambiguity error is the most sensible outcome here; with `--experimental:overloadableEnums` there is an ambiguity error, without it, `what` has type `C`. So the behavior of `overloadableEnums` here is preferred.

The difference between the example code and the test cases is that in the example case, the enums would normally have the `{.pure.}` annotation, while other enums may not necessarily need fancy behavior like this. So maybe the best solution is to restrict this overloading behavior to pure enums, while also removing any remaining need for qualification of pure enums.

### Description

`pure` as is is generally regarded to be useless and deserving deprecation because of it not working as documented, so giving it new meaning that is compatible with its common/intended use is acceptable. If a new name for this is used instead of `pure`, then `pure` can be deprecated and alias to the new name. 

This will make the transition to `--experimental:overloadableEnums` easier for normal projects, as they can gradually enable certain enums to work this way. Projects already using `--experimental:overloadableEnums` will have to annotate their enums with `pure`. We could make `pure` the default somehow but this doesn't fit the narrative of them being "fancy" enums.

### Code Examples

```nim
# a.nim
type A* {.pure.} = enum
  Left, Right
```
```nim
# b.nim
import a

type B* {.pure.} = enum
  Left, Down

when isMainModule:
  assert not compiles((let left = Left; left))
  assert compiles((let left: A = Left; left))
  assert compiles((let left: B = Left; left))
```
```nim
# c.nim
import a, b

type C* = enum
  Left, South

when isMainModule:
  assert Left is C
```
```nim
# d.nim
import c

type D* = enum
  Left, Back

when isMainModule:
  assert Left is D
```

### Backwards Compatibility

Backwards incompatible for projects already using `overloadableEnums` however the fix is extremely adaptable and simple.

If `pure` is used, the behavior of the old `pure` would be removed, but this can still only be under `--experimental:overloadableEnums`.

**Comment by Araq** [comment]
The problem with this proposal is that it keeps two distinct forms of `enum` in Nim. Ideally there is only one `enum` construct that just works.

**Comment by metagn** [comment]
Then should these tests be removed? Keeping the tests means we would need to keep some way to opt in/out of overloadableEnums, meaning there would still be 2 enum constructs.

**Comment by al6x** [comment]
I dislike this proposal. Overloadable enums looks like a proper way enums should work by default.

**Comment by Araq** [comment]
> Should these tests be removed then?

Yes.

**Comment by metagn** [comment]
> > Should these tests be removed then?
> 
> Yes.

Done in https://github.com/nim-lang/Nim/pull/20298
