### ISSUE TITLE
Unicode proposals

### ISSUE THREAD

**Issue by data-man** [nim-lang/RFCs#47]
### Comparison with standard libraries of some languages (not finished)

|                                    |stdlib unicode|Proposed RFC  |Nitely's Nim packages  |D                |Go           |Julia           |Python3        |Rust         |
|------------------------------------|--------------|--------------|-----------------------|-----------------|-------------|----------------|---------------|-------------|
|**Unicode data version**            |              |              |                       |                 |             |                |               |             |
|                                    |Unknown       |10.0          |10.0                   |6.2.0            |10.0         |10.0            |10.0           |10.0         |
|                                    |              |              |                       |                 |             |                |               |             |
|**Character type**                  |              |              |                       |                 |             |                |               |             |
|                                    |Rune          |CodePoint     |Rune                   |dchar            |rune         |Char            |               |char         |
|**Data structures/search algorithm**|              |              |                       |                 |             |                |               |             |
|Data structure(s)                   |Range tables  |Range tables  |Two stage table        |Trie             |Trie         |Two stage table |Two stage table|Trie         |
|Search algorithm                    |binarySearch  |binarySearch  |                       |                 |             |                |               |             |
|                                    |              |              |                       |                 |             |                |               |             |
|**Character sets**                  |-             |?             |-                      |+                |+            |+               |               |?            |
|                                    |              |CodePointSet  |                       |CodepointSet     |RangeTable   |                |               |             |
|                                    |              |CodePointRange|                       |CodepointInterval|             |                |               |             |
|                                    |              |              |                       |                 |             |                |               |             |
|**Character names**                 |-             |?             |+                      |+                |+            |-               |               |-            |
|                                    |              |              |                       |                 |             |                |               |             |
|**Character widths**                |-             |?             |+                      |-                |+            |+               |               |-            |
|                                    |              |              |                       |                 |             |                |               |             |
|**Composition**                     |-             |?             |+                      |+                |+            |-               |               |?            |
|                                    |              |              |                       |                 |             |                |               |             |
|**Decomposition**                   |-             |?             |+                      |+                |+            |-               |               |?            |
|                                    |              |              |                       |                 |             |                |               |             |
|**Graphemes**                       |-             |?             |+                      |+                |+            |+               |               |?            |
|                                    |              |              |                       |                 |             |                |               |             |
|**Normalization**                   |              |?             |                       |                 |             |                |               |+            |
|NFC                                 |-             |              |+                      |+                |+            |+               |               |             |
|NFD                                 |-             |              |+                      |+                |+            |+               |               |             |
|NFKC                                |-             |              |+                      |+                |+            |+               |               |             |
|NFKD                                |-             |              |+                      |+                |+            |+               |               |             |
|                                    |              |              |                       |                 |             |                |               |             |
|**Character categories**            |-             |?             |+                      |-                |+            |-               |               |             |
|                                    |              |              |                       |                 |             |                |               |             |
|**Character properties**            |-             |?             |+                      |-                |+            |-               |               |             |
|                                    |              |              |                       |                 |             |                |               |             |
|**Character scripts**               |-             |?             |-                      |+                |+            |-               |               |             |
|                                    |              |              |                       |                 |             |                |               |             |
|**Functions**                       |              |              |                       |                 |             |                |               |             |
|character width                     |-             |?             |unicodeWidth           |-                |+            |textwidth       |               |             |
|character is alpha                  |isAlpha       |isAlpha       |isAlpha                |isAlpha          |IsLetter     |isletter        |               |Alphabetic   |
|character is alpha or number        |-             |isAlphaNumber |isAlnum                |isAlphaNum       |-            |isalnum         |               |             |
|character is ascii                  |-             |isAscii       |-                      |-                |-            |isascii         |               |             |
|character is assigned code point    |-             |isAssigned    |-                      |-                |-            |isassigned      |               |             |
|character is combining              |isCombining   |?             |-                      |-                |-            |-               |               |             |
|character is control                |-             |isControl     |-                      |isControl        |IsControl    |iscntrl         |               |             |
|character is decimal                |-             |isDecimal     |isDecimal              |-                |-            |isnumeric       |               |             |
|character is digit                  |-             |isDigit       |isDigit                |-                |IsDigit      |isdigit         |               |             |
|character is emoji                  |-             |isEmoji       |-                      |-                |-            |-               |               |             |
|character is formatting             |-             |isFormat      |-                      |isFormat         |-            |-               |               |             |
|character is grapheme break         |-             |?             |-                      |-                |-            |isgraphemebreak |               |             |
|character is graph                  |-             |isGraph       |-                      |isGraphical      |IsGraphic    |isgraph         |               |             |
|character is lower                  |isLower       |isLower       |isLower                |isLower          |IsLower      |islowercase     |               |Lowercase    |
|character is mark                   |-             |isMark        |-                      |isMark           |IsMark       |-               |               |             |
|character is non-character          |-             |isNonCharacter|-                      |isNonCharacter   |-            |-               |               |             |
|character is number                 |-             |isNumber      |isNumeric              |isNumber         |IsNumber     |isnumber        |               |             |
|character is printable              |-             |isPrint       |isPrintable            |-                |IsPrint      |isprint         |               |             |
|character is private use            |-             |?             |-                      |isPrivateUse     |-            |-               |               |             |
|character is punctuation            |-             |isPunctuation |-                      |isPunctuation    |IsPunct      |ispunct         |               |             |
|character is space                  |-             |isSpace       |-                      |isSpace          |IsSpace      |isspace         |               |             |
|character is surrogate              |-             |?             |-                      |isSurrogate      |-            |-               |               |             |
|character is hi surrogate           |-             |?             |-                      |isSurrogateHi    |-            |-               |               |             |
|character is low surrogate          |-             |?             |-                      |isSurrogateLo    |-            |-               |               |             |
|character is symbol                 |-             |isSymbol      |-                      |isSymbol         |IsSymbol     |-               |               |             |
|character is title                  |isTitle       |isTitle       |isTitle                |-                |IsTitle      |-               |               |             |
|character is upper                  |isUpper       |isUpper       |isUpper                |isUpper          |IsUpper      |isuppercase     |               |Uppercase    |
|character is hexadecimal digit      |-             |isXDigit      |-                      |-                |-            |isxdigit        |               |             |
|character is valid                  |-             |?             |-                      |isWhite          |-            |isvalid         |               |             |
|character is white space            |isWhiteSpace  |isWhiteSpace  |isWhiteSpace           |isWhite          |-            |-               |               |White_Space  |
|character's combining class         |-             |?             |combining              |combiningClass   |-            |-               |               |             |
|to lower case                       |toLower       |toLower       |                       |toLower          |ToLower      |lowercase       |               |to_lower     |
|to title case                       |toTitle       |toTitle       |                       |-                |ToTitle      |titlecase       |               |-            |
|to upper case                       |toUpper       |toUpper       |                       |toUpper          |ToUpper      |uppercase       |               |to_upper     |
|                                    |              |              |                       |                 |             |                |               |             |

**Comment by Araq** [comment]
The Unicode tables have been updated to Unicode v12.0 and so I consider this issue solved.
