### ISSUE TITLE
Stale bot for RFCs

### ISSUE THREAD

**Issue by metagn** [nim-lang/RFCs#483]
There are many RFCs in this repo that are old or need to be rewritten for present Nim. Some of them get implemented too but don't get closed, for example `{.requiresInit.}` should close #63.

A repo for RFCs should be vetted as much as possible for potential contributors and even just users of the language to go through. It shouldn't be just a dump of discussion.

**Comment by jpalomaki** [comment]
@metagn One option is to use https://github.com/actions/stale in a scheduled GitHub workflow (e.g. `.github/workflows/stale.yml), with `days-before-stale` and `days-before-close` set appropriately (I presume they'd be set to relatively long values)

**Comment by metagn** [comment]
There is a stale bot on the main repo for PRs but I'm not sure if it's that one. It attaches a stale label and gives a warning, if anyone responds to the warning it removes the stale label, otherwise after a while it closes it. This behavior seems fitting here as well.

For the sake of this being actionable I propose a stale warning time of 1 year. Then close after a week or a month of no one responding to the warning.

**Comment by metagn** [comment]
Implemented now
