### ISSUE TITLE
Style check/remove `do:` blocks lifted to lambdas

### ISSUE THREAD

**Issue by metagn** [nim-lang/RFCs#486]
### Abstract

There is a behavior [in these lines](https://github.com/nim-lang/Nim/blob/7a756bfaef29ff521059b3310b67a0344001f5fd/compiler/sigmatch.nim#L2164-L2174) in the compiler, that allow `do:` blocks without parameter lists (parsed as raw statement lists), to be lifted to lambdas with no parameters (the same as `do ():`). The proposal is to do one of:

* Turn this into a style check hint, that is, when `--styleCheck` is turned on, hint to the programmer that `do ():` should be used (my preferred solution)
* Deprecate/remove this behavior, and turn it into a special warning/error

### Description

This is a weird special case that implies `do:` and `do ():` are meant to be the same construct, despite both commonly being used for different purposes. There is already discussion about this "inconsistency", see #264 and https://github.com/nim-lang/Nim/pull/12117.

There is no reason for `do:` to be ambiguous here, it is not hard to accept that `do:` and `do ...:` parse as different things since the visual rule is as simple as "check if there is anything between `do` and `:`". Other keywords in the language like `of`, `except`, `object`/`enum` also have different meanings with different contexts.

https://github.com/nim-lang/Nim/pull/12117 attempted to remove the distinction between `do:` and `do ():` by making them all parse as lambdas. I propose embracing the distinction and making `do:` not ambiguous, thereby making code more clear about what it does.

But, this doesn't have to be forced; the compiler can just complain about it being bad style instead of erroring. This is what I prefer, I consider it more practical. The special case is only a few lines, it doesn't really harm anyone beyond optics.

### Code Examples

```nim
proc twiceLambda(x: proc()) =
  x()
  x()

twiceLambda do (): echo "a" # fine
twiceLambda do: echo "a" # hint/warning/error: add parentheses to make a lambda

template twiceStmt(x: untyped) =
  x
  x

twiceStmt do: echo "a" # fine
twiceStmt do (): echo "a" # error
```

### Backwards Compatibility

When [tested against CI](https://github.com/nim-lang/Nim/pull/20389), only one package was affected by this in one line, [argparse](https://github.com/iffy/nim-argparse/blob/4048a76b24919807b0871dd145ba93a48c2688e7/src/argparse.nim#L308). The solution is literally just to change `do:` to `do ():` in that line.

If this is only a style check, there are obviously no compatibility problems.

**Comment by Araq** [comment]
That makes lots of sense.
