### ISSUE TITLE
Accept `zig cc` as a C compiler

### ISSUE THREAD

**Issue by sls1005** [nim-lang/RFCs#489]
### Abstract

Add an option: `--cc:zig` to support `zig cc` as a C compiler for the C backend of Nim, and `zig c++` for the C++ backend.

### Motivation

The command `zig cc` can be used as a C cross-compiler. And as a replacement for MinGW. So I hope it could be supported.

See: https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html

### Description

The command is `zig cc` for C, and `zig c++` for C++. The other cmdline options are the same as that of `clang`.

For example:
```sh
zig cc *.nim.c -I/usr/lib/nim/lib -o a.out
```

**Comment by dom96** [comment]
This doesn't need any Nim support. It's already possible using this package https://github.com/nim-lang/packages/pull/2323

**Comment by sls1005** [comment]
I see.
