### ISSUE TITLE
awesome-nim

### ISSUE THREAD

**Issue by tomByrer** [nim-lang/RFCs#496]
### Abstract

Repo to list the 'best of' repos & projects written in Nim, videos, blogs, etc.

### Motivation

good PR

### Description

takes time to keep updated

### Code Examples

https://github.com/sindresorhus/awesome

**Comment by Yardanico** [comment]
Already exists - https://github.com/ringabout/awesome-nim

There were problems with adding it to the official awesome list, but that doesn't make it any less useful.
