### ISSUE TITLE
Merge editdistance and wordwrap into strmisc

### ISSUE THREAD

**Issue by metagn** [nim-lang/RFCs#497]
### Abstract

Merge the [editdistance](http://nim-lang.github.io/Nim/editdistance.html) and [wordwrap](nim-lang.github.io/Nim/wordwrap.html) modules into the [strmisc](http://nim-lang.github.io/Nim/strmisc.html) module.

### Motivation

strmisc's description states:

> This module contains various string utility routines that are uncommonly used in comparison to the ones in [strutils](http://nim-lang.github.io/Nim/strutils.html).

`editdistance` and `wordwrap` seem to fit this description, and are small enough that they don't need to be in their own module. Having tiny procs like this in their own module clutters the standard library IMO.

### Description

The way I would do it is: directly add the code of these modules to `strmisc`, then do the following:

```nim
# editdistance.nim
from std/strmisc import editDistance, editDistanceAscii
export editDistance, editDistanceAscii

# wordwrap.nim
from std/strmisc import wrapWords
export wrapWords
```

Doesn't matter if we deprecate these or not.

**Comment by Araq** [comment]
`editdistance` could grow into supporting more than strings though. Same for wordwrap.

More importantly, these algorithms have nothing to do with each other except that they work on `string`. There are thousands of useful algorithms for strings, should they all be under "strmisc"? And why not under "strutils"? When I import editdistance I get `wordwrap` for free? Why? It makes no sense. Both "strmisc" and "strutils" are not all that well designed.

**Comment by metagn** [comment]
I would agree with you if we weren't talking about the standard library. It's more arbitrary for the standard library to have separate modules for random algorithms like `editdistance` and `wordwrap` than to have a finite number of modules that would ever need to be imported like `strmisc` and `strutils` (which is really `std/strings`). Otherwise yeah `strmisc` and `strutils` are really bad package names, but they serve their purpose fine IMO (though `strmisc` is tiny as of now, I would expect stuff like `strutils.formatSize` to go in it).

**Comment by arnetheduck** [comment]
One way here is to have `std/strings/editdistance` etc then `std/strings` reexports every string algo and users can pick their granularity
