### ISSUE TITLE
Automatically import std/assertions in runnableExamples

### ISSUE THREAD

**Issue by metagn** [nim-lang/RFCs#499]
### Abstract

Automatically import std/assertions in runnableExamples blocks.

### Motivation

Pretty much every runnableExamples block has an `assert` statement. Would save hundreds of lines of code to not have to explicitly import it in every single one.

### Description

Seems pretty self explanatory. Don't know about implementation details.

### Code Examples

```nim
runnableExamples:
  assert true # works
```

**Comment by juancarlospaco** [comment]
Workaround `runnableExamples"--import:std/assertions":`.

**Comment by ringabout** [comment]
`-d:nimPreviewSlimSystem` hasn't been enabled, so I'm not sure whether we should enforce the option for the `runnableExamples`. Otherwise, a define should be generated instead

```nim
when defined(nimPreviewSlimSystem):
  ...
```
