### ISSUE TITLE
labeled types; a path to self documented and more readable code 

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/RFCs#507]
### Abstract

Labeling types enables you to write more self-document code, both easy for you to review in the future and for other people to get the idea behind your algorithm.

it is specially good for `proc`s that do many jobs; as it is not much obvious what they are returning as result.

#### scenario 1
assume you're reading someone's code, you came upon something like this:

```nim
var cars = Table[string, bool]
```

wow! what is it? is that a table for (`ownerName` -> `isCrushed`) or (`carName` -> `hasWheels`) ??

#### scenario 2

you wanna develop a telegram bot using [telebot](https://github.com/ba0f3/telebot.nim/) for example, you came upon `UpdateCallback` type:

```nim
proc(bot: Telebot, update: Update): Future[bool] 
```

what is `Future[bool]` for? why a `bool`? you can't even guess it without reading the docs [RTFM right? :D]

### Description

but if you could somehow just **_label your types_**, the code would be a lot more readable!

#### scenario 1
```nim
var cars = Table[(name: string), (isReady: bool)]
```

#### scenario 2
```nim
proc(bot: Telebot, update: Update): (shouldEndWaiting: Future[bool])
```

### Backwards Compatibility

the syntax `(label: Type)` definitely has conflicts with one-field-tuples:

```nim
(name: string)
```

other syntaxes that I can think of:
```nim
name ! string # alternative 1
name :: string # alternative 2
(.name: string.) # alternative 3
[.name: string.] # alternative 4
```

**Comment by Varriount** [comment]
I'm not sure the complexity here is worth the possible benefit. Why not just use sensible names for types and variables? With types you can even use type aliases:
```nim
type Path = string

proc join(left, right: Path): Path
```

**Comment by konsumlamm** [comment]
My first reaction is: That's what (doc) comments are for. What benefit does this have over writing a comment that explains what the table stores or what the proc returns? IDEs can also show the doc comments, so you don't have to open the documentation separately. Sure, there are people not documenting their code, but I doubt that providing new syntax for documenting code would change that.
