### ISSUE TITLE
introduce copilot bot for pull requests

### ISSUE THREAD

**Issue by ringabout** [nim-lang/RFCs#520]
[copilot4prs](https://github.com/apps/copilot4prs) is an official GitHub App to make pull requests overview work like a breeze. See also https://githubnext.com/projects/copilot-for-pull-requests.

It generates summary like

![image](https://user-images.githubusercontent.com/43030857/233836223-11b5e1a0-83cb-4b61-bd12-41d3b66e52c9.png)

~~It is also a chance to let the AI know more about the Nim lanaguge.~~

**Comment by Yardanico** [comment]
> It is also a chance to let the AI know more about the Nim lanaguge.

But those tools will not make the AI learn more about Nim, their output isn't used for training the model.

**Comment by Yardanico** [comment]
Also, "Once installed, you will have the ability to add select repositories to a waitlist" it'll only add the repo to the waitlist, it doesn't guarantee immediate access, although they might specifically enable it for Nim if you ask.

**Comment by ringabout** [comment]
> Also, "Once installed, you will have the ability to add select repositories to a waitlist" it'll only add the repo to the waitlist, it doesn't guarantee immediate access, although they might specifically enable it for Nim if you ask.

Yeah, I knew that. I have requested access to adding it to waitlist since I'm not the owner of the org. I have seen other programming languages which are approved of access. So it never hurts to try.

**Comment by juancarlospaco** [comment]
Theres also https://sourcery.ai Free for open source.
