### ISSUE TITLE
remove `deprecated` statement

### ISSUE THREAD

**Issue by metagn** [nim-lang/RFCs#521]
### Abstract

Get rid of the deprecated pragma statement syntax.

```nim
type New = object
{.deprecated: [Old: New].}
```

### Motivation

This feature is redundant over the `deprecated` pragma next to definitions. It was added [a very long time ago](https://github.com/nim-lang/Nim/commit/1f63d1c76e733812e5e61d81e83429f853511fe7#diff-3a0e33a349c8918a83a500b34d594fff2aac2129d4f4ef2e1464b12ac922f646) but never documented in the language spec (or its documentation was removed). It still had use cases for a while because 1. some kinds of symbols (like const) used to not support the pragma, which they now do, and 2. the `nimfix` tool can automatically replace the old name with the new name (see description below for how to deal with this).

The biggest reason to remove it though is the fact that it is the sole remaining user of the internal `skAlias` symbol kind which requires `skipAlias` calls everywhere in the compiler, and when some parts of the compiler forget to call it, it causes issues: https://github.com/nim-lang/Nim/issues/14819.

### Description

How to make `nimfix` still work:

1. don't
2. make nimfix parse stuff like "nimfixReplace:xyz" or "use xyz instead" (could give wrong code) in the deprecated message in `markUsed`
3. define a custom pragma `template deprecatedReplace(newName: untyped) {.pragma.}` which then `nimfix` would look for in `markUsed`

I vote 1 because 2 and 3 are way too opt-in and tedious to implement and I've never heard of anyone using nimfix.

### Code Examples

```nim
type
  New = object
  Old {.deprecated: "use New instead".} = New # https://www.youtube.com/watch?v=BnTdfA5aTpY

type Foo = enum fooX
# this works since 2.0 (specifically PR #20115)
const fooA {.deprecated: "use fooX instead".} = fooX
```

### Backwards Compatibility

Backwards incompatible for people who used this, but can use `when` and version check to work around.

Only use I could find in the old Nim standard library was [db_connector/mysql](https://github.com/nim-lang/db_connector/blob/e65693709dd042bc723c8f1d46cc528701f1c479/src/db_connector/mysql.nim#L198) (used regex `deprecated\s*:\s*\[`). I don't think many people used this but it's still worth checking if they did.

**Comment by Araq** [comment]
It was meant for a transition period and it was used during this period successfully. Now it's time to let it die and make the compiler a tiny bit simpler (and faster) internally.

**Comment by Araq** [comment]
A tool that can do the "rename" refactoring feature automatically. It was used successfully back in the days and could be revived, but this doesn't require this pragma.

**Comment by metagn** [comment]
Packages caught in Nim CI that use the deprecated statement along with db_connector as mentioned above:

* sdl2 [keycodes](https://github.com/nim-lang/sdl2/blob/82dc936bc25c223947feec9d799789a184b27fe1/src/sdl2/private/keycodes.nim#L406-L407), [gfx](https://github.com/nim-lang/sdl2/blob/82dc936bc25c223947feec9d799789a184b27fe1/src/sdl2/gfx.nim#L878)
* zip [zzip](https://github.com/nim-lang/zip/blob/6f627c7d7354e274aaf72f008cf46b09f3a37742/zip/zzip.nim#L69-L71), [zipfiles](https://github.com/nim-lang/zip/blob/6f627c7d7354e274aaf72f008cf46b09f3a37742/zip/zipfiles.nim#L21), [libzip](https://github.com/nim-lang/zip/blob/6f627c7d7354e274aaf72f008cf46b09f3a37742/zip/libzip.nim#L84-L86), [zlib](https://github.com/nim-lang/zip/blob/6f627c7d7354e274aaf72f008cf46b09f3a37742/zip/zlib.nim#L52-L53)
* [nimquery](https://github.com/GULPF/nimquery/blob/4ed0ce9e8e1e6e7d0ea2bfdbd15cd4008063ee21/nimquery.nim#L118)
* sdl1 [a lot of places](https://github.com/search?q=repo%3Anim-lang%2Fsdl1%20deprecated&type=code)

Since these are versioned, it may be fine to make PRs just removing these, since they've been there for a long time and it's not likely anyone uses the deprecated names.
