### ISSUE TITLE
introduce two xor operations for `set[T]`

### ISSUE THREAD

**Issue by mrgaturus** [nim-lang/RFCs#554]
### Abstract

xor instructions usage for `set[T]` are missing
we can introduce two important operations which make usage of xor instructions:
`a ^ b`: calculates xor between a and b
`a.toggle(b)`: toggles b elements of a

### Motivation

xor operations are useful to check differences between two sets or toggle elements of a set

### Description

`set[T]`  is an easy way to do bitflags in Nim, however a bitwise masking operation is missing and that is xor operation, it's importance is mostly to check differences between two sets or toggle elements of a set. those may be done with more operations but it's not so efficient as use xor directly. another workaround is casting to an unsigned integer but it might be unsafe and not so elegant also may not work at vm side.

we can introduce two operations which make usage of xor instructions:
`a ^ b`: calculates xor between a and b - magic: `XorSet`
`a.toggle(b)`: toggles b elements of a - magic: `ToggleSet`

### Code Examples

example of `a ^ b`:
```nim
type
  MyFlags = enum
    flagA, flagB

var flags: MyFlags
let flags0 = flags
# ... do something with those flags ...

# react to flags changes
let delta = flags0 ^ flags
if flagA in delta:
  echo "flagA changed"
if flagB in delta:
  echo "flagB changed"
```

example of `a.toggle(b)`:
```nim
type
  MyFlags = enum
    flagA, flagB, flagC
  MyState = object
    flags: MyFlags

# ... suppose there is a toggle button widget in a gui app ...
proc onclickButtonC(state: var MyState) =
  state.flags.toggle( {flagC} )
```

### Backwards Compatibility

introduces two straightforward magics and two simple procs to system for `set[T]`, no breaking changes

**Comment by Zectbumo** [comment]
So `a ^ b` modifies `a` in the ToggleSet?
Would `a ^= b` be more appropriate in that case?

**Comment by metagn** [comment]
I thought this already existed as "symmetric difference" but apparently not for bitsets, unless I'm missing something. Makes sense to add since it does directly map to `xor`.

The `toggle` name is good but for the regular operation we might want to keep the same naming with [hash sets](https://nim-lang.org/docs/sets.html#symmetricDifference%2CHashSet%5BA%5D%2CHashSet%5BA%5D).

It's even implemented in the compiler already, just not used: [bitsets](https://github.com/nim-lang/Nim/blob/7dfadb8b4e95d09981fbeb01d85b12f23946c3e7/compiler/bitsets.nim#L50), [nimsets](https://github.com/nim-lang/Nim/blob/7dfadb8b4e95d09981fbeb01d85b12f23946c3e7/compiler/nimsets.nim#L122) (for VM presumably).

**Comment by mrgaturus** [comment]
> I thought this already existed as "symmetric difference" but apparently not for bitsets, unless I'm missing something. Makes sense to add since it does directly map to `xor`.
> 
> The `toggle` name is good but for the regular operation we might want to keep the same naming with [hash sets](https://nim-lang.org/docs/sets.html#symmetricDifference%2CHashSet%5BA%5D%2CHashSet%5BA%5D).
> 
> It's even implemented in the compiler already, just not used: [bitsets](https://github.com/nim-lang/Nim/blob/7dfadb8b4e95d09981fbeb01d85b12f23946c3e7/compiler/bitsets.nim#L50), [nimsets](https://github.com/nim-lang/Nim/blob/7dfadb8b4e95d09981fbeb01d85b12f23946c3e7/compiler/nimsets.nim#L122) (for VM presumably).

I agree name it `-+-` like in hashsets instead `^` but `^` is more similar as symmetric difference math symbol

**Comment by mrgaturus** [comment]
> So `a ^ b` modifies `a` in the ToggleSet? Would `a ^= b` be more appropriate in that case?

I named it `toggle` because operations that modifies the sets: `incl` and `excl` are not `+=` and `-=` respectely
