### ISSUE TITLE
RFC: Placeholder AST nodes

### ISSUE THREAD

**Issue by drslump** [nim-lang/RFCs#59]
This proposal tries to address the use of *injected* expressions in a less surprising way to the user. The more ambitious approach on #8675 is a hard sell so I would like to propose a solution that can gather more consensus while still remaining compatible with the other RFC goals.

Currently in Nim an *identifier* cannot start with `_`, the symbol however is valid as part of identifiers and can also be used to separate numeric literals. So there is the interesting opportunity of having `_` produce a new AST node to signal a *placeholder*.

Placeholders can optionally have an identifier to assign a name to them, and can appear anywhere an `ident` node can in the grammar. The rule for it would be:

    PLACEHOLDER ::= '_' IDENT?

A *placeholder* node can only exist in the AST before semantic analysis, it must be dealt with in the initial phases of the compilation, probably by a macro. Failing to do so would produce a compiler error indicating that the *placeholder* wasn't properly handled. This allows to reduce the changes required in the compiler to support the new node while also serving as safety guard against wrong usage.

Macros receiving an `untyped` expression can analyze it looking for *placeholder* nodes to do the appropriate transformation. This serves two purposes, first it allows the user to choose a placeholder name that matches the implemented logic, secondly it permits the macro author to perform error checking by asserting the number of placeholders found in the expression.

Using the `sequtils` templates as examples:

```nim
# a placeholder might not have a name and can be repeated
acceptable = filterIt(temperatures, _ < 50 and _ > -10)
# also can have arbitrary names, signifying that they are different values
foldl(numbers, _a + _b)
```

The main benefit is that it provides the user with a language-wide *visual cue* about the way in which the expression will be evaluated. The `_` at start position always introduces a placeholder and cannot be compiled unless transformed. It also helps authors to implement more robust macros since now there is a language mechanism for that use case.

This RFC still has the shortcoming that an user must know that a library implements the macro behavior in order to use the placeholders, it's an implementation detail that leaks in my opinion.

One potential advantage of going with the placeholders syntax, that should be explored further, is to implement a pass for them in the compiler. That way non-transformed placeholder nodes would be handled generically by the compiler instead of erroring out before the semantic pass takes place. This transformation could perhaps pave the way to unify *do notation* with *template code blocks* like in the following example:

```nim
data.sort do (a, b: auto) -> auto:
    a.lower < b.lower

# compiler creates a proc expression as argument to sort based on the placeholders
data.sort:
  _1.lower < _2.lower
```

**Comment by Araq** [comment]
Interesting ideas but nobody is working on it and `it` is here to stay.
