### ISSUE TITLE
Add a Warning or Note when not all body values are set.

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/RFCs#63]
We can start with code like this:

```
type
  Dog = object
    name: string

# Somewhere else, very far away in the codebase....

var dog = Dog(name: "Jack")

echo $dog
```

Which when run, gives this output:

```
(name: "Jack")
```

Later on, we decide that all Dog records need an age field, so we update our definition:

```
type
  Dog = object
    name: string
    age: Natural
```

However, our printed output becomes this in that case:

```
(name: "Jack", age: 0)
````
My request is for a warning or note that this field wasn't set (eg even to an empty/default value by the user code):

```
var dog = Dog(name: "Jack")
```

To make the warning or note go away, you need to change the code to eg:

```
var dog = Dog(name: "Jack", age: 3)
```

Or alternately, perhaps the new age field can be marked as {.disposable.} if we don't care what default values new fields get later on.

I see this as (a bit) similar to requiring that functions (not marked as .disposable.) log warnings when their return codes aren't used.

eg above could be seen as analogous to a proc that didn't return a value, being updated to return a value.

**Comment by Araq** [comment]
Has been implemented by the name of `.requiresInit`.
