### ISSUE TITLE
[RFC] module/package level pragma `{.doctype: markdown|rst.}` to help migrate docs from RST to Markdown 

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#68]
There seems to be a consensus (or near-consensus) that markdown is preferred over RST for documentation, see https://forum.nim-lang.org/t/4280 (Drop RST and join the Markdown train?) and that the only valid argument for keeping RST is historical reason.

A number of people have also noted that supporting a hybrid will just cause more issues, so let's explore practical ways to gradually migrate docs to markdown.
To ease the migration I propose the following:

introduce a module/package-level annotation `{.doctype: markdown|rst.}` which states how to interpret documentation comments (as either markdown or RST depending on doctype).

## usage
```nim
foo/
  nim.cfg # contains --doctype:markdown : applies to all modules under foo/
  foo_bar1.nim
  foo_bar2.nim # can override nim.cfg with `{.doctype: markdown|rst.}`
bar3.nim
bar4.nim # contains `{.doctype: markdown.}`
```

so `doctype` would only have to be specified at a few places (eg just 1, in nimble/nim.cfg/config.nims) until this becomes the new default.

## automating documentation source code migration from rst to markdown
* tooling should be able to handle the 99% case fairly easily, the rest could be manual fixups; tooling should report when it can't transform a doc comment, and when the resulting markdown is invalid; this could be part of nim doc, nimpretty, or a separate tool.

**Comment by Araq** [comment]
There simply isn't so much of a difference between Markdown and RST. Rejected. Also: The docgen now supports more markdown features.
