### ISSUE TITLE
[RFC] Add shallow/deep option/pragma to term-rewriting macro

### ISSUE THREAD

**Issue by mratsim** [nim-lang/RFCs#69]
Background in https://github.com/nim-lang/Nim/pull/9305#issuecomment-428893096

Related to: https://github.com/nim-lang/Nim/issues/9288, https://github.com/nim-lang/Nim/issues/2901, https://github.com/nim-lang/Nim/issues/8376

In some (several?) cases you only want to replace the first function call and don't need to apply the TRM recursively.

One such case is modular arithmetic, assuming I want to do `addmod(3, 4, 5) == 3 + 4 mod 5`, `addmod` will be implemented in terms of addition (and substraction) but I don't want to replace the addition inside `addmod` definition.

**Comment by metagn** [comment]
Can this be closed due to `{.noRewrite.}` which is [documented](https://nim-lang.github.io/Nim/manual_experimental.html#term-rewriting-macros-norewrite-pragma)?
