### ISSUE TITLE
Copyright headers in files

### ISSUE THREAD

**Issue by dom96** [nim-lang/RFCs#7]
As an example: https://github.com/nim-lang/Nim/blob/devel/lib/pure/json.nim

``` nim
#
#
#            Nim's Runtime Library
#        (c) Copyright 2015 Andreas Rumpf, Dominik Picheta
#
#    See the file "copying.txt", included in this
#    distribution, for details about the copyright.
#
```

We need to come up with ways to decide what names are written after the "Copyright".

I suggest simply modifying everything to read `Copyright (C) Andreas Rumpf and constributors`. But I haven't looked at how other projects do it.

Thoughts?

**Comment by Araq** [comment]
We didn't do anything about it for 4 years, closing.

**Comment by dom96** [comment]
> After discussing this with Araq, we've decided on the following:
>
>  * Changing the copyright message to "Copyright (C) Nim Developers"
>  * Adding a "Maintainers: " to the header which will include the names of the maintainers of that file.


I'm happy to write a quick script to do this. But not sure there is much point to the "maintainers" part. Can we just link to the github history of the file to allow people to check the most recent/common contributors?

**Comment by Araq** [comment]
Instead of listing "maintainers" we can list the "original author" and give him/her some credit.

**Comment by xflywind** [comment]
Imo, we can give credits to everyone who wants to include their names in the modules to encourage more people to contribute to Nim. If they want, they can just add their names to the contributor list.

```nim
#            Nim's Runtime Library
#        (c) Copyright 2022 Nim contributors
#
#    See the file "copying.txt", included in this
#    distribution, for details about the copyright.
#
#    contributors: [...]
```

Btw GitHub also tells everyone who are the original author or contributors.
![image](https://user-images.githubusercontent.com/43030857/165964014-122e6984-4bcd-44c9-ba4c-674d96f15866.png)
