### ISSUE TITLE
[RFC] Updating the fields of a DateTime is unsafe

### ISSUE THREAD

**Issue by GULPF** [nim-lang/RFCs#75]
## The problem

It's current possible to mutate the fields of a `DateTime` object, but it's very unsafe since it's easy to end up with an invalid state. Examples of invalid states include:

- Dates that are impossible in the gregorian calendar, e.g February 30.
- Date & time that are impossible in the timezone being used, e.g 2018-03-25T02:30 in the Europe/Stockholm timezone (at 02:00 the clock is moved forward one hour).
- Mutating anything without also updating derived fields like isDst and utcOffset.

The API should be modified to ensure that `DateTime` can only be used in safe ways.

## Proposal

Both options below requires all fields of `DateTime` to be made private to avoid manual construction and direct write access. This is a breaking change of course.

- **Option 1**: add assignment operators for the fields that are allowed to be mutated. These procs can update the derived fields and prevent invalid states. This is how it's done in D. It's a breaking change for code that writes to the fields.

- **Option 2**: embrace immutability and add procs for updating fields without mutation, e.g `dt = dt.withYear(2015)`. This is how it's done in Java. Deprecated overloads for field assignments can still be added to prevent breaking old code, which means that this option only breaks code that uses the `DateTime(...)` constructor.

Note that it only makes sense to update some fields. For example `utcOffset` and `isDst` should never be updated directly, so they can be made private without any way to update them. The fields `weekday` and `yearday` should likely be removed and replaced with procs that calculate the values on the fly. The only fields that should be allowed to be updated are the date & time fields, e.g year/month/day and so on.

**Comment by konsumlamm** [comment]
See https://github.com/nim-lang/Nim/pull/14197.
