### ISSUE TITLE
[RFC] Exceptions that inherit from `system.Defect` should not be tracked

### ISSUE THREAD

**Issue by GULPF** [nim-lang/RFCs#77]
The point of the exception tracking system is to know which exceptions needs to catched. Since exceptions that inherit from `system.Defect` should not be catched, there's no point in tracking them.

Exceptions that are raised from magic operations (like `OverflowError`) already bypass the tracking. The `assert`/`doAssert` procs use a trick to make their exception untrackable. Adding a simple rule that exceptions that inherit from `system.Defect` cannot be tracked would simplify things.

Another issue with tracking them is that using `{.push raises: [].}` becomes tedious, since there will be a bunch of exceptions that are irrelevant but still needs to be explicitly tracked.

**Comment by Araq** [comment]
This has finally been implemented and will be in version 1.4.
