### ISSUE TITLE
[RFC] {.hygienic.} template with {.dirty:some_outer_symbol.} escape hatch

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#78]
/cc @mratsim @Araq 

same motivation as https://github.com/nim-lang/Nim/issues/8208 but (IMO) better solution

```nim
proc bar_local1() = discard
when not defined(foo): var x_outer_maybe = 0
var x_local1 = 0

template fun*() {.hygienic.} = # maybe become new default in future release after deprecation period
  # same: rules aren't changed for these:
  proc bar_injected() = discard
  proc bar_not_injected() {.gensym.} = discard
  var x_not_injected = 0
  var x_injected {.inject.} = 0

  # new: these cannot access calling scope
  bar_local1()
  bar_injected()
  bar_not_injected()
  echo x_local1

  # new: escape hatch to allow dirty access to calling scope
  {.dirty:bar_outer1.}
  bar_outer1()

  when defined(foo): # these inject pragma can be conditional
    {.dirty:x_outer_maybe¸.}
  echo x_outer_maybe

  # `result` follows these rules, nothing special
  {.dirty:result.}
  result.add 10
```

## note
* with this proposal, there'd be very little use cases for `dirty` templates (maybe some valid use cases but most cases would be covered by this proposal)
* would likely fix https://github.com/nim-lang/Nim/issues/7791 /cc @krux02 

## related
* https://github.com/nim-lang/Nim/issues/8208 is related but I prefer my proposal because #8208 has serious issues:
  * would break too much code (my proposal doesn't break any code)
  * didn't provide escape hatch in hygienic templates
  * it required using `{.dirty.}` when some symbols needed outer scope, which is a blunt tool (and would prevent access to any local scope symbol)

**Comment by Araq** [comment]
Rejected.
