### ISSUE TITLE
universal conversion operator (cf D's `a.to!T`) (std.conv.to)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#84]
in D `std.conv.to` allows universal type conversions, it's used very frequently and simplifies code a lot.

Is there anything similar in nim? if not could we add it?

```d
import std.conv:to;
auto a1="123".to!int;
auto a2="123".to!double;
auto a3=123.to!string;

// custom conversion:
struct A{
  auto opCast(T) if(is(T==float) || is(T==double)) { return 1.0; }
}
auto a5=A.init.to!double;
```

Instead in nim I see `parseInt`, `parseBool`, etc which is:
* not as scalable (introduces tons of symbols)
* not as searcheable 
* not as elegant as D's `to`.
* not generic (doesn't work in generic code)

# proposed design:
see https://github.com/nim-lang/Nim/pull/7488

## related
* [easy way to convert between different data types? - Nim forum](https://forum.nim-lang.org/t/4177)
* https://scripter.co/notes/nim#representing-one-type-in-another

**Comment by hlaaftana** [comment]
Reiterating [my comment on a PR](https://github.com/nim-lang/Nim/pull/14147#issuecomment-620558099):

In line with `var T` becoming more important recently thanks to sugar.dup finally being implemented, I think the overload should be of `(var T, S)` where S is the old type and T is the new type. Like so:

```nim
import strutils

proc to(x: var float, str: string) = x = parseFloat(str)

var f: float
to(f, "1.0")
```

This is nice because we can have a generic `as` operator that calls this similar to `in`.

```nim
template `as`(toConvert: untyped, T: typedesc): T =
  var converted: T
  to(converted, toConvert)
  converted

# with previous code block:
doAssert ("1.0" as float) == 1.0
```

We can also do things like get information from the `var` we're converting to, though I don't know if this is a good idea (maybe good for case objects):

```nim
type Obj = object
  changeSign: bool
  num: int

proc to(obj: var Obj, n: int) =
  if obj.changeSign:
    obj.num = -n
  else:
    obj.num = n

var obj = Obj(changeSign: true)
to(obj, 5)
echo obj.num # -5
```

**Comment by timotheecour** [comment]
Here's my proposal:

* there's a unique `to` template (outplace):
```nim
template to*[S](a: S, T: typedesc): T =
  var ret: T
  mixin from
  from(ret, a)
  ret
```

* the real implementation is deferred to `from` (inplace) which can be overloaded:
```nim
proc from[T, S](result: T, a: S) =
  ...
```
code looks/reads naturally whether you use inplace (to) or outplace (from), eg:
```nim
# outplace form
echo s.bar.to(JsonNode)
echo s.bar.to BsonNode # obviously, also works without ()

# inplace form; eg when you want to reuse object to avoid allocations
var ret: Foo
foo.from(JsonNode)
```

* the main drawback of using a (universal) generic conversion function is that, in many languages, it can be hard to find which generic is selected in some code.

This is one of the main design goals of https://github.com/nim-lang/Nim/pull/12076, which allows you to retrieve the symbol (if any) that would be selected after sigmatch (or nil if no match):

```nim
foo.from(bar) # which `from` was picked? where is it declared?
inspect foo.from(bar) # this gives you the symbol selected after sigmatch (or prints where it's declared)
```

note that `nimsuggest` can't help here, since it can't know what T was instantiated with.

## special case: converting to string and parsing from string
these are so common they deserve a special case (but `to/from` could call these)
* see https://github.com/nim-lang/RFCs/issues/191 for conversion to string (in line with the above, it's using a single outline template that calls an overloaded inline proc)
* see https://github.com/nim-lang/Nim/pull/10346 for parsing from string (that PR was closed as better fit for nimble for now, but the idea is sound; although implementation should be updaded)

## note
* your suggestion `to(obj, 5)` doesn't read well, in particular in UFCS/MCS form: `obj.to(5)` doesn't quite make sense since arguments should be reversed; that's why I'm naming the inplace form as `from`: `obj.from(bar)`

## `a as T` doesn't carry its weight for keyword use
* I don't think `a as T` carries it's weight for the keyword `as`. `a.to T` is just as simple without using a reserved keyword and in many cases more convenient in expressions where you need parenthesis to disambiguate eg:

```
a or fun(1) as bool # no idea what grouping is used
a or (fun(1) as bool) # clear but increases nesting
a or fun(1).to(bool) # clear and doesn't increase nesting
```


## operator vs `to`
>  It can be an operator

IMO operators are overused and should usually be reserved for cases where operator precedence makes a difference, eg by removing 1 level of parenthesis in the expression; it shouldn't be used for cases where a regular proc could be used in its place.

eg: in https://github.com/nim-lang/Nim/pull/13023 (wrapnil operator) the initial idea `s.maybe.foo[12].bar.name[]` was improved by araq's suggestion of using an operator; this allows simplifying to: `?.s.foo[12].bar.name`

**Comment by hlaaftana** [comment]
As github syntax highlighting shows first thing in your post `from` is a keyword too. I can't think of a word to describe this operation (the one I wrote as to and you as from). I don't want an operator either. `become`? `emplace`?

Other languages don't have operators like `as` at such a low precedence like Nim does. In Nim it's equivalent to `in` and `==`, in Rust and Java they're immediately below unary operators (in Nim, equivalent to 9.5).

I think this should be in a package, so people can choose whether they want an operator or a keyword. Other packages can provide support.

**Comment by timotheecour** [comment]
> As github syntax highlighting shows first thing in your post from is a keyword too

* `a.from b` can already be used as shown below
* your PR https://github.com/nim-lang/Nim/pull/14241 also enables it's use as an operator, but IMO the UFCS/MCS is more natural with `from` (unlike `a and b` where operator makes more sense)
* one technical advantage of `as` over `to` is it allows writing things like `doAssert "13.3" as float == 13.3` (parens not needed unlike your snippet in https://github.com/nim-lang/RFCs/issues/84#issuecomment-620565574) whereas `to` would require some parens, eg: `doAssert "13.3".as(float) == 13.3`

```nim
when true:# D20200506T234004
  import strutils
  proc `from`[T, S](result: var T, a: S) =
    when S is string:
      when T is int: result = parseInt a
      elif T is float: result = parseFloat a
      else: doAssert false
    else: doAssert false

  template to*[S](a: S, T: typedesc): untyped =
    var ret: T
    # mixin `from` # doesn't seem needed, not super sure why
    ret.from a
    ret

  template `as`*[S](a: S, T: typedesc): untyped =
    var ret: T
    ret.from a
    ret

  proc main()=
    var ret: int
    ret.from "12" # that's the syntax that will be most often used
    `from`(ret, "12") # works too, useful in templates to "bind early"
    # ret from "12" # works pending https://github.com/nim-lang/Nim/pull/14241
    doAssert ret == 12
    doAssert "13".to(int) == 13
    doAssert "13.2".to(float) == 13.2
    let b = "13".to int
    doAssert b == 13
    doAssert "13.3".as(float) == 13.3
    ## only difference between to and as:
    doAssert "13.3" as float == 13.3 # possible
    # doAssert "13.4" to float == 13.4 # not possible
  main()
```

> Also a or fun(1) as bool correctly becomes a or (fun(1) as bool) and I don't see how that's not clear, all other languages do this (including Groovy).

well you have to "know" the precedence table and that it's not interpreted as `(a or fun(1)) as bool` whereas `a or fun(1).as bool` would be more obvious, but I guess that just boils down to RTFM, so fine I guess.


> I trust you but I can't think of these, if your ideas of as are incompatible with a (untyped, typedesc) overload then please tell me.

one of them was https://github.com/nim-lang/RFCs/issues/163 but I'm now thinking this could be done with a pragma instead; other uses I had in mind could also be done with a pragma. What I'd really like is for `alias` to become a keyword, for this: `alias foo = system.echo` (better syntax for https://github.com/nim-lang/Nim/pull/11992) but that's a separate topic.

> If all else fails, this should be in a package

then let's make sure it doesn't fail :). https://github.com/nim-lang/RFCs/issues/191 aside, `$` is useful **because** it's the standard stringification operator, making it useful in generic code. Anything that's package specific would defeat its purpose.


## Long story short
* `a.from b` is a good fit for the thing that's overloaded
* `a.to T` and `a.as T` (which can also be written `a as T`) both work, and I'd be fine with `as` since it allows `doAssert "13.3" as float == 13.3` without parens, unlike `to`

## one last thing: to reset or not to reset
that wasn't really discussed yet; IMO the thing that's overloaded should not reset:
```nim
# everything is defined in terms of `addFrom`
proc addFrom*[T, S](result: var T, a: S) = .. # this is what gets overloaded
  # no resetting of result

template `from`*[T, S](result: var T, a: S) = # single `from` template, doesn't get overloaded
  result.reset # resets
  result.addFrom(a)

template `as`*[S](a: S, T: typedesc): untyped = # single `to` template, doesn't get overloaded
  var ret: T
  ret.addFrom a
  ret
```

`from` and `as` are then just syntax sugar over `addFrom`, which is the only thing that needs to be overloaded.
Users code can choose between addFrom and from depending on whether they need reset or not. There are many use cases for not resetting, eg merging a json/bson object with some new data, or appending to a string or stream etc.

This gives a simple design where there's only 1 proc to overload, and you get `from` and `as` variants "for free"
