### ISSUE TITLE
`except:` should map to the more conservative`except CatchableError:` instead of `except Exception:`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#89]
follow up for https://github.com/nim-lang/Nim/issues/8237, and with the same principles ("Technically, assertion failures are not catchable."), `except:` should map to the more conservative`except CatchableError:` instead of `except Exception:`

User can always explicitly set `except Exception:` (or even `except Defect:`depending on his use case) when he needs, eg in unittests.

```nim
when defined(case1):
  # prints ok3 (OK!)
  try:
    doAssert false, "basf"
  except CatchableError:
    echo "ok1"
  except Exception:
    echo "ok3"

when defined(case2):
  # BUG: prints ok1; should give `Error: unhandled exception:` and behave like `except CatchableError:` which is a saner default
  try:
    doAssert false, "basf"
  except:
    echo "ok4"

when defined(case3):
  # BUG: this gives a C error: timn_t44_try_except_throwable.c:444:3: error: expected expression
  try:
    doAssert false, "basf"
  except:
    echo "ok4"
  except Defect:
    echo "ok5"
```

## note
* I remember someone mentioned a plan to deprecate `except:` but now that @araq implemented `CatchableError` as root of all ethically catchable exceptions, it makes sense to keep `except:` , and give it the meaning of `except CatchableError:`; it's a sensible default.
* this was part of original RFC https://github.com/nim-lang/Nim/issues/8237 (albeit more like a footnote...); the hard part was already done; this is a small but logical improvement

**Comment by hlaaftana** [comment]
A solution to foreign exceptions/exceptions that dont extend one of CatchableError or Defect is the following:

```nim
try:
  something()
except Defect:
  raise
except:
  handleException()
```

I think this is how it should be regardless, the system module can't categorize every single exception type in existence. CatchableError and Defect should be convenience options, not rule with an iron fist. As for whether or not the compiler can automate this, Defect could have a `{.uncatchable.}` pragma, in line with separating the standard library from the compiler, and the compiler should track this for `except:` statements.

**Comment by Araq** [comment]
With ``--panics:on`` and the refined ideas about what to track finally implemented, I think this RFC is of little relevance. Ping @timotheecour

**Comment by timotheecour** [comment]
with `--panics:on` it makes no difference indeed, but it does with `--panics:off` (which is the default), and we should reserve the concise syntax to be the safest, while still allowing user to customize for his needs

## proposal: `except {.foreign.}:`

* this should solve the foreign exception issue mentioned above
* makes the concise syntax `except:` be the safe one
* prevents at CT `getCurrentException()` in foreign branches
* `except CppException as e:` works as it does today, and in fact everything that already works would keep working the same apart from `except:`; and `except {.foreign.}:` would be introduced


```nim
try: something()
except: # same as `except CatchableError:`
	let e = getCurrentException() # same `e` as captured with `except CatchableError e:`
except CppException as e: # ok, catches a specific foreign exception
  discard
  #  let e2 = getCurrentException() # this should be CT error, since CppException is foreign (eg importcpp)
except AssertionError as e: # ok, catches an AssertionError (eg for testing or long running servers, or REPL's etc)
  discard
except Defect as e: # ok, catches all other Defects
  let e2 = getCurrentException() # ok, same as e
except {.foreign.}:
  discard
  # let e = getCurrentException() # this should give CT here in this except branch
```

note: this is partly related to https://github.com/nim-lang/Nim/issues/14369 btw.

**Comment by cooldome** [comment]
I agree with @Araq it can be closed.
The following example continue to work as is
```nim
try:
  something()
except Exception:
  handle all Nim Exceptions 
except:
  handleNonNimExceptions()
```

Comments about getCurrentException() are irrelevant. It can be used outside of try/except blocks and there are cases where it is required outside of try/except blocks.

**Comment by timotheecour** [comment]
my point about `getCurrentException`  was that it's guaranteed to be `nil` when used directly inside a `except Foo` block where `Foo` is foreign:
```nim
try: bar()
except Foo: # user is unaware this is a foreign exception
  let e = getCurrentException()
  echo e.msg # SIGSEGV
```
so that case could be made illegal at CT; however it wouldn't prevent other cases where `getCurrentException` is called inside a proc eg:
```
try: bar()
except Foo: # user is unaware this is a foreign exception
  fun()

proc fun() =
  let e = getCurrentException()
  echo e.msg # SIGSEGV
```

so maybe it's not worth the special case

Anyway, closing, it's sane enough currently.

**Comment by zah** [comment]
What is the rationale for rejecting this proposal?

The reason why `except:` should default to `CatchableErrror` is that inexperienced (or just tired) Nim developers tend to use it in their code as a synonym for "I don't care what kind of recoverable error happens here, I'll treat all errors in the same way". It's similar to writing `if errno != 0` or `if( SUCCEEDED(hr))` in C code.

But since `Defects` are not recoverable errors, stopping their propagation is almost never appropriate. In the rare situations where it is appropriate, the user can use an explicit `except Exception: ...` or `except Defect: ...`.

I've personally fixed more than 20 places in our codebase and third party libraries when `except: ...` was used inappropriately (the author should have used `except CatchableErrror`).

**Comment by timotheecour** [comment]
re-opening since there's no consensus yet. @zah what do you think of `except {.foreign.}:` to handle foreign exceptions?
this could be:
```nim
try: bar
except: # means `except CatchableError:`; preferred concise syntax is mapped to the safe, sane option
except AsstionDefect: # useful in some cases, eg test frameworks / servers that can't die / some repl implementations
except MyCppException: 1 particular foreign exception
except {.foreign.}: catch-all for foreign exceptions
except {.all.}: catch-all, both nim Exception and foreign exception
```

**Comment by zah** [comment]
We can perhaps work-around the problem of foreign exceptions with some magical types such as `CppException` and `JsException` that are specialized on the codegen level.

One could argue that in JavaScript mode (and C++), the default could be `CatchableError`, `JsException`, but reasoning about this quickly gets complicated (The JavaScript hierarchy itself can benefit from a Defect/Error distinction)

**Comment by timotheecour** [comment]
> We can perhaps work-around the problem of foreign exceptions with some magical types such as CppException and JsException that are specialized on the codegen level.

that'd work too; not that, unlike for C++, the following works for js:
```nim
try {
} catch (e) { // catches all exceptions AND have a reference to it via `e`
}
```
whereas in C++ the best catch-all you can do is:
```c++
catch(...) // no reference `e` possible
```

so `JsException` maybe doesn't have to be magic and can just be JsObject;
(and `e isinstanceof RangeError` etc can still be used by user code)

**Comment by alehander92** [comment]
ok, can't just `except:` include foreign exceptions as well by default? otherwise we expect the user to find out about a special pragma: this seems very bug-prone to me

**Comment by dom96** [comment]
Isn't this proposal a little unintuitive? I can't think of a programmer that wouldn't expect `except:` to catch ALL exceptions. Non-catchable exceptions are exceptions too. So why make the semantics special here?

**Comment by ringabout** [comment]
Now bareExcept gives a warning now. It can be closed.
