### ISSUE TITLE
Feature Request / RFC: Accessors for inferred effects

### ISSUE THREAD

**Issue by mjendrusch** [nim-lang/RFCs#91]
As far as I know, there is currently no way to retrieve the effects (tags, raises) inferred for a procedure
from its symbol in the VM, as `getImpl` only retrieves effects which have been set explicitly.
The only procedure I could find, which does something comparable is `documentRaises` in `sempass2`.
Should there already be a way to retrieve inferred effects for procedure symbols or should such a feature be in any way undesirable, feel free to close this issue. Otherwise, I would put together a pull request containing the following new functionality in the `macros` module, together with the 
corresponding additional opcode and behaviour in the VM:

```nim
proc getRaises(procedure: NimNode): NimNode
  ## Returns the nodes corresponding to the actual inferred exceptions `procedure` can raise
  ## inside an `nkBracket` node.
proc getTags(procedure: NimNode): NimNode
  ## Does the same as above for tag effects.
proc raises(procedure: NimNode, exception: typedesc[object]): bool
  ## Checks, whether procedure is inferred to raise exception.
proc hasTag(procedure: NimNode, tag: typedesc[object]): bool
  ## Does the same for tag effects.
```

Furthermore, I would include similar procedures for `writtenTo`, `escapes` and `new` effects behind a
`when false` for completeness' sake.

**Comment by Araq** [comment]
We now have ``std / effecttraits`` for this.
