### ISSUE TITLE
RFC: unified quasi-bool handling

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [nim-lang/RFCs#95]
We have several PRs (#8358 #8369 #8366) made by @krux02 and @PMunch proposing short-circuit evaluation schemes for Option[T] and other types.

This eventually can lead to zoo of incompatible decisions and once again make the language irregular and thus harder to learn. I can propose two ways to make this feature more orthogonal:

### Approach#1 - implement it in generic way:

Each type T that declares itself as quasi-bool should implement `toBool(x:T): bool`.

```Nim
proc `or`[T](x,y:T): T = 
    if toBool(x): x; else: y

proc find_first_nonempty[T] (c: Container[T]): Option[T] = 
    for x in c:
        if toBool(x):
            return Some(x)
...
```

This allows us to define a lot of operations in generic way, define hasToBool concept, and optionally - redefine if/while/... to accept quasi-bools as conditions. Eventually, by defining the single toBool operation, a type will get access to plenty of operations, including ones defined in application code. 

And users will need to learn these operations only once and then can apply them to any type with "nil value" concept instead of learning new set of operations for every new type.

In particular, I will be glad if we will copy Haskell operation names on Maybes :)

 
### Approach#2 - define guidelines

Just define guidelines - what extended 'or' and other ex-bool operations should do, and what they cannot do. Go with ad-hoc definitions. And may be later change it to the first approach.

**Comment by krux02** [comment]
I am closing this as rejected. Proposal 1 is rejected, because generics that are not constrainted to specific types for common operator will cause problems. They will be matched when they should not and error messages that were simple become complicated. Like mratsim said:

> Having generics procs not constrained to specific types (like seq, SomeInteger ...) should be done with care.

The guidelines could be added, but but since they are not ever formulated here I don't see a reason to keep this RFC alive.
