### ISSUE TITLE
[RFC] Support documentation translation

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/RFCs#96]
It's been requested to provide support for translating manuals in #8437.
I'm proposing an initial implementation to support translation in `nim doc`.
It can translate any docstring so it can be used to translate parts of the stdlib,
or examples and so on.
This will also allow Nim users to support translation in their own projects.
Later on it can be extended to allow Nim users to translate UIs as well.
The formats used are compatible with gettext to allow using the existing tools
e.g. Weblate, Poedit and similar GUI tools, automated translators etc.
Feedback from people with translation experience would be helpful!

- [x] Create a project entry on https://hosted.weblate.org/ or equivalent
- [ ] Write tool to extract docstrings into .pot files or another format
- [ ] Add translation support to `nim doc`
- [ ] Add translation support to `koch docs` (including language switching form/links)
- [ ] Add translation howto
- [ ] Publish translated webpages

**Comment by FedericoCeratto** [comment]
PR https://github.com/nim-lang/Nim/pull/8842 was closed without merging.

**Comment by Araq** [comment]
I'm completely against this for the following reasons:

- We don't have translators and even if we had, the resources are better spent on improving the English docs.
- We don't have translations either.
- Translated docs need to be maintained and could become outdated very quickly.
- Translated docs make internet searches *harder* for the programmers who happen to be fine with English and yet have some other mother tongue.
- Automatic language translation is getting better with every passing day.
