### ISSUE TITLE
Allow treating `result: var T` out parameters as return values

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/RFCs#99]
Using `result: var T` out parameters is nice in performance critical code since it allows reusing preallocated buffers. However out params are a pain to use for the majority of code that isn't performance critical:

* You can't use `let` to declare the variable at the call site, even if it is const after init.
* You can't use type inference when declaring the variable
* `let val = foo(init(arg))` becomes:
```nim
var tmp: T
tmp.init
let val = foo(arg)
```

I propose making the argument name `result` special, and allow callers to choose to use it as either an out param or a return value, without having to manually define both proc signatures. Essentially the compiler handles the mechanical task of translating code written like this:

```nim
proc readFile*(filename: string, result: var string)
let contents = readFile("some.file")
```
to work as if written like this:
```nim
proc readFile*(filename: string, result: var string)
let contents = (var tmp: string; readFile("some.file", result=string); string)
```

Note that named-argument syntax is used in the transformed call site to allow result argument to appear in any position.

I think this should only be done for arguments named `result` for a few reasons:
* It should be opt-in in the definition because you are declaring that `result` can be in default state (nil)
* `result` already has the meaning of "return value" in nim
* `result` is syntax highlighted specially already (at least in vim)
* It is already illegal to use a param named `result` in a non-void proc, so no new rule to ban that is needed

It may also be worth implicitly putting the {.restrict.} pragma on result params once they are special in the language so the compiler can optimize them similarly to return values (which are often implemented by implicit pointer anyway).

**Comment by hlaaftana** [comment]
Is this solved by `outplace` and the like now?

**Comment by Araq** [comment]
Resolved by ``sugar.dup``.
